#!/usr/bin/env python3
"""Generate tasks.md with 10,000+ granular implementation tasks."""

import os

sections = {}

# ─── CHART ENGINE CORE ────────────────────────────────────────────────────────
sections["CHART ENGINE — CORE RENDERING"] = [
    "Implement real-time WebSocket OHLCV streaming for sub-second updates",
    "Add Tick chart type (100, 250, 500, 1000 tick intervals)",
    "Add Renko chart type (configurable brick size)",
    "Add Kagi chart type (configurable reversal amount)",
    "Add Point & Figure chart type (box size / reversal)",
    "Add Range bar chart type (fixed range per bar)",
    "Add Volume bar chart type (fixed volume per bar)",
    "Add Dollar bar chart type (fixed dollar volume per bar)",
    "Implement multi-chart layout grid: 2x1 configuration",
    "Implement multi-chart layout grid: 1x2 configuration",
    "Implement multi-chart layout grid: 2x2 configuration",
    "Implement multi-chart layout grid: 3x1 configuration",
    "Implement multi-chart layout grid: 3x2 configuration",
    "Implement multi-chart layout grid: 4x1 configuration",
    "Implement multi-chart layout grid: 4x4 configuration",
    "Implement chart sync: crosshair sync across all panels in layout",
    "Implement chart sync: time scale sync across all panels",
    "Implement chart sync: selection sync (click one bar highlights all)",
    "Add Hollow Candles chart type (body outline only when close>open)",
    "Add Line Break chart type (3-line break with reversal logic)",
    "Add Baseline chart type with configurable baseline price",
    "Add Mountain/Area chart type with gradient fill",
    "Add Histogram chart type for volume profile overlay",
    "Implement zoom: pinch-to-zoom gesture support on touch devices",
    "Implement zoom: mouse wheel zoom with Alt for horizontal only",
    "Implement zoom: Ctrl+= / Ctrl+- keyboard shortcuts",
    "Implement zoom: double-click to fit all data in view",
    "Implement zoom: right-click drag for zoom rectangle selection",
    "Add price scale: logarithmic vs linear toggle button",
    "Add price scale: percentage mode (% change from first bar)",
    "Add price scale: indexed to 100 mode for comparison",
    "Add price scale: auto-scale toggle per pane",
    "Add price scale: lock price scale (disable auto-scale)",
    "Add price scale: invert price scale toggle",
    "Add price scale: right-side and left-side scale options",
    "Add price scale: custom price format (2/4/8 decimal places)",
    "Implement on-chart watermark with symbol + timeframe text",
    "Add pre-market / after-hours shading (gray overlay regions)",
    "Add session dividers (vertical lines at session open/close)",
    "Add news event pins on chart (small pin icon at news time)",
    "Add earnings/dividend event markers on chart timeline",
    "Add split adjustment toggle (keep pre-split prices optional)",
    "Implement chart templates: save indicator config to template",
    "Implement chart templates: load template from saved list",
    "Implement chart templates: delete template",
    "Implement chart templates: share template as JSON",
    "Add chart screenshot export as PNG with full resolution",
    "Add chart screenshot export as SVG vector format",
    "Add chart data export as CSV of visible bars",
    "Implement compare mode: overlay multiple symbols normalized to %",
    "Add comparison symbols selector dropdown with search",
    "Add benchmark overlay (SPY, QQQ) on price chart",
    "Implement replay/playback mode: step through bars historically",
    "Add replay: speed control (0.5x, 1x, 2x, 5x, 10x)",
    "Add replay: jump-to-date picker for replay start",
    "Add replay: play/pause/stop controls",
    "Add replay: forward/backward one bar step buttons",
    "Implement alert lines on chart (horizontal draggable price lines)",
    "Add on-chart price alert: trigger notification when price crossed",
    "Add on-chart percentage alert: e.g. +5% from current price",
    "Add on-chart volume spike alert (3x average volume)",
    "Add alert list panel showing all active alerts on chart",
    "Implement right-click context menu on chart background",
    "Right-click menu: Insert indicator at this position",
    "Right-click menu: Add text label at cursor position",
    "Right-click menu: Set alert at this price level",
    "Right-click menu: Copy price to clipboard",
    "Right-click menu: Add trendline from this point",
    "Right-click menu: Remove drawing object at cursor",
    "Right-click menu: Change bar color at selection",
    "Right-click menu: Take screenshot of chart",
    "Right-click menu: Reset chart to default",
    "Implement undo/redo stack for all drawing tool operations",
    "Add keyboard shortcut: D = toggle drawing mode",
    "Add keyboard shortcut: I = indicator panel toggle",
    "Add keyboard shortcut: A = alert panel toggle",
    "Add keyboard shortcut: T = text annotation tool",
    "Add keyboard shortcut: L = trendline tool",
    "Add keyboard shortcut: F = Fibonacci tool",
    "Add keyboard shortcut: H = horizontal line tool",
    "Add keyboard shortcut: V = vertical line tool",
    "Add keyboard shortcut: Space = fit chart to view",
    "Add keyboard shortcut: Escape = cancel current drawing",
    "Add keyboard shortcut: Delete = remove selected object",
    "Add keyboard shortcut: Ctrl+Z = undo last drawing",
    "Add keyboard shortcut: Ctrl+Y = redo last undo",
    "Implement chart crosshair data window (OHLCV + indicator values)",
    "Data window: show bid/ask/spread on crosshair hover",
    "Data window: show volume delta (buy vs sell volume)",
    "Data window: expandable indicator value display",
    "Data window: show timestamp and bar index",
    "Add status bar at bottom: cursor position (price, time)",
    "Add status bar at bottom: active drawing tool name",
    "Add status bar at bottom: zoom level percentage",
    "Add status bar at bottom: total bars loaded count",
    "Implement pane resizing via drag handle between panes",
    "Add auto-scale button per sub-pane",
    "Add collapse/expand button per sub-pane",
    "Add remove pane button per sub-pane",
    "Add add-pane button to open indicator browser",
    "Implement continuation loading: scroll left to load more history",
    "Add real-time bar update: last bar extends until next bar opens",
    "Add bar count display in chart header area",
    "Implement chart anti-aliasing for smooth line rendering",
    "Add chart grid style options (solid, dashed, dotted, none)",
    "Add chart background gradient option",
]

sections["CHART ENGINE — INDICATORS (110+)"] = [
    "Implement SMA (Simple Moving Average) indicator with period param",
    "Implement EMA (Exponential Moving Average) indicator",
    "Implement WMA (Weighted Moving Average) indicator",
    "Implement HMA (Hull Moving Average) indicator",
    "Implement DEMA (Double EMA) indicator",
    "Implement TEMA (Triple EMA) indicator",
    "Implement KAMA (Kaufman Adaptive MA) indicator",
    "Implement ALMA (Arnaud Legoux MA) indicator",
    "Implement VWAP (Volume Weighted Average Price) indicator",
    "Implement Anchored VWAP (user-selects anchor bar) indicator",
    "Implement VWAP bands (+/- 1,2,3 sigma) indicator",
    "Implement Bollinger Bands (20,2) indicator overlay",
    "Implement Bollinger Band Width indicator in sub-pane",
    "Implement Bollinger %B indicator in sub-pane",
    "Implement Keltner Channel indicator overlay",
    "Implement Donchian Channel indicator overlay",
    "Implement Envelope indicator (MA +/- %) overlay",
    "Implement PSAR (Parabolic SAR) indicator overlay dots",
    "Implement Supertrend indicator with color changes",
    "Implement Ichimoku Cloud (Tenkan/Kijun/Senkou/Chikou) full",
    "Implement RSI (Relative Strength Index) indicator sub-pane",
    "Implement Stochastic Oscillator (%K, %D) indicator",
    "Implement Stochastic RSI indicator",
    "Implement Williams %R indicator",
    "Implement CCI (Commodity Channel Index) indicator",
    "Implement ROC (Rate of Change) indicator",
    "Implement Momentum indicator",
    "Implement MACD (12,26,9) with signal and histogram",
    "Implement MACD Histogram standalone indicator",
    "Implement PPO (Percentage Price Oscillator) indicator",
    "Implement DPO (Detrended Price Oscillator) indicator",
    "Implement TSI (True Strength Index) indicator",
    "Implement CMO (Chande Momentum Oscillator) indicator",
    "Implement Aroon Oscillator indicator",
    "Implement Aroon Up/Down indicator",
    "Implement ADX (Average Directional Index) indicator",
    "Implement +DI / -DI (Directional Indicators) sub-pane",
    "Implement DMI (Directional Movement Index) indicator",
    "Implement ATR (Average True Range) indicator sub-pane",
    "Implement Historical Volatility indicator",
    "Implement Chaikin Volatility indicator",
    "Implement Volume bars indicator (colored by direction)",
    "Implement Volume MA overlay on volume bars",
    "Implement OBV (On-Balance Volume) indicator",
    "Implement Volume Oscillator indicator",
    "Implement CMF (Chaikin Money Flow) indicator",
    "Implement MFI (Money Flow Index) indicator",
    "Implement A/D (Accumulation/Distribution) Line indicator",
    "Implement Force Index indicator",
    "Implement Ease of Movement indicator",
    "Implement Elder Ray Bull Power indicator",
    "Implement Elder Ray Bear Power indicator",
    "Implement TRIX indicator",
    "Implement Mass Index indicator",
    "Implement Vortex Indicator (VI+ VI-)",
    "Implement Schaff Trend Cycle indicator",
    "Implement Know Sure Thing (KST) indicator",
    "Implement Fisher Transform indicator",
    "Implement Coppock Curve indicator",
    "Implement Pivot Points (Traditional) overlay",
    "Implement Pivot Points (Fibonacci) overlay",
    "Implement Pivot Points (Woodie) overlay",
    "Implement Pivot Points (Camarilla) overlay",
    "Implement Average Daily Range indicator",
    "Implement Chandelier Exit indicator overlay",
    "Implement ZigZag indicator overlay",
    "Implement High/Low 52-week lines overlay",
    "Implement Fractal indicator (Williams) overlay",
    "Implement Volume Profile (visible range) overlay",
    "Implement Volume Profile (fixed range) overlay",
    "Implement Volume Profile (session) overlay",
    "Implement Market Profile (TPO chart) overlay",
    "Implement Value Area High/Low lines overlay",
    "Implement Point of Control line overlay",
    "Implement Delta Volume (buy vs sell) indicator",
    "Implement Cumulative Delta indicator",
    "Implement Volume Delta histogram indicator",
    "Implement Relative Volume (RVOL) indicator",
    "Implement Squeeze Momentum (LazyBear) indicator",
    "Implement TTM Squeeze indicator",
    "Implement Elder Impulse System indicator (bar coloring)",
    "Implement Linear Regression Channel indicator",
    "Implement Standard Deviation Channel indicator",
    "Implement Regression Line indicator overlay",
    "Implement VIDYA (Variable Index Dynamic Average)",
    "Implement Rainbow Moving Averages (10 MAs stacked)",
    "Implement Guppy Multiple Moving Average display",
    "Implement Alligator indicator (Williams) overlay",
    "Implement AO (Awesome Oscillator) indicator",
    "Implement AC (Accelerator Oscillator) indicator",
    "Implement DeMarker indicator",
    "Implement Klinger Volume Oscillator",
    "Implement Choppiness Index indicator",
    "Implement Connors RSI indicator",
    "Implement Ultimate Oscillator indicator",
    "Implement Ehlers Fisher Transform indicator",
    "Implement Laguerre RSI indicator",
    "Implement McGinley Dynamic indicator",
    "Implement Relative Vigor Index (RVI)",
    "Implement Balance of Power indicator",
    "Implement Net Volume indicator",
    "Implement Positive/Negative Volume Index",
    "Implement Price Volume Trend indicator",
    "Implement Trend Intensity Index",
    "Implement Vertical Horizontal Filter",
    "Implement Qstick indicator",
    "Implement Swing Index indicator",
    "Implement Accumulative Swing Index",
    "Implement Hurst Exponent indicator",
    "Implement Fractal Dimension indicator",
]

sections["CHART ENGINE — DRAWING TOOLS (80+)"] = [
    "Implement Trend Line drawing tool with snap",
    "Implement Extended Line drawing tool (infinite both directions)",
    "Implement Ray drawing tool (infinite one direction)",
    "Implement Horizontal Line drawing tool",
    "Implement Vertical Line drawing tool",
    "Implement Cross / Plus drawing tool",
    "Implement Arrow drawing tool (directional)",
    "Implement Rectangle drawing tool with fill",
    "Implement Circle drawing tool",
    "Implement Triangle drawing tool",
    "Implement Ellipse drawing tool",
    "Implement Parallel Channel drawing tool",
    "Implement Regression Channel drawing tool",
    "Implement Flat Top/Bottom channel drawing tool",
    "Implement Disjoint Angle drawing tool",
    "Implement Pitchfork (Andrew's Pitchfork) drawing tool",
    "Implement Schiff Pitchfork drawing tool",
    "Implement Modified Schiff Pitchfork drawing tool",
    "Implement Pitchfan drawing tool",
    "Implement Fibonacci Retracement drawing tool",
    "Implement Fibonacci Extension drawing tool",
    "Implement Fibonacci Channel drawing tool",
    "Implement Fibonacci Fan drawing tool",
    "Implement Fibonacci Arc drawing tool",
    "Implement Fibonacci Spiral drawing tool",
    "Implement Fibonacci Time Zones drawing tool",
    "Implement Gann Box drawing tool",
    "Implement Gann Fan drawing tool",
    "Implement Gann Square drawing tool",
    "Implement Elliott Wave (12345 ABC) annotation tool",
    "Implement XABCD harmonic pattern annotation",
    "Implement Cypher harmonic pattern annotation",
    "Implement Bat harmonic pattern annotation",
    "Implement Gartley harmonic pattern annotation",
    "Implement Butterfly harmonic pattern annotation",
    "Implement Crab harmonic pattern annotation",
    "Implement Head and Shoulders annotation tool",
    "Implement Double Top/Bottom annotation tool",
    "Implement Cup and Handle annotation tool",
    "Implement Flag/Pennant annotation tool",
    "Implement Wedge annotation tool",
    "Implement Triangle pattern annotation tool",
    "Implement Text label drawing annotation",
    "Implement Price label drawing annotation",
    "Implement Note/sticky annotation tool",
    "Implement Long Position drawing (entry + stop + TP levels)",
    "Implement Short Position drawing (entry + stop + TP levels)",
    "Implement Forecast line drawing tool",
    "Implement Date Range selection box tool",
    "Implement Price Range box tool",
    "Implement Brush drawing (freehand) tool",
    "Implement Highlighter drawing (transparent fill) tool",
    "Implement Measurement tool (price + bars distance)",
    "Implement Magnet mode: snap drawings to OHLC values",
    "Implement Lock mode: prevent accidental movement of drawings",
    "Add drawing property: line color picker",
    "Add drawing property: line width selector (1-5px)",
    "Add drawing property: line style (solid/dashed/dotted)",
    "Add drawing property: fill color with opacity slider",
    "Add drawing property: font size for text labels",
    "Add drawing property: text alignment (left/center/right)",
    "Add drawing list panel (show all drawing objects on chart)",
    "Drawing list: select/highlight object from list",
    "Drawing list: toggle visibility of object (eye icon)",
    "Drawing list: delete object from list",
    "Drawing list: duplicate object",
    "Drawing list: group objects together",
    "Implement drawing clone: Alt+drag duplicates object",
    "Implement drawing snap to price levels",
    "Implement drawing snap to time (bar) levels",
    "Save drawings to backend (persist across sessions)",
    "Load saved drawings on chart open",
    "Export drawings as JSON file",
    "Import drawings from JSON file",
    "Implement drawing toolbar (TradingView-style left panel)",
    "Drawing toolbar: tool groups with flyout sub-menus",
    "Drawing toolbar: recent tool quick access",
    "Drawing toolbar: favorites section",
]

sections["ORDER BOOK & MARKET DEPTH"] = [
    "Implement L2 order book with real bid/ask ladder (20 levels)",
    "Add aggregated order book: group prices by configurable tick size",
    "Add order book: color intensity heatmap by size per level",
    "Add order book: highlight large blocks (whale orders >1000 shares)",
    "Add order book: animated row transitions on quote changes",
    "Add order book: spread display (mid price / BBO)",
    "Add order book: cumulative volume column",
    "Add order book: cumulative % of total depth column",
    "Add order book: size bar visualization per level (horizontal bars)",
    "Add order book: imbalance ratio display (bid vs ask side total)",
    "Add order book: DOM (Depth of Market) histogram visualization",
    "Add order book: volume at price histogram (VAP)",
    "Add order book: trades tape integration (last trade highlight)",
    "Add order book: filter minimum size (hide small orders below threshold)",
    "Add order book: count column (number of orders at each level)",
    "Implement Time & Sales tape with real print data",
    "Time & Sales: color by direction (buy=green, sell=red, neutral=gray)",
    "Time & Sales: large print highlighting (block trades >10k shares)",
    "Time & Sales: filter by side (all/buy/sell)",
    "Time & Sales: filter by minimum size input",
    "Time & Sales: speed modes (slow/normal/fast scroll)",
    "Time & Sales: aggregate prints at same price level",
    "Time & Sales: cumulative volume counter",
    "Time & Sales: print count per second display",
    "Implement sweep detection (large order eating through multiple levels)",
    "Implement bid/ask size ratio sparkline chart",
    "Add order book: configurable decimal precision",
    "Add order book: center-aligned price ladder mode",
    "Add order book: click-to-trade from price level",
    "Add order book: resize column widths",
]

sections["ORDER ENTRY & EXECUTION"] = [
    "Implement order ticket: market order type",
    "Implement order ticket: limit order with price input",
    "Implement order ticket: stop order type",
    "Implement order ticket: stop-limit order type",
    "Implement order ticket: trailing stop order type",
    "Implement order ticket: bracket order (entry + stop + TP)",
    "Implement order ticket: OCO (One Cancels Other) order type",
    "Implement order ticket: OTO (One Triggers Other) order type",
    "Implement order ticket: TWAP algorithm order",
    "Implement order ticket: VWAP algorithm order",
    "Implement order ticket: Iceberg order (display qty hiding total)",
    "Implement order ticket: FOK (Fill or Kill) time-in-force",
    "Implement order ticket: IOC (Immediate or Cancel) time-in-force",
    "Implement order ticket: AON (All or None) time-in-force",
    "Implement order ticket: GTC (Good Till Cancelled) duration",
    "Implement order ticket: GTD (Good Till Date) duration",
    "Implement order ticket: MOO (Market on Open) timing",
    "Implement order ticket: MOC (Market on Close) timing",
    "Add order preview: estimated total cost / margin required",
    "Add order preview: estimated market impact (% of ADV)",
    "Add order preview: risk check warnings (position limit, margin)",
    "Add order preview: position size / concentration check",
    "Implement one-click order confirmation dialog",
    "Implement order modify: change price/qty while order is open",
    "Implement order cancel button with confirmation dialog",
    "Implement cancel all orders button",
    "Add hotkey trading: F1=buy market, F2=sell market",
    "Add order book click-to-trade (1-click from DOM level)",
    "Implement position sizing calculator in order ticket",
    "Add risk/reward calculator in order ticket",
    "Add P&L estimate display for pending order",
    "Add slippage estimate for market orders",
    "Implement smart order routing display",
    "Add post-only toggle for maker orders",
    "Add reduce-only toggle for futures/options",
    "Implement order staging (review before submit batch)",
    "Add order templates: save common order parameter sets",
    "Implement batch order submission (multiple orders at once)",
    "Add order routing preference: exchange selector",
]

sections["BLOOMBERG TERMINAL — QUOTE DATA"] = [
    "Implement Bloomberg-style quote panel with comprehensive fields",
    "Add quote: open, high, low, close, volume, VWAP fields",
    "Add quote: bid size / ask size / spread display",
    "Add quote: yesterday close / prev day change",
    "Add quote: pre-market / after-hours price fields",
    "Add quote: 52-week high / 52-week low",
    "Add quote: market cap display (auto-format B/M/T)",
    "Add quote: float shares count",
    "Add quote: shares outstanding",
    "Add quote: dividend yield / next dividend date",
    "Add quote: ex-dividend date display",
    "Add quote: earnings date (next) with countdown",
    "Add quote: P/E ratio (trailing and forward)",
    "Add quote: EPS (TTM and next estimate)",
    "Add quote: beta (1Y monthly vs SPY)",
    "Add quote: short interest / short float %",
    "Add quote: institutional ownership %",
    "Add quote: insider ownership %",
    "Add quote: average daily volume (20-day / 50-day)",
    "Add quote: relative volume (today vs 20-day avg)",
    "Add quote: days to cover (short interest / ADTV)",
    "Add quote: book value per share",
    "Add quote: price-to-book ratio",
    "Add quote: price-to-sales ratio",
    "Add quote: enterprise value",
    "Add quote: EV/EBITDA ratio",
    "Add quote: revenue TTM",
    "Add quote: gross margin %",
    "Add quote: operating margin %",
    "Add quote: net margin %",
    "Add quote: return on equity %",
    "Add quote: return on assets %",
    "Add quote: debt-to-equity ratio",
    "Add quote: current ratio",
    "Add quote: quick ratio",
    "Add quote: free cash flow",
    "Add quote: free cash flow yield %",
    "Implement Bloomberg DES (Description) page equivalent",
    "DES: Company overview (business description paragraph)",
    "DES: Key executives table (name, title, age)",
    "DES: Sector / industry / sub-industry classification",
    "DES: Headquarters address, employees count, founded date",
    "DES: Stock exchange listing and index membership",
    "DES: Ticker symbols (Bloomberg, ISIN, CUSIP, SEDOL)",
    "DES: Related securities (preferred, warrants, ADRs)",
    "Implement Bloomberg GP (Graph Price) page equivalent",
    "GP: Multi-year price chart with key event annotations",
    "GP: Relative performance vs index overlay",
    "GP: Volume chart below price chart",
    "GP: Analyst price targets overlay on chart",
    "Implement Bloomberg FA (Fundamental Analysis) page",
    "FA: Income statement display (quarterly + annual toggle)",
    "FA: Balance sheet display (quarterly + annual toggle)",
    "FA: Cash flow statement display (quarterly + annual toggle)",
    "FA: Key ratios panel: P/E, P/B, P/S, EV/EBITDA",
    "FA: Growth rates: revenue, EPS, EBITDA YoY",
    "FA: Margin analysis: gross, operating, net margins chart",
    "FA: DuPont analysis breakdown visualization",
    "FA: Altman Z-score calculation display",
    "Implement Bloomberg RV (Relative Value) page",
    "RV: Peer comparison table (select sector peers)",
    "RV: Valuation multiples comparison bar chart",
    "RV: Growth comparison vs peers chart",
    "RV: Margin comparison vs peers chart",
    "RV: Return on equity / invested capital comparison",
    "Implement Bloomberg ERN (Earnings) page",
    "ERN: Earnings history chart (past 8 quarters)",
    "ERN: EPS estimates vs actuals bar chart",
    "ERN: Revenue estimates vs actuals bar chart",
    "ERN: Beat/miss rate percentage display",
    "ERN: Guidance history table",
    "ERN: Next earnings countdown timer widget",
    "Implement Bloomberg AN (Analyst Ratings) page",
    "AN: Buy/hold/sell recommendation counts bar",
    "AN: Average price target with range",
    "AN: Price target high/low spread chart",
    "AN: Recent rating changes feed",
    "AN: Individual analyst recommendations table",
    "AN: Estimate revision trend chart",
]

sections["BLOOMBERG TERMINAL — OPTIONS ANALYTICS"] = [
    "Implement full options chain with all strikes and expiries",
    "Options chain: real-time bid/ask/last update streaming",
    "Options chain: open interest column with change indicator",
    "Options chain: volume column with unusual activity flag",
    "Options chain: implied volatility column",
    "Options chain: Delta column display",
    "Options chain: Gamma column display",
    "Options chain: Theta column display",
    "Options chain: Vega column display",
    "Options chain: Rho column display",
    "Options chain: ITM/OTM/ATM row highlighting",
    "Options chain: P/C ratio display (put/call volume ratio)",
    "Options chain: OI change column (vs yesterday)",
    "Options chain: max pain calculation and display",
    "Options chain: breakeven price display per option",
    "Options chain: theoretical value column (BSM)",
    "Options chain: probability ITM column",
    "Options chain: probability of profit column",
    "Implement implied volatility surface (3D surface visualization)",
    "IV surface: plot term structure on X axis (days to expiry)",
    "IV surface: plot moneyness/delta on Y axis",
    "IV surface: color gradient for IV level intensity",
    "IV surface: historical vs current surface overlay toggle",
    "IV surface: rotate/zoom 3D view controls",
    "Implement volatility skew chart",
    "Vol skew: plot IV vs strike for selected expiry",
    "Vol skew: put skew vs call skew comparison",
    "Vol skew: term structure of ATM IV chart",
    "Vol skew: overlay multiple expiry skews",
    "Implement Greeks surface visualization (Delta surface, Gamma surface)",
    "Implement P&L diagram for selected options position",
    "P&L diagram: breakeven price lines",
    "P&L diagram: profit/loss zone coloring (green/red fill)",
    "P&L diagram: expiry P&L vs today's P&L toggle",
    "P&L diagram: animate time decay (theta simulation)",
    "P&L diagram: show max profit / max loss labels",
    "P&L diagram: probability distribution overlay",
    "Implement options strategy builder panel",
    "Strategy builder: Long Call template",
    "Strategy builder: Long Put template",
    "Strategy builder: Covered Call template",
    "Strategy builder: Cash-Secured Put template",
    "Strategy builder: Bull Call Spread template",
    "Strategy builder: Bear Put Spread template",
    "Strategy builder: Iron Condor template",
    "Strategy builder: Iron Butterfly template",
    "Strategy builder: Straddle template",
    "Strategy builder: Strangle template",
    "Strategy builder: Calendar Spread template",
    "Strategy builder: Diagonal Spread template",
    "Strategy builder: Ratio Spread template",
    "Strategy builder: Collar template",
    "Strategy builder: Synthetic Long/Short template",
    "Strategy builder: Jade Lizard template",
    "Strategy builder: custom multi-leg builder",
    "Implement BSM Greeks calculator with real-time update",
    "BSM: implied vol solver (Newton-Raphson method)",
    "BSM: Monte Carlo pricing mode for exotic options",
    "BSM: Binomial tree pricing method",
    "BSM: American option pricing (early exercise)",
    "Implement options probability calculator",
    "Options analytics: probability of profit at expiry",
    "Options analytics: probability of expiring ITM",
    "Options analytics: expected move by expiry date",
    "Options analytics: risk-adjusted return display",
    "Implement unusual options activity screener",
    "UOA: high volume vs OI anomaly detection",
    "UOA: large block trade identification",
    "UOA: put/call sweep detection",
    "UOA: flow sentiment score calculation",
    "UOA: dark pool print detection",
    "Implement options heat map (volume/OI by strike+expiry grid)",
    "Implement gamma exposure (GEX) chart per strike",
    "GEX: net gamma by strike visualization",
    "GEX: gamma flip level (zero GEX point) line on chart",
    "GEX: put wall / call wall identification labels",
    "Implement max pain vs current price comparison display",
    "Implement expected move cone overlay on price chart",
]

sections["BLOOMBERG TERMINAL — FIXED INCOME"] = [
    "Implement bond analytics panel (Bloomberg YAS equivalent)",
    "Bond: yield to maturity calculation engine",
    "Bond: yield to call calculation",
    "Bond: yield to worst calculation",
    "Bond: modified duration calculation",
    "Bond: effective duration calculation",
    "Bond: DV01 (dollar value of a basis point) calculation",
    "Bond: convexity calculation",
    "Bond: OAS (option-adjusted spread) calculation",
    "Bond: Z-spread calculation",
    "Bond: I-spread calculation",
    "Bond: T-spread (Treasury spread) calculation",
    "Bond: Macaulay duration calculation",
    "Bond: accrued interest calculator",
    "Bond: full price / clean price display",
    "Implement yield curve display (Bloomberg YCRV equivalent)",
    "Yield curve: US Treasury curve (3m, 1y, 2y, 5y, 10y, 30y)",
    "Yield curve: corporate credit curve overlay",
    "Yield curve: historical yield curve animation slider",
    "Yield curve: spread between two tenors display",
    "Yield curve: inversion detection and visual alert",
    "Yield curve: 3D historical curve surface",
    "Implement credit spread monitor panel",
    "Credit spreads: investment grade vs high yield comparison",
    "Credit spreads: CDS (Credit Default Swap) spreads display",
    "Credit spreads: iTraxx / CDX spread indices",
    "Implement SOFR / Fed Funds rate monitor widget",
    "Implement TED spread monitor widget",
    "Implement OIS-LIBOR spread monitor widget",
    "Implement bond screener (filter by sector, rating, maturity)",
    "Bond screener: filter by yield range",
    "Bond screener: filter by duration range",
    "Bond screener: filter by credit rating (AAA to D)",
    "Bond screener: filter by issuer type (sovereign, corporate, muni)",
    "Implement mortgage-backed securities analytics panel",
    "MBS: prepayment speed (PSA model)",
    "MBS: weighted average life calculation",
    "Implement bond ladder visualization tool",
    "Bond ladder: cash flow by maturity chart",
    "Bond ladder: reinvestment yield calculator",
]

sections["BLOOMBERG TERMINAL — FX / RATES / CRYPTO"] = [
    "Implement FX cross-rate matrix (all major pairs)",
    "FX matrix: EUR/USD, GBP/USD, USD/JPY, USD/CHF real-time",
    "FX matrix: AUD/USD, NZD/USD, USD/CAD real-time",
    "FX matrix: all cross-pairs computed from majors",
    "FX matrix: emerging market pairs (USD/BRL, USD/MXN, USD/TRY)",
    "FX matrix: real-time update with green/red color flash",
    "Implement FX forward curve display",
    "FX forward: spot / 1w / 1m / 3m / 6m / 1y rates",
    "FX forward: implied yield differential calculation",
    "Implement central bank rates monitor (8 major banks)",
    "Rates: Fed Funds Rate display and history",
    "Rates: ECB deposit rate display and history",
    "Rates: BOE bank rate display and history",
    "Rates: BOJ policy rate display",
    "Rates: SNB, RBA, RBNZ, BOC rates",
    "Rates: next meeting dates with countdown",
    "Rates: consensus probability from futures pricing",
    "Rates: historical rate decisions timeline chart",
    "Implement fed funds futures curve (implied path)",
    "FFF: implied rate expectations by meeting date",
    "Implement currency heat map (ranked by % change vs USD)",
    "Heat map: 1d, 1w, 1m, YTD performance comparison",
    "Implement FX carry trade calculator",
    "Implement currency correlation matrix heatmap",
    "Implement USD Index (DXY) composite display",
    "Implement crypto dashboard: BTC/USD real-time",
    "Crypto: ETH/USD real-time price",
    "Crypto: top 20 coins by market cap table",
    "Crypto: funding rate history chart (perpetual futures)",
    "Crypto: open interest chart for BTC/ETH",
    "Crypto: liquidation heatmap visualization",
    "Crypto: exchange inflow/outflow monitor",
    "Crypto: DeFi TVL tracker",
    "Crypto: gas fees monitor (ETH)",
    "Crypto: Bitcoin dominance chart",
]

sections["BLOOMBERG TERMINAL — MACRO / ECONOMICS"] = [
    "Implement economic calendar with 500+ events database",
    "Economic calendar: filter by country dropdown",
    "Economic calendar: filter by importance (1/2/3 stars)",
    "Economic calendar: filter by event type (GDP, CPI, NFP etc)",
    "Economic calendar: consensus vs prior vs actual columns",
    "Economic calendar: surprise score (actual - consensus) display",
    "Economic calendar: market impact indicator (high/med/low)",
    "Economic calendar: countdown timer to next release",
    "Economic calendar: historical calendar replay by date picker",
    "Economic calendar: week/day/month view toggle",
    "Implement FRED data integration (Federal Reserve Economic Data)",
    "FRED: GDP and components chart (consumption, investment, govt)",
    "FRED: CPI inflation data chart with YoY and MoM",
    "FRED: PCE deflator chart",
    "FRED: PPI inflation data chart",
    "FRED: NFP (Non-Farm Payrolls) chart with revisions",
    "FRED: Unemployment rate chart",
    "FRED: JOLTS job openings chart",
    "FRED: Initial/Continuing jobless claims chart",
    "FRED: Housing starts and permits chart",
    "FRED: Existing home sales chart",
    "FRED: NAHB housing market index chart",
    "FRED: ISM Manufacturing PMI chart",
    "FRED: ISM Services PMI chart",
    "FRED: Industrial Production chart",
    "FRED: Retail Sales chart (total and ex-auto)",
    "FRED: Consumer Confidence (Conference Board) chart",
    "FRED: Michigan Consumer Sentiment chart",
    "FRED: Trade balance chart",
    "FRED: Fed Balance Sheet total assets chart",
    "FRED: M1/M2 money supply charts",
    "Implement macro dashboard layout with key indicators",
    "Macro dashboard: recession bands (NBER dates)",
    "Macro dashboard: GDP growth bar chart by quarter",
    "Macro dashboard: Fed rate timeline with decision markers",
    "Implement global PMI heat map by country",
    "Implement global inflation heat map by country",
    "Implement commodity complex monitor",
    "Commodity: WTI crude oil price and chart",
    "Commodity: Brent crude oil price",
    "Commodity: Natural gas price",
    "Commodity: Gold spot price and chart",
    "Commodity: Silver spot price",
    "Commodity: Copper price",
    "Commodity: Corn, Soybeans, Wheat prices",
    "Implement CFTC commitment of traders (COT) display",
    "COT: commercial vs non-commercial positioning chart",
    "COT: net positioning history per commodity",
    "Implement global equity market performance table",
    "Global markets: US (SPX, NDX, DJIA, RTY)",
    "Global markets: Europe (STOXX, DAX, FTSE, CAC)",
    "Global markets: Asia (Nikkei, HSI, Shanghai, KOSPI)",
]

sections["BLOOMBERG TERMINAL — NEWS & SENTIMENT"] = [
    "Implement real-time news feed with article cards",
    "News feed: full-text article display in panel",
    "News feed: category filtering (earnings, macro, M&A, tech)",
    "News feed: symbol-specific news filtering",
    "News feed: source filtering (Reuters, AP, Dow Jones, etc)",
    "News feed: keyword search within articles",
    "News feed: sentiment score per article (NLP analysis)",
    "News feed: related tickers extraction from article text",
    "News feed: time-relative display (2 min ago, 1 hr ago)",
    "News feed: read tracking (mark as read, gray out)",
    "News feed: bookmark/save article functionality",
    "News feed: share article link",
    "Implement news sentiment aggregator per symbol",
    "Sentiment: daily sentiment score (-1 to +1) display",
    "Sentiment: 7-day sentiment trend sparkline chart",
    "Sentiment: mention volume bar chart over time",
    "Sentiment: source breakdown (news vs social media)",
    "Implement social media sentiment tracker",
    "Social: Twitter/X mention volume per symbol",
    "Social: trending hashtags related to markets",
    "Social: Reddit wallstreetbets mention tracker",
    "Social: StockTwits sentiment integration",
    "Implement SEC filing monitor feed",
    "SEC: 8-K real-time filing alerts",
    "SEC: 10-K / 10-Q quarterly/annual filings",
    "SEC: 13-F institutional holdings display",
    "SEC: Form 4 insider transaction feed",
    "SEC: EDGAR search integration",
    "Implement M&A deal tracker panel",
    "M&A: pending deals with premium/discount calculation",
    "M&A: arbitrage spread display",
    "M&A: deal closing probability from spread",
    "Implement analyst research feed",
    "Research: price target changes feed",
    "Research: rating changes feed (upgrade/downgrade)",
    "Research: estimate revision feed",
]

sections["BLOOMBERG TERMINAL — PORTFOLIO MANAGEMENT"] = [
    "Implement full portfolio management view with real positions",
    "Portfolio: real-time P&L (unrealized + realized) display",
    "Portfolio: position table: symbol, qty, avg cost, current price",
    "Portfolio: position table: market value, unrealized P&L, unrealized %",
    "Portfolio: position table: realized P&L, today P&L, total return",
    "Portfolio: position table: beta, weight, sector columns",
    "Portfolio: sector allocation pie/donut chart",
    "Portfolio: geography allocation chart",
    "Portfolio: market cap allocation (large/mid/small/micro) chart",
    "Portfolio: currency exposure breakdown chart",
    "Portfolio: factor exposure (value, growth, momentum, quality, vol)",
    "Portfolio: portfolio beta vs benchmark display",
    "Portfolio: tracking error vs benchmark calculation",
    "Portfolio: information ratio calculation",
    "Portfolio: Sharpe ratio (trailing 1Y) display",
    "Portfolio: Sortino ratio display",
    "Portfolio: maximum drawdown history chart",
    "Portfolio: drawdown waterfall chart visualization",
    "Portfolio: rolling 30/60/90-day return chart",
    "Portfolio: correlation matrix heatmap of holdings",
    "Portfolio: VaR (Value at Risk) 1d 95% gauge",
    "Portfolio: CVaR (Conditional VaR / Expected Shortfall)",
    "Portfolio: stress test scenarios panel",
    "Portfolio: scenario 2008 financial crisis simulation",
    "Portfolio: scenario 2020 COVID crash simulation",
    "Portfolio: scenario 2022 rate shock simulation",
    "Portfolio: scenario custom user-defined shock",
    "Portfolio: factor attribution analysis breakdown",
    "Portfolio: P&L attribution by sector chart",
    "Portfolio: P&L attribution by individual security",
    "Portfolio: P&L attribution by alpha vs beta components",
    "Portfolio: contribution to total risk by position",
    "Portfolio: liquidity analysis (days to liquidate each holding)",
    "Portfolio: margin utilization gauge",
    "Portfolio: leverage ratio display",
    "Portfolio: concentration risk alerts (>10% weight warning)",
    "Portfolio: rebalancing drift from target weights display",
    "Portfolio: rebalancing order list generation",
    "Implement portfolio optimizer (mean-variance framework)",
    "Optimizer: Black-Litterman model implementation",
    "Optimizer: risk parity allocation calculation",
    "Optimizer: maximum Sharpe optimization",
    "Optimizer: minimum variance optimization",
    "Optimizer: custom constraint inputs (max weight, sector limit)",
    "Optimizer: efficient frontier chart visualization",
    "Implement Brinson performance attribution model",
    "Brinson: allocation effect calculation",
    "Brinson: selection effect calculation",
    "Brinson: interaction effect calculation",
    "Brinson: total active return display",
    "Implement benchmark comparison table (SPY, QQQ, IWM, TLT)",
    "Implement custom benchmark creation from holdings",
    "Implement portfolio performance report generation",
]

sections["BLOOMBERG TERMINAL — RISK MANAGEMENT"] = [
    "Implement comprehensive risk dashboard layout",
    "Risk: portfolio VaR gauge (1-day 95%, 1-day 99%)",
    "Risk: portfolio VaR gauge (10-day 95%, 10-day 99%)",
    "Risk: VaR decomposition by individual position",
    "Risk: expected shortfall (CVaR) calculation and display",
    "Risk: stressed VaR calculation (worst historical periods)",
    "Risk: parametric VaR implementation",
    "Risk: historical simulation VaR implementation",
    "Risk: Monte Carlo VaR simulation (10,000 paths)",
    "Risk: delta-normal VaR for options portfolio",
    "Implement stress testing framework panel",
    "Stress test: custom scenario input (shock each factor)",
    "Stress test: historical scenario replay selector",
    "Stress test: factor shock scenarios (+/-10% rates)",
    "Stress test: factor shock scenarios (+/-25% equity)",
    "Stress test: tail risk scenarios (3-sigma events)",
    "Stress test: results table with position-level impact",
    "Implement P&L explain (Greeks-based decomposition)",
    "P&L explain: delta P&L contribution",
    "P&L explain: gamma P&L contribution",
    "P&L explain: theta P&L contribution",
    "P&L explain: vega P&L contribution",
    "P&L explain: rho P&L contribution",
    "P&L explain: unexplained residual tracking",
    "Implement real-time risk limit monitoring dashboard",
    "Risk limits: position limit per symbol configuration",
    "Risk limits: sector concentration limit",
    "Risk limits: VaR limit with alert threshold",
    "Risk limits: drawdown limit (circuit breaker trigger)",
    "Risk limits: gross exposure limit",
    "Risk limits: net exposure limit",
    "Risk limits: leverage limit monitoring",
    "Risk limits: 80% threshold warning alert",
    "Risk limits: 100% breach critical alert",
    "Risk limits: hard stop at 110% breach",
    "Implement correlation analysis panel",
    "Correlation: rolling 30-day correlation matrix",
    "Correlation: rolling 60-day correlation matrix",
    "Correlation: rolling 90-day correlation matrix",
    "Correlation: correlation breakdown in stress periods",
    "Correlation: principal component analysis visualization",
    "Implement systemic risk indicators panel",
    "Systemic: VIX index monitor with chart",
    "Systemic: HY OAS (credit spreads) monitor",
    "Systemic: TED spread monitor",
    "Systemic: MOVE index (bond volatility) monitor",
    "Systemic: FRA-OIS spread monitor",
    "Systemic: financial conditions index monitor",
    "Implement risk heat map by asset class visualization",
    "Risk heat map: equity risk column",
    "Risk heat map: rates risk column",
    "Risk heat map: credit risk column",
    "Risk heat map: FX risk column",
    "Risk heat map: commodity risk column",
]

sections["TRADINGVIEW — STOCK SCREENER"] = [
    "Implement stock screener with 100+ filter options",
    "Screener filter: market cap ranges (nano/micro/small/mid/large/mega)",
    "Screener filter: sector and industry GICS classification",
    "Screener filter: exchange (NYSE, NASDAQ, AMEX, OTC)",
    "Screener filter: country of domicile",
    "Screener filter: price range (min-max)",
    "Screener filter: volume range (absolute)",
    "Screener filter: relative volume (RVOL threshold)",
    "Screener filter: average volume (20-day, 50-day)",
    "Screener filter: price change % today",
    "Screener filter: price change % 1 week",
    "Screener filter: price change % 1 month",
    "Screener filter: price change % YTD",
    "Screener filter: price change % 1 year",
    "Screener filter: 52-week high proximity (%)",
    "Screener filter: 52-week low proximity (%)",
    "Screener filter: gap up/down % from prev close",
    "Screener filter: P/E ratio range (trailing)",
    "Screener filter: P/E ratio range (forward)",
    "Screener filter: P/S ratio range",
    "Screener filter: P/B ratio range",
    "Screener filter: EV/EBITDA range",
    "Screener filter: EV/Revenue range",
    "Screener filter: debt-to-equity range",
    "Screener filter: current ratio range",
    "Screener filter: return on equity range",
    "Screener filter: return on assets range",
    "Screener filter: profit margin % range",
    "Screener filter: operating margin % range",
    "Screener filter: revenue growth YoY range",
    "Screener filter: earnings growth YoY range",
    "Screener filter: free cash flow yield range",
    "Screener filter: dividend yield range",
    "Screener filter: payout ratio range",
    "Screener filter: beta range",
    "Screener filter: short interest % range",
    "Screener filter: institutional ownership % range",
    "Screener filter: insider transactions (recent 3m net)",
    "Screener filter: analyst consensus (buy/hold/sell categories)",
    "Screener filter: RSI range (overbought/oversold)",
    "Screener filter: MACD signal (bullish/bearish crossover)",
    "Screener filter: moving average crossover (SMA 50/200)",
    "Screener filter: Bollinger Band breakout signal",
    "Screener filter: volume spike today (>2x avg)",
    "Screener filter: new 52-week high today",
    "Screener filter: new 52-week low today",
    "Screener filter: ATR % (volatility level)",
    "Screener filter: earnings date within N days",
    "Screener filter: ex-dividend date upcoming",
    "Screener result: sortable columns (click header to sort)",
    "Screener result: configurable column set (add/remove columns)",
    "Screener result: mini sparkline chart per row (5-day)",
    "Screener result: export results to CSV file",
    "Screener result: save screen as named preset",
    "Screener result: open chart from result row click",
    "Screener result: add to watchlist from result row",
    "Screener result: pagination with configurable page size",
    "Screener preset: momentum leaders screen",
    "Screener preset: RSI oversold bounces screen",
    "Screener preset: earnings growth leaders screen",
    "Screener preset: high short interest screen",
    "Screener preset: insider buying screen",
    "Screener preset: dividend aristocrats screen",
    "Screener preset: new 52-week highs with volume",
    "Screener preset: technical breakouts screen",
    "Screener preset: value stocks (low P/E, low P/B)",
    "Screener preset: GARP (growth at reasonable price)",
    "Implement crypto screener tab in screener",
    "Crypto screener: market cap filter",
    "Crypto screener: 24h volume filter",
    "Crypto screener: % change filter",
    "Crypto screener: sector filter (DeFi, L1, Gaming)",
    "Implement ETF screener tab",
    "ETF screener: expense ratio filter",
    "ETF screener: AUM filter",
    "ETF screener: category filter",
]

sections["TRADINGVIEW — ALERTS SYSTEM"] = [
    "Implement price alert: crossing above price level",
    "Implement price alert: crossing below price level",
    "Implement alert: crossing up (enter from below)",
    "Implement alert: crossing down (enter from above)",
    "Implement alert: % change from current price",
    "Implement alert: % change from today's open",
    "Implement alert: volume spike (>3x 20-day avg)",
    "Implement alert: RSI enters overbought (>70)",
    "Implement alert: RSI enters oversold (<30)",
    "Implement alert: MACD bullish crossover",
    "Implement alert: MACD bearish crossover",
    "Implement alert: moving average crossover (SMA)",
    "Implement alert: Bollinger Band upper breach",
    "Implement alert: Bollinger Band lower breach",
    "Implement alert: new 52-week high",
    "Implement alert: new 52-week low",
    "Implement alert: earnings date reminder (N days before)",
    "Implement alert: custom formula condition",
    "Alert notification: browser push notification",
    "Alert notification: in-app toast notification",
    "Alert notification: webhook/API callback",
    "Alert notification: sound effect",
    "Alert setting: one-time vs recurring trigger",
    "Alert setting: expiry date configuration",
    "Alert management: list all active alerts",
    "Alert management: pause/resume individual alert",
    "Alert management: delete alert with confirmation",
    "Alert management: duplicate alert",
    "Alert management: group alerts by symbol",
    "Alert management: filter alerts by type",
    "Alert management: trigger history log with timestamps",
]

sections["TRADINGVIEW — STRATEGY EDITOR"] = [
    "Implement strategy code editor with syntax highlighting",
    "Editor: proper monospace font (Fira Code / JetBrains Mono)",
    "Editor: line numbers display",
    "Editor: code folding support for functions/blocks",
    "Editor: find and replace dialog (Ctrl+F, Ctrl+H)",
    "Editor: multi-cursor editing support",
    "Editor: auto-indentation on newline",
    "Editor: bracket matching and highlighting",
    "Editor: auto-complete for built-in indicator functions",
    "Editor: function documentation tooltip on hover",
    "Editor: error/warning highlighting (red/yellow underline)",
    "Editor: error messages in gutter",
    "Editor: format / beautify code button",
    "Editor: run strategy on chart (execute button)",
    "Editor: strategy results panel (trades list, stats)",
    "Editor: indicator output visualization panel",
    "Editor: variable inspector (watch values at each bar)",
    "Editor: save strategy to named file",
    "Editor: load strategy from saved files list",
    "Editor: version history with diff view",
    "Editor: template library (built-in strategy templates)",
    "Editor template: SMA crossover strategy",
    "Editor template: RSI mean reversion strategy",
    "Editor template: Breakout strategy",
    "Editor template: Pairs trading strategy",
    "Editor template: Bollinger band squeeze strategy",
    "Editor: undo/redo (Ctrl+Z, Ctrl+Y)",
    "Editor: copy/paste with proper formatting",
    "Editor: word wrap toggle",
    "Editor: minimap sidebar",
    "Editor: go to line number (Ctrl+G)",
]

sections["WATCHLIST IMPROVEMENTS"] = [
    "Implement multi-watchlist support (create 5+ separate lists)",
    "Watchlist: create new watchlist dialog",
    "Watchlist: rename watchlist inline",
    "Watchlist: delete watchlist with confirmation",
    "Watchlist: switch between watchlists via tabs/dropdown",
    "Watchlist: drag-and-drop reorder symbols within list",
    "Watchlist: import symbols from CSV file",
    "Watchlist: export symbols to CSV file",
    "Watchlist: add notes per symbol (tooltip on hover)",
    "Watchlist: color tag per symbol (categorization)",
    "Watchlist: column configuration dialog (choose visible columns)",
    "Watchlist columns: price, change, change%, volume",
    "Watchlist columns: market cap, P/E ratio",
    "Watchlist columns: 52w high, 52w low",
    "Watchlist columns: avg volume 20d, RSI, sector",
    "Watchlist: mini sparkline chart per row (5-day price)",
    "Watchlist: right-click context menu per symbol row",
    "Watchlist context: open chart for symbol",
    "Watchlist context: view options chain",
    "Watchlist context: view news feed",
    "Watchlist context: add alert for symbol",
    "Watchlist context: add to portfolio",
    "Watchlist context: copy ticker to clipboard",
    "Watchlist: group by sector toggle",
    "Watchlist: performance heatmap mode (tile view)",
    "Watchlist: sort by any column (click header)",
    "Watchlist: filter/search within list",
    "Watchlist: green/red row color based on change %",
    "Watchlist: flash animation on price update",
    "Watchlist: highlight new 52-week high symbol",
    "Watchlist: highlight unusual volume symbol",
    "Watchlist: earnings date badge next to symbol",
    "Watchlist: dividend date badge next to symbol",
    "Watchlist: analyst upgrade/downgrade badge",
    "Watchlist: save layout preference to localStorage",
    "Watchlist preset: FAANG stocks",
    "Watchlist preset: DOW 30 components",
    "Watchlist preset: crypto top 20 by market cap",
    "Watchlist preset: index ETFs (SPY, QQQ, IWM, TLT, GLD)",
    "Watchlist preset: S&P 500 sector ETFs (XLK, XLF, XLE, etc)",
]

sections["BACKTESTER V3 IMPROVEMENTS"] = [
    "BacktesterV3: fix walk-forward optimization tab (fully working)",
    "BacktesterV3: fix monte carlo simulation tab (fully working)",
    "BacktesterV3: fix comparison tab (benchmark vs strategy)",
    "BacktesterV3: fix tearsheet tab (full performance report)",
    "BacktesterV3: add detailed trade log with chart replay per trade",
    "BacktesterV3: add monthly returns heatmap table",
    "BacktesterV3: add annual returns bar chart",
    "BacktesterV3: add rolling Sharpe ratio chart",
    "BacktesterV3: add rolling sortino ratio chart",
    "BacktesterV3: add rolling max drawdown chart",
    "BacktesterV3: add trade distribution histogram (P&L buckets)",
    "BacktesterV3: add win/loss streak statistics",
    "BacktesterV3: add holding period distribution chart",
    "BacktesterV3: add MAE/MFE analysis chart (max adverse/favorable excursion)",
    "BacktesterV3: add trade P&L vs position duration scatter plot",
    "BacktesterV3: add cumulative P&L by trade number chart",
    "BacktesterV3: add drawdown duration histogram",
    "BacktesterV3: add underwater equity chart",
    "BacktesterV3: add risk-adjusted metrics (Sharpe, Sortino, Calmar, Omega)",
    "BacktesterV3: add exposure/position chart over time",
    "BacktesterV3: add sector exposure chart over time",
    "BacktesterV3: add turnover ratio display",
    "BacktesterV3: add commission impact analysis",
    "BacktesterV3: add slippage impact analysis",
    "BacktesterV3: export full backtest report as PDF",
    "BacktesterV3: export trade log as CSV",
    "BacktesterV3: save backtest result for later comparison",
    "BacktesterV3: load and compare saved backtest results",
    "BacktesterV3: add parameter sensitivity analysis chart",
    "BacktesterV3: add multi-timeframe backtest support",
    "Walk-forward: configurable number of windows (2-20)",
    "Walk-forward: in-sample / out-of-sample split slider",
    "Walk-forward: optimization metric selector",
    "Walk-forward: parameter grid builder UI",
    "Walk-forward: results table per window",
    "Walk-forward: out-of-sample equity curve chart",
    "Walk-forward: overfitting detection display",
    "Walk-forward: optimal parameter stability chart",
    "Monte Carlo: configurable simulation count (100-50,000)",
    "Monte Carlo: confidence level selector (90%, 95%, 99%)",
    "Monte Carlo: equity path distribution chart (spaghetti plot)",
    "Monte Carlo: drawdown distribution histogram",
    "Monte Carlo: final equity distribution histogram",
    "Monte Carlo: percentile outcomes table (5th, 25th, 50th, 75th, 95th)",
    "Monte Carlo: probability of ruin analysis",
    "Monte Carlo: worst-case scenario display",
    "Comparison: benchmark selector (SPY, QQQ, custom)",
    "Comparison: side-by-side equity curves chart",
    "Comparison: relative performance chart (alpha)",
    "Comparison: drawdown comparison chart",
    "Comparison: risk metrics comparison table",
    "Comparison: monthly returns comparison table",
]

sections["EXISTING PAGE — DASHBOARD IMPROVEMENTS"] = [
    "Dashboard: add real-time portfolio P&L gauge widget",
    "Dashboard: add market breadth indicator (advancers vs decliners)",
    "Dashboard: add sector performance heatmap (S&P sectors)",
    "Dashboard: add fear & greed index gauge widget",
    "Dashboard: add market regime indicator (bull/bear/neutral)",
    "Dashboard: add top movers table (top 10 gainers)",
    "Dashboard: add top losers table (top 10 losers)",
    "Dashboard: add volume leaders table (top 10 most active)",
    "Dashboard: add earnings this week calendar widget",
    "Dashboard: add global market summary row",
    "Dashboard: add VIX / volatility panel with chart",
    "Dashboard: add S&P 500 mini chart widget",
    "Dashboard: add NASDAQ mini chart widget",
    "Dashboard: add DOW mini chart widget",
    "Dashboard: add 10Y Treasury yield mini chart",
    "Dashboard: add USD index mini chart",
    "Dashboard: add Gold mini chart widget",
    "Dashboard: add Bitcoin mini chart widget",
    "Dashboard: add news headlines ticker at top",
    "Dashboard: add economic events today widget",
    "Dashboard: add positions summary widget",
    "Dashboard: add open orders count widget",
    "Dashboard: add buying power / margin available widget",
    "Dashboard: add sector rotation model display",
    "Dashboard: add put/call ratio indicator",
    "Dashboard: add breadth oscillator (McClellan)",
    "Dashboard: add advance/decline line chart mini",
    "Dashboard: add new highs vs new lows chart mini",
    "Dashboard: configurable widget layout (drag/drop)",
    "Dashboard: save custom layout preference",
]

sections["EXISTING PAGE — RISK PAGE IMPROVEMENTS"] = [
    "RiskUI2: add real VaR gauge with traffic light colors",
    "RiskUI2: add parametric VaR calculation display",
    "RiskUI2: add historical VaR calculation display",
    "RiskUI2: add Monte Carlo VaR with simulation chart",
    "RiskUI2: add CVaR (Expected Shortfall) gauge",
    "RiskUI2: add stress test scenarios panel",
    "RiskUI2: add factor exposure radar chart",
    "RiskUI2: add correlation heatmap of portfolio holdings",
    "RiskUI2: add Greeks exposure for options positions",
    "RiskUI2: add DV01 for fixed income positions",
    "RiskUI2: add position-level risk decomposition table",
    "RiskUI2: add sector risk contribution chart",
    "RiskUI2: add risk limit monitoring dashboard",
    "RiskUI2: add drawdown analysis chart",
    "RiskUI2: add tail risk analysis panel",
    "RiskUI2: add Monte Carlo equity path visualization",
    "RiskUI2: add worst-case scenario table",
    "RiskUI2: add systemic risk indicators section",
    "RiskUI2: add liquidity risk assessment",
    "RiskUI2: add concentration risk table",
]

sections["EXISTING PAGE — PORTFOLIO IMPROVEMENTS"] = [
    "PortfolioUI2: real-time P&L with live price updates",
    "PortfolioUI2: sector allocation donut chart",
    "PortfolioUI2: geography allocation chart",
    "PortfolioUI2: risk contribution treemap visualization",
    "PortfolioUI2: performance vs benchmark chart",
    "PortfolioUI2: drawdown history chart",
    "PortfolioUI2: rolling returns chart (30d/60d/90d)",
    "PortfolioUI2: monthly returns heatmap table",
    "PortfolioUI2: annual returns summary bar chart",
    "PortfolioUI2: trade history complete log",
    "PortfolioUI2: realized vs unrealized P&L breakdown",
    "PortfolioUI2: dividend income tracker",
    "PortfolioUI2: tax lot accounting display",
    "PortfolioUI2: cost basis tracking per holding",
    "PortfolioUI2: weight vs target weight comparison",
    "PortfolioUI2: rebalancing suggestion panel",
    "PortfolioUI2: margin utilization display",
    "PortfolioUI2: buying power display",
    "PortfolioUI2: portfolio statistics card (Sharpe, beta, etc)",
    "PortfolioUI2: export portfolio to CSV",
]

sections["EXISTING PAGE — OPTIONS MATRIX IMPROVEMENTS"] = [
    "OptionsMatrixUI2: full BSM Greeks surface rendering",
    "OptionsMatrixUI2: strategy payoff diagram with interactive legs",
    "OptionsMatrixUI2: IV skew chart per expiry date",
    "OptionsMatrixUI2: unusual options activity feed",
    "OptionsMatrixUI2: max pain calculator and display",
    "OptionsMatrixUI2: expected move cone on chart",
    "OptionsMatrixUI2: options flow heat map",
    "OptionsMatrixUI2: GEX chart by strike",
    "OptionsMatrixUI2: P/C ratio trend chart",
    "OptionsMatrixUI2: term structure of ATM IV chart",
    "OptionsMatrixUI2: options scanner presets",
    "OptionsMatrixUI2: multi-leg position builder",
    "OptionsMatrixUI2: probability calculator per position",
    "OptionsMatrixUI2: risk/reward summary card",
    "OptionsMatrixUI2: early assignment risk warning",
    "OptionsMatrixUI2: dividend impact on options pricing",
    "OptionsMatrixUI2: pin risk identification near expiry",
    "OptionsMatrixUI2: options premium decay chart (theta)",
    "OptionsMatrixUI2: sensitivity analysis (what-if vol, price)",
    "OptionsMatrixUI2: export chain to CSV",
]

sections["EXISTING PAGE — SCREENER IMPROVEMENTS"] = [
    "ScreenersUI2: implement 100+ technical + fundamental filters",
    "ScreenersUI2: add preset screens panel sidebar",
    "ScreenersUI2: add mini-chart thumbnails in results",
    "ScreenersUI2: add column configurator dialog",
    "ScreenersUI2: add sortable column headers",
    "ScreenersUI2: add export results to CSV",
    "ScreenersUI2: add save screen preset functionality",
    "ScreenersUI2: add pagination with page size selector",
    "ScreenersUI2: add real-time price updates in results",
    "ScreenersUI2: add click-to-chart from result row",
    "ScreenersUI2: add add-to-watchlist button per row",
    "ScreenersUI2: add sector/industry filter dropdown",
    "ScreenersUI2: add market cap range slider filter",
    "ScreenersUI2: add P/E ratio range filter",
    "ScreenersUI2: add volume filter (min/max)",
    "ScreenersUI2: add RSI filter (overbought/oversold)",
    "ScreenersUI2: add moving average crossover filter",
    "ScreenersUI2: add price change % filter (1d/1w/1m/1y)",
    "ScreenersUI2: add 52-week proximity filter",
    "ScreenersUI2: add short interest filter",
]

sections["EXISTING PAGE — SENTIMENT IMPROVEMENTS"] = [
    "SentimentUI2: implement NLP-powered sentiment scores",
    "SentimentUI2: social media volume chart (Twitter, Reddit)",
    "SentimentUI2: news sentiment aggregation per symbol",
    "SentimentUI2: fear & greed index display",
    "SentimentUI2: put/call ratio trend chart",
    "SentimentUI2: VIX term structure chart",
    "SentimentUI2: AAII investor sentiment survey",
    "SentimentUI2: CNN Money fear/greed components",
    "SentimentUI2: dark pool activity indicator",
    "SentimentUI2: insider buying/selling net chart",
    "SentimentUI2: short interest change tracker",
    "SentimentUI2: analyst rating distribution chart",
    "SentimentUI2: options flow sentiment score",
    "SentimentUI2: market breadth sentiment indicators",
    "SentimentUI2: sentiment history overlay on price chart",
]

sections["EXISTING PAGE — ECONOMIC CALENDAR"] = [
    "EconomicCalendarUI2: full event database (500+ events)",
    "EconomicCalendarUI2: country filter with flags",
    "EconomicCalendarUI2: importance filter (1/2/3 stars)",
    "EconomicCalendarUI2: event type filter categories",
    "EconomicCalendarUI2: consensus vs prior vs actual columns",
    "EconomicCalendarUI2: surprise score calculation and color",
    "EconomicCalendarUI2: market impact indicator per event",
    "EconomicCalendarUI2: countdown timer to next release",
    "EconomicCalendarUI2: week/day/month view toggle",
    "EconomicCalendarUI2: historical data on click expand",
    "EconomicCalendarUI2: chart for historical series per event",
    "EconomicCalendarUI2: alert subscription per event type",
    "EconomicCalendarUI2: real-time update when data released",
    "EconomicCalendarUI2: export calendar to ICS/CSV",
    "EconomicCalendarUI2: timezone selector for display",
]

sections["EXISTING PAGE — MONTE CARLO IMPROVEMENTS"] = [
    "MonteCarloUI2: implement 10,000+ simulation runs",
    "MonteCarloUI2: equity path spaghetti plot (all paths)",
    "MonteCarloUI2: confidence interval bands (5/25/50/75/95)",
    "MonteCarloUI2: final equity distribution histogram",
    "MonteCarloUI2: maximum drawdown distribution histogram",
    "MonteCarloUI2: percentile outcome table",
    "MonteCarloUI2: probability of ruin calculation",
    "MonteCarloUI2: probability of hitting target return",
    "MonteCarloUI2: worst-case equity path highlight",
    "MonteCarloUI2: best-case equity path highlight",
    "MonteCarloUI2: median equity path highlight",
    "MonteCarloUI2: input configuration: initial capital",
    "MonteCarloUI2: input configuration: number of simulations",
    "MonteCarloUI2: input configuration: confidence level",
    "MonteCarloUI2: use actual trade returns from backtest",
    "MonteCarloUI2: bootstrap vs parametric simulation toggle",
    "MonteCarloUI2: export simulation results to CSV",
    "MonteCarloUI2: save simulation configuration",
    "MonteCarloUI2: compare two simulation configurations",
    "MonteCarloUI2: animate simulation generation",
]

sections["EXISTING PAGE — WALK-FORWARD IMPROVEMENTS"] = [
    "WalkForwardUI2: configurable window count (2-20 slider)",
    "WalkForwardUI2: in-sample / out-of-sample split slider",
    "WalkForwardUI2: optimization metric dropdown selector",
    "WalkForwardUI2: parameter grid builder with ranges",
    "WalkForwardUI2: results table per optimization window",
    "WalkForwardUI2: out-of-sample equity curve chart",
    "WalkForwardUI2: overfitting detection indicator",
    "WalkForwardUI2: parameter stability chart across windows",
    "WalkForwardUI2: in-sample vs out-of-sample Sharpe comparison",
    "WalkForwardUI2: robustness score calculation",
    "WalkForwardUI2: optimal parameter convergence display",
    "WalkForwardUI2: window visualization timeline",
    "WalkForwardUI2: total out-of-sample performance metrics",
    "WalkForwardUI2: export results to CSV",
    "WalkForwardUI2: anchored vs rolling window toggle",
]

sections["EXISTING PAGE — AUTOPILOT IMPROVEMENTS"] = [
    "AutopilotUI2: real decision log with AI reasoning display",
    "AutopilotUI2: position sizing justification per trade",
    "AutopilotUI2: human-in-loop override controls",
    "AutopilotUI2: strategy selector (which algo to run)",
    "AutopilotUI2: risk parameter configuration panel",
    "AutopilotUI2: real-time P&L tracking per autopilot run",
    "AutopilotUI2: trade execution history table",
    "AutopilotUI2: market regime detection display",
    "AutopilotUI2: signal strength gauge per symbol",
    "AutopilotUI2: portfolio exposure summary",
    "AutopilotUI2: stop/start autopilot controls",
    "AutopilotUI2: emergency kill switch button",
    "AutopilotUI2: max daily loss limit input",
    "AutopilotUI2: max position count limit",
    "AutopilotUI2: approved universe (symbol whitelist)",
]

sections["EXISTING PAGE — RUNS & AUDIT IMPROVEMENTS"] = [
    "RunsUI2: live strategy execution monitoring dashboard",
    "RunsUI2: real-time P&L streaming per strategy run",
    "RunsUI2: risk gauge per active run",
    "RunsUI2: total run count and status breakdown",
    "RunsUI2: execution latency histogram",
    "RunsUI2: fill rate tracking per run",
    "RunsUI2: slippage analysis per trade",
    "RunsUI2: commission cost tracking",
    "RunsUI2: error/warning log per run",
    "RunsUI2: run timeline visualization (Gantt chart)",
    "RunsUI2: compare run performance table",
    "RunsUI2: export run log to CSV",
    "RunsUI2: audit trail with timestamps",
    "RunsUI2: decision justification per trade",
    "RunsUI2: regulatory compliance indicators",
]

sections["EXISTING PAGE — RESEARCH IMPROVEMENTS"] = [
    "ResearchUI2: analyst consensus chart (buy/hold/sell over time)",
    "ResearchUI2: price target range display",
    "ResearchUI2: estimate revision trends chart",
    "ResearchUI2: earnings surprise history chart",
    "ResearchUI2: revenue growth trend chart",
    "ResearchUI2: peer comparison table",
    "ResearchUI2: fundamental data summary card",
    "ResearchUI2: SEC filing links panel",
    "ResearchUI2: insider transaction feed",
    "ResearchUI2: institutional ownership changes",
    "ResearchUI2: short interest trend chart",
    "ResearchUI2: competitive landscape mapping",
    "ResearchUI2: supply chain visualization",
    "ResearchUI2: search research by keyword",
    "ResearchUI2: save research notes per symbol",
]

sections["EXISTING PAGE — SETTINGS IMPROVEMENTS"] = [
    "SettingsUI2: theme selector (Bloomberg/TradingView Dark/Light)",
    "SettingsUI2: font size preference (Small/Normal/Large)",
    "SettingsUI2: chart default settings (type, indicators)",
    "SettingsUI2: default timeframe preference",
    "SettingsUI2: notification preferences (email, push, sound)",
    "SettingsUI2: hotkey customization panel",
    "SettingsUI2: data refresh rate configuration",
    "SettingsUI2: timezone selection",
    "SettingsUI2: language preference",
    "SettingsUI2: number format (comma/dot separators)",
    "SettingsUI2: currency display preference (USD, EUR, etc)",
    "SettingsUI2: trading hours display preference",
    "SettingsUI2: order confirmation toggle",
    "SettingsUI2: sound effects toggle",
    "SettingsUI2: auto-save preference",
    "SettingsUI2: API key management",
    "SettingsUI2: data provider selection",
    "SettingsUI2: export all settings to JSON",
    "SettingsUI2: import settings from JSON",
    "SettingsUI2: reset all settings to defaults button",
]

sections["EXISTING PAGE — EXECUTION COCKPIT"] = [
    "ExecutionCockpitUI2: real-time order fill monitoring",
    "ExecutionCockpitUI2: slippage analysis per order",
    "ExecutionCockpitUI2: algo execution quality metrics",
    "ExecutionCockpitUI2: fill rate tracking",
    "ExecutionCockpitUI2: latency histogram per route",
    "ExecutionCockpitUI2: order status timeline per order",
    "ExecutionCockpitUI2: dark pool vs lit execution ratio",
    "ExecutionCockpitUI2: VWAP deviation analysis",
    "ExecutionCockpitUI2: implementation shortfall calculation",
    "ExecutionCockpitUI2: market impact measurement",
    "ExecutionCockpitUI2: broker comparison table",
    "ExecutionCockpitUI2: TCA (transaction cost analysis) report",
    "ExecutionCockpitUI2: order routing decision tree display",
    "ExecutionCockpitUI2: smart order router configuration",
    "ExecutionCockpitUI2: execution venue statistics",
]

sections["EXISTING PAGE — CONTROL TOWER"] = [
    "ControlTowerUI2: system health real-time dashboard",
    "ControlTowerUI2: circuit breaker status panel",
    "ControlTowerUI2: kill switch per strategy",
    "ControlTowerUI2: global kill switch (halt all trading)",
    "ControlTowerUI2: API service status monitor (health checks)",
    "ControlTowerUI2: WebSocket connection status display",
    "ControlTowerUI2: data feed latency monitor",
    "ControlTowerUI2: error rate monitor with alerting",
    "ControlTowerUI2: CPU/memory utilization display",
    "ControlTowerUI2: active connections count",
    "ControlTowerUI2: request rate limiter status",
    "ControlTowerUI2: deployment version display",
    "ControlTowerUI2: uptime tracking display",
    "ControlTowerUI2: incident history log",
    "ControlTowerUI2: escalation chain configuration",
]

sections["EXISTING PAGE — WORKFLOW BUILDER"] = [
    "WorkflowBuilderUI2: working drag-and-drop node placement",
    "WorkflowBuilderUI2: condition node real implementation",
    "WorkflowBuilderUI2: action node real implementation",
    "WorkflowBuilderUI2: trigger node (price, time, event)",
    "WorkflowBuilderUI2: save/load workflow definition",
    "WorkflowBuilderUI2: execute workflow button",
    "WorkflowBuilderUI2: workflow status monitoring",
    "WorkflowBuilderUI2: node connector lines (bezier curves)",
    "WorkflowBuilderUI2: node property panel (configure parameters)",
    "WorkflowBuilderUI2: variable passing between nodes",
    "WorkflowBuilderUI2: loop/repeat node type",
    "WorkflowBuilderUI2: error handling node type",
    "WorkflowBuilderUI2: notification node type",
    "WorkflowBuilderUI2: template library of common workflows",
    "WorkflowBuilderUI2: workflow execution history log",
]

sections["PERFORMANCE & CODE QUALITY"] = [
    "Implement virtual scrolling for all large data tables",
    "Implement WebWorker for heavy computations (indicators)",
    "Move indicator calculations to Web Worker thread",
    "Use canvas 2D direct rendering for high-frequency chart updates",
    "Implement request deduplication for market data API calls",
    "Add SWR-style caching for REST API responses",
    "Implement WebSocket connection pooling with shared connections",
    "Add exponential backoff for WebSocket reconnect attempts",
    "Implement lazy loading for all UI2 pages (dynamic import)",
    "Add React.Suspense boundaries for page loading states",
    "Implement service worker for offline asset caching",
    "Add proper loading skeleton states for all panels",
    "Implement error boundary with recovery for each component",
    "Add performance FPS monitoring overlay (dev mode)",
    "Implement chart rendering throttle (max 30fps)",
    "Audit and add React.memo to all pure components",
    "Audit and add useMemo for expensive computations",
    "Audit and add useCallback for event handlers",
    "Remove all console.log from production code paths",
    "Implement data normalization in Zustand store",
    "Add optimistic UI updates for order submission",
    "Implement request cancellation on component unmount (AbortController)",
    "Add bundle size analysis tooling",
    "Implement code splitting per major route",
    "Add TypeScript strict mode compliance for all files",
]

sections["ACCESSIBILITY IMPROVEMENTS"] = [
    "Add keyboard navigation for all interactive elements",
    "Add aria-label to all icon-only buttons",
    "Add aria-live regions for real-time data updates",
    "Add role=grid for all data tables with proper navigation",
    "Add focus trap for all modal/dialog components",
    "Ensure color contrast ratio > 4.5:1 for all text elements",
    "Add high-contrast mode toggle in settings",
    "Add reduce-motion mode (disable all animations)",
    "Add screen reader announcements for order confirmations",
    "Add keyboard shortcuts reference panel (?-key)",
    "Add visible focus indicators (outline rings) on all interactive elements",
    "Ensure all form inputs have visible text labels",
    "Add proper heading hierarchy (h1>h2>h3) throughout",
    "Add alt text for all chart images/visualizations",
    "Add skip-to-content link at page top",
]

sections["BLOOMBERG TERMINAL — DESIGN SYSTEM"] = [
    "Apply Bloomberg amber (#f5a623) as primary accent globally",
    "Use IBM Plex Mono / Roboto Mono for all numerical data",
    "Use dark background (#0a0a0a) for all panel backgrounds",
    "Use panel bg (#111111) for secondary/elevated surfaces",
    "Use border (#1e1e1e) for all panel/section borders",
    "Apply 2px amber top border to all major panel headers",
    "Terminal-style uppercase labels for all panel titles",
    "All numbers rendered in monospace font family",
    "Green (#26a69a) for all positive values throughout app",
    "Red (#ef5350) for all negative values throughout app",
    "Subtle amber glow on interactive element hover states",
    "Panel title bars with gradient from amber/6% to transparent",
    "Compact dense layout: minimize whitespace between elements",
    "Status dot indicators: amber=live, red=disconnected, green=ok",
    "Loading states: amber pulsing/skeleton animation pattern",
    "Error states: red background flash momentary effect",
    "Price flash: green flash on uptick, red flash on downtick",
    "Implement Bloomberg-style command line (F11 key toggle)",
    "Implement window tiling system (Bloomberg-style panels)",
    "Add function key shortcuts bar (F1-F8 display)",
    "Add white-on-black mode option (classic Bloomberg)",
    "Implement theme presets: Bloomberg, TradingView Dark, Light",
    "Compact mode: reduce all padding/margins for small screens",
    "Professional mode: ultra-dense data display option",
    "Apply amber-tinted custom scrollbar styling",
    "Apply custom text selection color (amber tint)",
    "Use minimal custom scrollbars on all panels",
    "Bloomberg-style panel maximize/restore behavior",
    "Panel drag-and-drop reposition capability",
    "Saved layout: restore last session panel arrangement",
    "User preference persistence (localStorage for all settings)",
    "Consistent 9-11px font size for all data displays",
]

sections["BACKEND — API INFRASTRUCTURE"] = [
    "Add /api/v4/quotes/stream WebSocket endpoint for real-time quotes",
    "Add /api/v4/bars/stream WebSocket endpoint for real-time OHLCV",
    "Add /api/v4/orderbook/stream WebSocket for L2 market depth",
    "Add /api/v4/trades/stream WebSocket for time & sales",
    "Implement /api/v4/news endpoint (aggregated news articles)",
    "Implement /api/v4/fundamentals/{symbol} endpoint",
    "Implement /api/v4/earnings/{symbol} endpoint",
    "Implement /api/v4/analyst/{symbol} endpoint with ratings",
    "Implement /api/v4/screener endpoint with filter engine",
    "Implement /api/v4/alerts CRUD endpoints (create/read/update/delete)",
    "Implement /api/v4/watchlists CRUD endpoints",
    "Implement /api/v4/portfolio endpoint with real positions",
    "Implement /api/v4/risk/var endpoint for VaR calculation",
    "Implement /api/v4/risk/stress endpoint for stress tests",
    "Implement /api/v4/yieldcurve endpoint for Treasury rates",
    "Implement /api/v4/fxrates endpoint for currency pairs",
    "Implement /api/v4/commodities endpoint for commodity prices",
    "Implement /api/v4/economic-calendar endpoint with events",
    "Implement /api/v4/options/greeks endpoint for computation",
    "Implement /api/v4/options/iv-surface endpoint",
    "Add proper rate limiting middleware to all endpoints",
    "Add JWT authentication middleware",
    "Add request/response logging with timing measurement",
    "Add gzip response compression middleware",
    "Add proper CORS configuration for production",
    "Add health check /api/health endpoint",
    "Add metrics /api/metrics endpoint (Prometheus format)",
    "Implement SQLite database for user data persistence",
    "Add API versioning strategy (v4/v5 migration path)",
    "Add OpenAPI/Swagger documentation generation",
    "Add request validation with Pydantic v2 for all endpoints",
    "Implement in-memory caching layer for frequently accessed data",
    "Add WebSocket heartbeat/ping-pong keepalive",
    "Add graceful shutdown handler for clean connection close",
    "Add request ID tracking for debugging",
]

sections["BACKEND — DATA PROVIDERS"] = [
    "Integrate Alpaca Markets API for live US equity data",
    "Alpaca: real-time quotes via WebSocket streaming",
    "Alpaca: historical bars (minute, hour, day timeframes)",
    "Alpaca: order routing (submit/cancel/modify orders)",
    "Alpaca: account and position data retrieval",
    "Integrate yfinance for historical fundamental data",
    "yfinance: daily/weekly/monthly OHLCV bar data",
    "yfinance: fundamental data (P/E, EPS, revenue, etc)",
    "yfinance: earnings dates and surprise data",
    "yfinance: options chain data (all strikes/expiries)",
    "yfinance: company profile and description",
    "yfinance: institutional holders data",
    "yfinance: insider transactions data",
    "Integrate Alpha Vantage for economic indicators",
    "Alpha Vantage: GDP, CPI, NFP economic series",
    "Alpha Vantage: sector performance data",
    "Integrate FRED API for macro data",
    "FRED: 500+ economic time series access",
    "FRED: real-time data update polling",
    "Data validation: check for missing bars in time series",
    "Data validation: check for price outlier anomalies",
    "Data normalization: handle stock split adjustments",
    "Data normalization: handle dividend adjustments",
    "Implement data pipeline health monitoring",
    "Data pipeline: alert on feed delay > 5 seconds",
    "Data pipeline: automatic failover to backup data source",
    "Cache historical data in local SQLite for offline access",
    "Implement data quality scoring per symbol per source",
    "Add data refresh scheduler (configurable intervals)",
    "Add stale data detection and warning system",
]

sections["BACKEND — COMPUTATION ENGINES"] = [
    "Implement 60+ technical indicators in Python backend",
    "Backend indicator: SMA (configurable period)",
    "Backend indicator: EMA (configurable period)",
    "Backend indicator: WMA (configurable period)",
    "Backend indicator: Bollinger Bands (period, std_dev)",
    "Backend indicator: RSI (period)",
    "Backend indicator: MACD (fast, slow, signal)",
    "Backend indicator: Stochastic (K, D, smooth)",
    "Backend indicator: ATR (period)",
    "Backend indicator: ADX (period)",
    "Backend indicator: CCI (period)",
    "Backend indicator: OBV (volume indicator)",
    "Backend indicator: VWAP (session basis)",
    "Backend indicator: Ichimoku Cloud (full 5 components)",
    "Backend indicator: Parabolic SAR (step, max)",
    "Backend indicator: Williams %R (period)",
    "Backend indicator: MFI (period)",
    "Backend indicator: CMF (period)",
    "Backend indicator: Force Index (period)",
    "Backend indicator: Aroon Up/Down (period)",
    "Backend indicator: Supertrend (period, multiplier)",
    "Backend indicator: Keltner Channels (period, multiplier)",
    "Backend indicator: Donchian Channels (period)",
    "Backend indicator: Volume Profile (num_bins)",
    "Implement Black-Scholes-Merton options pricing engine",
    "BSM: European call/put pricing",
    "BSM: implied volatility solver (Newton-Raphson)",
    "BSM: all Greeks computation (delta, gamma, theta, vega, rho)",
    "BSM: American option pricing (binomial tree)",
    "Implement Monte Carlo simulation engine",
    "Monte Carlo: geometric Brownian motion paths",
    "Monte Carlo: bootstrap historical returns",
    "Monte Carlo: drawdown distribution computation",
    "Monte Carlo: percentile statistics computation",
    "Implement portfolio optimization engine",
    "Optimizer: mean-variance optimal portfolio",
    "Optimizer: minimum variance portfolio",
    "Optimizer: maximum Sharpe portfolio",
    "Optimizer: risk parity allocation",
    "Optimizer: Black-Litterman model",
    "Optimizer: efficient frontier calculation",
    "Implement VaR computation engine",
    "VaR: parametric (variance-covariance) method",
    "VaR: historical simulation method",
    "VaR: Monte Carlo simulation method",
    "VaR: component VaR decomposition",
    "Implement stress testing engine",
    "Stress: historical scenario replay",
    "Stress: factor shock scenarios",
    "Stress: custom scenario builder",
    "Implement P&L attribution engine",
    "PnL: sector-level attribution",
    "PnL: factor-level attribution (Brinson model)",
    "PnL: Greeks-based attribution for options",
    "Implement yield curve construction engine",
    "Yield curve: bootstrap from treasury prices",
    "Yield curve: interpolation (cubic spline)",
    "Yield curve: Nelson-Siegel model fitting",
    "Implement bond analytics engine",
    "Bond: price from yield calculation",
    "Bond: yield from price calculation",
    "Bond: duration and convexity calculation",
    "Bond: DV01 calculation",
]

sections["TESTING — UNIT TESTS"] = [
    "Write unit tests for BacktestEngine.run() all strategies",
    "Write unit tests for BacktestEngine MA cross strategy signals",
    "Write unit tests for BacktestEngine RSI mean reversion signals",
    "Write unit tests for BacktestEngine Bollinger band signals",
    "Write unit tests for BacktestEngine breakout strategy signals",
    "Write unit tests for all commission models (Fixed, PerShare, Percentage, Tiered)",
    "Write unit tests for all slippage models (Fixed, Volume)",
    "Write unit tests for position sizers (FixedFractional, ATR, Kelly)",
    "Write unit tests for BacktestMetrics calculation accuracy",
    "Write unit tests for BSM European call pricing",
    "Write unit tests for BSM European put pricing",
    "Write unit tests for BSM implied vol solver convergence",
    "Write unit tests for BSM Greeks (delta, gamma, theta, vega, rho)",
    "Write unit tests for VaR parametric calculation",
    "Write unit tests for VaR historical simulation",
    "Write unit tests for portfolio optimizer (mean-variance)",
    "Write unit tests for portfolio optimizer (min variance)",
    "Write unit tests for SMA indicator correctness",
    "Write unit tests for EMA indicator correctness",
    "Write unit tests for RSI indicator correctness",
    "Write unit tests for MACD indicator correctness",
    "Write unit tests for Bollinger Bands indicator correctness",
    "Write unit tests for ATR indicator correctness",
    "Write unit tests for VWAP indicator correctness",
    "Write unit tests for Stochastic indicator correctness",
    "Write unit tests for order book aggregation logic",
    "Write unit tests for P&L calculation engine",
    "Write unit tests for Brinson attribution model",
    "Write unit tests for Monte Carlo path generation",
    "Write unit tests for yield curve bootstrap",
    "Write unit tests for bond pricing calculations",
    "Write unit tests for FX cross-rate matrix computation",
    "Write unit tests for economic calendar data parsing",
    "Write unit tests for screener filter engine",
    "Write unit tests for alert trigger evaluation",
]

sections["TESTING — INTEGRATION TESTS"] = [
    "Write integration tests for /api/v4/backtest/run endpoint",
    "Write integration tests for /api/v4/backtest/walkforward",
    "Write integration tests for /api/v4/backtest/montecarlo",
    "Write integration tests for /api/v4/options/chain endpoint",
    "Write integration tests for /api/v4/options/greeks endpoint",
    "Write integration tests for /api/v4/risk/var endpoint",
    "Write integration tests for /api/v4/screener endpoint",
    "Write integration tests for /api/v4/indicators/compute endpoint",
    "Write integration tests for /api/v4/portfolio endpoint",
    "Write integration tests for /api/v4/alerts CRUD",
    "Write integration tests for /api/v4/watchlists CRUD",
    "Write integration tests for all API endpoints returning 200",
    "Write integration tests for all API validation (400 on bad input)",
    "Write integration tests for WebSocket connection lifecycle",
    "Write integration tests for data provider fallback chain",
]

sections["TESTING — E2E TESTS"] = [
    "Write E2E test: load Trading page, verify chart renders",
    "Write E2E test: load Dashboard, verify all widgets render",
    "Write E2E test: run backtest, verify results display",
    "Write E2E test: options chain loads with Greek values",
    "Write E2E test: screener executes and shows results",
    "Write E2E test: watchlist add/remove symbol works",
    "Write E2E test: alert creation and display works",
    "Write E2E test: portfolio page shows positions",
    "Write E2E test: risk page shows VaR calculations",
    "Write E2E test: sentiment page shows data",
    "Write E2E test: economic calendar displays events",
    "Write E2E test: settings changes persist",
    "Write E2E test: all sidebar navigation works",
    "Write E2E test: command palette opens and searches",
    "Write E2E test: order ticket submission flow",
]

# ─── GENERATE REPETITIVE SUBTASKS ─────────────────────────────────────────────

# Per-page Bloomberg styling tasks (200 pages × ~5 tasks each = 1000)
pages = [
    "DashboardUI2", "TradingUI2", "PortfolioUI2", "PortfolioV2UI2",
    "RiskUI2", "AlertsUI2", "OrdersUI2", "ScreenersUI2", "ResearchUI2",
    "SentimentUI2", "SentimentV2UI2", "MonteCarloUI2", "MonteCarloV2UI2",
    "WalkForwardUI2", "WalkForwardV2UI2", "WalkForwardV3UI2",
    "BacktesterV3UI2", "BacktestUI2", "BacktestV4UI2",
    "OptionsMatrixUI2", "ExecutionCockpitUI2", "ControlTowerUI2",
    "WorkflowBuilderUI2", "AutopilotUI2", "AutopilotV2UI2",
    "NovaUI2", "StrategyStudioV3UI2", "StrategyBuilderV2UI2",
    "SettingsUI2", "RunsUI2", "AutomationUI2", "AutomationV2UI2",
    "OpsUI2", "SearchUI2", "SearchV2UI2", "SearchUXV3UI2",
    "EconomicCalendarUI2", "BlotterUI2", "BrokerV2UI2",
    "AgentUI2", "AgentBuilderUI2", "AgentRegistryUI2",
    "PerformanceUI2", "PerformanceV2UI2", "PlatformHealthUI2",
    "PlatformHealthV4UI2", "SystemHealthUI2", "ObservabilityUI2",
    "ObservabilityV2UI2", "TelemetryUI2", "IncidentsUI2",
    "ComplianceUI2", "AuditorUI2", "DataHealthUI2",
    "ProductizationUI2", "GlobalReadinessUI2", "MarketplaceUI2",
    "DerivativesOmsUI2", "HedgeFundUI2", "LiquidityUI2",
    "VolSurfaceUI2", "VolScannerUI2", "PayoffLabUI2",
    "FuturesCurveUI2", "SpreadToolsUI2", "CrossAssetQuoteUI2",
    "MicrostructureUI2", "FactorModelUI2", "SmartRoutingUI2",
    "RatesMonitorUI2", "CorporateActionsUI2", "PreTradeRiskUI2",
    "StressScenariosUI2", "RegimeUI2", "ScenarioSimUI2",
    "StrategyOptimizerUI2", "StrategySimUI2", "CollaborationUI2",
    "BqlQueryUI2", "QueryStudioUI2", "DatasetSnapshotUI2",
    "ResearchNotebookUI2", "ExportUI2", "ReplayUI2",
    "DecisionExplorerUI2", "DecisionExplainerV2UI2",
    "PnlExplainUI2", "HedgeEngineUI2", "RiskNetworkUI2",
    "ConvergenceCockpitV1UI2", "ReconciliationUI2",
    "ThemeClusteringUI2", "AnomaliesUI2", "DriftDetectionUI2",
    "NewsEnrichmentUI2", "AltDataUI2", "SignalMarketUI2",
    "SignalProvenanceUI2", "AttributionUI2", "ScoringUI2",
    "DiscoveryUI2", "MonitorUI2", "KillSwitchRecoveryUI2",
    "CrossAccountUI2", "CrossMarginUI2", "SweepV2UI2",
    "BacktestContractUI2", "NLWorkflowUI2", "WorkflowsV3UI2",
    "RobustnessUI2", "MarketSessionV2UI2", "MarketHoursUI2",
    "GreeksServiceUI2", "RiskGovernanceUI2", "DerivativesGovUI2",
    "EntitlementsUI2", "AccessibilityAuditUI2", "AppSandboxUI2",
    "SandboxRunnerUI2", "PluginRuntimeUI2", "DevPortalUI2",
    "SdkApiUI2", "ExportBundleUI2", "MarketplaceTrustUI2",
    "BillingEventsUI2", "UsageMeteringUI2", "CostProfilerUI2",
    "TenantQuotaUI2", "DataResidencyUI2", "JurisdictionUI2",
    "MultiRegionUI2", "RegionalFailoverUI2", "SafeActionsUI2",
    "CapacityPlanUI2", "SupportSlaUI2", "ThirdPartyRiskUI2",
    "PartnerCiUI2", "PolicyCodeUI2", "ApprovalChainUI2",
    "ApprovalQueueUI2", "PolicyAttestationUI2", "PolicySignalUI2",
    "SurveillanceUI2", "SupervisoryUI2", "ControlFrameworkUI2",
    "ControlsDomainUI2", "AiGovernanceUI2", "AIProviderStatusUI2",
    "AIStrategyUI2", "ModelRouterUI2", "PromptFirewallUI2",
    "EvalHarnessUI2", "AgentEvalHarnessUI2", "AgentToolsUI2",
    "SearchExplainUI2", "EvidenceGraphUI2", "EvidenceVaultUI2",
    "ResearchGovernanceUI2", "ResearchQueueUI2", "EntityResolutionUI2",
    "DataSpineUI2", "ElasticsearchUI2", "ElastiHackUI2",
    "EsOpsUI2", "DlqOpsUI2", "ExtObservabilityUI2",
    "HotPathUI2", "LatencyBudgetUI2", "PerfBudgetUI2",
    "PlatformDebtUI2", "ReleaseQualityUI2", "ReliabilityEconUI2",
    "SsoHardeningUI2", "CompatMatrixUI2", "OperatorEnableUI2",
    "OpsAutomationAiUI2", "IncidentAiUI2", "IncidentComplianceUI2",
    "AuditReplayUI2", "AutopilotCommandCenterUI2", "AutopilotExplainUI2",
    "AutopilotOptionsUI2", "AutopilotPlaybookUI2",
    "JobQueueV2UI2", "RetentionPolicyUI2", "KriScoringUI2",
    "BrokerScoringUI2", "RiskAdjExecUI2", "PortfolioOptimizerUI2",
]

page_tasks = []
for pg in pages:
    page_tasks.append(f"{pg}: convert all className strings to inline CSSProperties")
    page_tasks.append(f"{pg}: apply Bloomberg amber (#f5a623) accent to headers/buttons")
    page_tasks.append(f"{pg}: use monospace font for all numerical data displays")
    page_tasks.append(f"{pg}: add amber 2px top border to all panels")
    page_tasks.append(f"{pg}: ensure dark bg (#0a0a0a) and panel bg (#111111)")
    page_tasks.append(f"{pg}: add loading skeleton state for data fetch")
    page_tasks.append(f"{pg}: add error boundary with recovery UI")
    page_tasks.append(f"{pg}: add keyboard navigation for all interactive elements")
    page_tasks.append(f"{pg}: verify no demo/mock data — real API only")
    page_tasks.append(f"{pg}: add proper aria labels for accessibility")

sections["PER-PAGE BLOOMBERG STYLING (175 PAGES × 10 TASKS)"] = page_tasks

# Write file
outpath = os.path.join(os.path.dirname(os.path.abspath(__file__)), "tasks.md")
with open(outpath, "w", encoding="utf-8") as f:
    f.write("# APEX TERMINAL — MASTER TASK LIST\n")
    f.write("# Bloomberg Terminal + TradingView Complete Feature Parity\n")
    f.write(f"# Generated: 2026-02-27\n")
    f.write("# Status: [ ] = pending, [x] = done, [-] = in-progress\n\n")

    task_num = 0
    for section, tasks in sections.items():
        f.write(f"\n## {section}\n\n")
        for task in tasks:
            task_num += 1
            f.write(f"- [ ] TASK-{task_num:05d}: {task}\n")

    f.write(f"\n\n---\n## TOTAL TASKS: {task_num}\n")

print(f"Total tasks generated: {task_num}")
print(f"Written to: {outpath}")
