"""Year 2 weeks 53-104 — injected into WEEKS dict by gen_expanded_plan.py"""

def register(WEEKS):
    # ── Y2 Q1: AI Agent Evolution & Advanced Intelligence ──
    WEEKS[53] = dict(
        title="Autonomous AI Agent Architecture (LangChain)",
        subtitle="Refactor the autopilot into a true autonomous AI agent using LangChain with tool-use and memory.",
        kpis=[("Framework","LangChain"),("Tools","12 agent tools"),("Memory","Conversation buffer"),("Plans","Dynamic")],
        goals=["LangChain agent replaces hardcoded scan→rank→validate→execute pipeline",
               "12 tools the agent can call: scan_universe, rank_candidates, validate_trade, execute_order, check_positions, etc.",
               "Agent memory: ConversationBufferWindowMemory with 20-message window",
               "Dynamic planning: agent decides in what order to call tools based on market context",
               "Explain agent reasoning: every tool call logged with agent's rationale",
               "Fallback: if agent hangs or loops, revert to deterministic pipeline"],
        tasks=["pip install langchain langchain-groq langchain-google-genai",
               "Create services/autopilot/agent.py: ApexAgent class with 12 tools",
               "Wrap each service function as a LangChain Tool with name + description",
               "AgentExecutor with verbose=True for full reasoning trace",
               "Store agent reasoning log in run_artifact.agent_trace JSON field",
               "Fallback handler: if agent_timeout > 120s, run deterministic pipeline"],
        deliverables=["LangChain agent completes full cycle in dry_run mode",
                      "Agent trace shows reasoning for each tool call",
                      "Fallback activates correctly after 120s timeout",
                      "Agent uses >8 different tools in a single cycle"],
        autopilot=["The agent is now the autopilot — it decides its own workflow",
                   "Dynamic strategies: on high-VIX days, agent may call check_risk first before scanning",
                   "Agent memory means it remembers this morning's briefing when making afternoon decisions"],
        risk=["Risk: Agent loops or halts → strict max_iterations=25; hard timeout at 120s",
              "Risk: Agent calls execute without validate → tool descriptions must state 'always validate first'"],
        code=["tools = [",
              "  Tool('scan_universe', scan_universe, 'Scan market for option trade candidates. Input: date.'),",
              "  Tool('validate_trade', validate_trade, 'Validate a candidate against all risk gates. Must call before execute.'),",
              "  Tool('execute_order', execute_order, 'Execute validated trade. Only call after validate_trade passes.'),",
              "]",
              "agent = create_react_agent(llm=groq_llm, tools=tools, prompt=AGENT_PROMPT)"],
        days=["Mon: LangChain integration; 12 tool wrappers","Tue: AgentExecutor + verbose trace",
              "Wed: Memory integration","Thu: Agent reasoning log in RunArtifact","Fri: Fallback; E2E dry-run"],
    )

    WEEKS[54] = dict(
        title="Multi-Agent System: Researcher + Validator + Executor Agents",
        subtitle="Split the single agent into specialized sub-agents that collaborate on trade decisions.",
        kpis=[("Sub-agents","3 specialized"),("Coordination","Supervisor"),("Isolation","Yes"),("Debate","50ms max")],
        goals=["ResearcherAgent: scans universe, builds candidate list, adds context",
               "ValidatorAgent: devils-advocate — argues against each trade; seeks to reject",
               "ExecutorAgent: final decision maker after hearing both sides",
               "SupervisorAgent: routes messages between sub-agents based on state",
               "Agent debate protocol: Researcher proposes → Validator challenges → Executor decides",
               "Full debate transcript saved in run artifact for human review"],
        tasks=["Create agent_researcher.py, agent_validator.py, agent_executor.py",
               "agent_supervisor.py: StateGraph with LangGraph or custom message router",
               "Each agent has different system prompt + different tools",
               "Validator agent given explicit instructions to find flaws, not be optimistic",
               "Executor reads debate transcript + weighs both sides before final order",
               "Debate saved to run_artifact.debate_transcript"],
        deliverables=["3-agent pipeline completes full cycle in dry_run",
                      "Validator correctly argues against at least 1 candidate",
                      "Executor sometimes overrules validator with reasoning",
                      "Debate transcript saved and readable"],
        autopilot=["Multi-agent = adversarial self-review = fewer bad trades",
                   "Validator agent effectively acts as the risk manager challenging every trade",
                   "Debate reveals LLM reasoning conflicts — invaluable for audit and improvement"],
        risk=["Risk: Multi-agent slower than single agent → parallelize Researcher + Validator; Executor last",
              "Risk: Agents disagree on every trade → tune Validator to focus on material risks only"],
        code=["graph = StateGraph(AgentState)",
              "graph.add_node('researcher', researcher_agent)",
              "graph.add_node('validator', validator_agent)",
              "graph.add_node('executor', executor_agent)",
              "graph.add_edge('researcher', 'validator')",
              "graph.add_conditional_edges('validator', route_to_executor)"],
        days=["Mon: ResearcherAgent with scan+rank tools","Tue: ValidatorAgent adversarial prompt",
              "Wed: ExecutorAgent decision framework","Thu: Supervisor/StateGraph routing",
              "Fri: Debate transcript in RunArtifact; E2E test"],
    )

    WEEKS[55] = dict(
        title="RAG-Powered Market Knowledge Base",
        subtitle="Build a vector knowledge base from financial documents for Retrieval-Augmented Generation.",
        kpis=[("Documents","500+ filings"),("Vector DB","ChromaDB"),("Retrieval","Top-5 chunks"),("Latency","<500ms")],
        goals=["Ingest 500+ documents: 10-K/10-Q filings, earnings transcripts, research reports, Fed minutes",
               "Chunk and embed documents with OpenAI/Groq embeddings → store in ChromaDB",
               "RAG query: agent asks knowledge base for company/market context before trading",
               "Hybrid retrieval: keyword match + semantic similarity for best results",
               "Knowledge base updated weekly with new filings",
               "RAG context shown in agent reasoning trace"],
        tasks=["pip install chromadb langchain-community","Build doc ingestion pipeline: fetch → chunk → embed → store",
               "Chunk strategy: 512 tokens with 50-token overlap",
               "KnowledgeBase.query(question, top_k=5) → relevant chunks",
               "Wire into ResearcherAgent: query KB for each symbol before scoring",
               "Weekly refresh: new 10-Q filings + earnings transcripts → re-index"],
        deliverables=["500+ documents indexed in ChromaDB","KB query returns relevant chunks for AAPL test",
                      "RAG context visible in agent trace","Weekly refresh job running"],
        autopilot=["RAG gives the agent memory of company history — not just current data",
                   "Agent can ask: 'What did AAPL management say about margins last earnings?'",
                   "RAG context improves LLM analysis quality significantly vs raw data"],
        risk=["Risk: ChromaDB persistence → use persistent client with volume mount in Docker",
              "Risk: Embedding cost too high → use sentence-transformers (local, free) for embeddings"],
        code=["from chromadb import PersistentClient",
              "chroma = PersistentClient(path='./chroma_db')",
              "collection = chroma.get_or_create_collection('apex_knowledge')",
              "",
              "def ingest_document(doc_id, text, metadata):",
              "    chunks = chunk(text, size=512, overlap=50)",
              "    collection.add(ids=[f'{doc_id}_{i}' for i in range(len(chunks))],",
              "                   documents=chunks, metadatas=[metadata]*len(chunks))"],
        days=["Mon: ChromaDB setup; doc ingestion pipeline","Tue: Embedding + indexing 500 docs",
              "Wed: Hybrid retrieval query","Thu: Wire into ResearcherAgent","Fri: Weekly refresh job"],
    )

    WEEKS[56] = dict(
        title="Real-Time News Arbitrage & Event-Driven Alpha",
        subtitle="Sub-second news processing to detect and act on market-moving events before price moves fully.",
        kpis=[("Latency","<2s detection"),("Sources","6 news feeds"),("Classification","ML-based"),("Alpha","Event-driven")],
        goals=["6 news feeds in real-time: Bloomberg RSS, Reuters, SEC EDGAR, Twitter, Reddit, Benzinga",
               "ML event classifier: categorize news as: Earnings Beat/Miss, M&A, FDA, Legal, Macro",
               "Estimate price impact: + or - delta based on news category and historical impact",
               "Trade signal: if large positive event detected for non-held symbol → evaluate immediate scan",
               "Trade signal: if negative event for held symbol → trigger emergency exit evaluation",
               "News arbitrage window: typically 30-90s after release before market fully adjusts"],
        tasks=["newsfeeds.py: async feed readers for 6 sources with dedup (URL hash)",
               "event_classifier.py: fine-tuned FinBERT for 8 event categories",
               "price_impact_estimator.py: regression model from historical news events",
               "Trigger reactive scan: POST /api/v1/autopilot/scan?trigger=news&symbol=AAPL",
               "Emergency exit: if negative_impact > 0.15 → evaluate position for immediate close",
               "News latency tracking: measure detection time vs first price tick after news"],
        deliverables=["6 news feeds ingesting in real-time","Event classifier correctly labels 8 types (tested)",
                      "Emergency exit triggered by test negative event","Latency < 2s from publication"],
        autopilot=["News arbitrage is the advanced alpha layer — acts faster than human can react",
                   "Emergency exit is a safety feature first — protect capital before chasing alpha",
                   "News detection logs: every article that was evaluated and its classification"],
        risk=["Risk: False positives (satire, corrections) → require 2+ source confirmation for large trades",
              "Risk: Acting on stale news (reposted old articles) → enforce 5-min freshness filter"],
        code=["async def process_article(article):",
              "    event_type = classifier.predict(article.text)",
              "    impact = estimator.predict(event_type, article.symbol)",
              "    if abs(impact) > 0.05:  # >5% expected move",
              "        await alert_engine.fire('NEWS_EVENT',",
              "                               {'symbol': article.symbol, 'impact': impact, 'event': event_type})"],
        days=["Mon: 6 news feed readers with dedup","Tue: FinBERT event classifier fine-tuning",
              "Wed: Price impact estimator","Thu: Reactive scan trigger","Fri: Emergency exit + latency tracking"],
    )

    WEEKS[57] = dict(
        title="Options Flow Intelligence & Dark Pool Analytics",
        subtitle="Detect institutional money movement via unusual options flow and dark pool prints before price moves.",
        kpis=[("Flow Sources","3"),("Unusual Threshold","5× avg OI"),("Dark Pool","Block prints"),("Signal","Pre-move"]],
        goals=["Unusual options activity: flag when volume > 5× average open interest for a strike",
               "Dark pool print detector: large block trades (>10,000 shares) before regular hours",
               "Sweep detector: options bought aggressively at ask across multiple strikes (strong directional bet)",
               "Flow intelligence score: 0-100 based on flow conviction (size, direction, proximity to expiry)",
               "Alert when flow aligns with proposed autopilot trade (confirmation signal)",
               "Alert when flow contradicts proposed trade (potential fade signal)"],
        tasks=["options_flow.py: connect to Unusual Whales API or Tradier screener",
               "unusual_activity_detector(): compare volume vs 30-day avg OI per strike",
               "sweep_detector(): identify aggressive multi-strike buying pattern",
               "darkpool.py: Quandl NASD dark pool data or inferred from TAQ data",
               "FlowScore: weighted composite of size, direction, proximity, sweep_flag",
               "GET /api/v1/flow/{symbol} → flow events for today"],
        deliverables=["Unusual activity detected for test case (>5× OI)",
                      "Sweep correctly identified for test multi-strike sequence",
                      "Flow score computed for 20 symbols","FlowView.tsx shows daily flow events"],
        autopilot=["Flow alignment: if flow + autopilot agree → add 10 bonus to entry score",
                   "Flow contradiction: if strong opposite flow → skip trade regardless of other signals",
                   "Dark pool prints before autopilot open = institutional validation"],
        risk=["Risk: Unusual Whales API expensive → use Tradier flow data as free tier fallback",
              "Risk: Flow data lagged 15 minutes → only use for context, never as sole signal"],
        code=["def is_unusual_activity(symbol, strike, volume, oi_avg):",
              "    ratio = volume / max(oi_avg, 1)",
              "    return ratio > 5.0, ratio  # True if unusual, with magnitude"],
        days=["Mon: Options flow API integration","Tue: Unusual activity detector",
              "Wed: Sweep detector","Thu: Dark pool prints","Fri: FlowView; score integration"],
    )

    WEEKS[58] = dict(
        title="Advanced LLM Fine-Tuning on Own Trade History",
        subtitle="Fine-tune a small LLM on Apex Terminal's own trade history to create a personalized trading model.",
        kpis=[("Dataset","500+ trades"),("Base Model","Llama3-8B"),("Fine-tune","LoRA PEFT"),("Eval","Win rate lift")],
        goals=["Build fine-tuning dataset from 500+ paper trades: features + outcomes + LLM decision",
               "Create instruction-tuning pairs: 'Given this setup, the trade should/should not be taken because...'",
               "Fine-tune Llama3-8B with LoRA adapters via Hugging Face PEFT",
               "Evaluate fine-tuned model vs base Groq on held-out test trades",
               "Deploy fine-tuned model as a 3rd LLM validation layer",
               "Retrain monthly as more trade data accumulates"],
        tasks=["pip install transformers peft datasets accelerate","Build dataset generator from DB trade history",
               "Format as instruction pairs: {instruction, input, output}",
               "finetune.py: LoRA config + Trainer + evaluate on test set",
               "Export LoRA adapter → load at inference alongside base model",
               "fine_tuned_ranker.py: wraps inference for use as 3rd LLM layer"],
        deliverables=["500-trade dataset generated from DB","LoRA fine-tuning completes without OOM error",
                      "Fine-tuned model achieves better win rate prediction vs base model on test set",
                      "3rd LLM layer integrated into pipeline"],
        autopilot=["Fine-tuned model learns YOUR specific trading style and market preferences",
                   "Monthly retraining: model improves as more trades accumulate",
                   "3rd LLM layer: Groq + Gemini + Fine-tuned = consensus from 3 independent judges"],
        risk=["Risk: 500 trades too small for fine-tuning → use data augmentation; mix with synthetic examples",
              "Risk: Fine-tuned model overfits → evaluate on held-out 20% before deploying"],
        code=["from peft import LoraConfig, get_peft_model",
              "lora_config = LoraConfig(r=16, lora_alpha=32, target_modules=['q_proj','v_proj'])",
              "model = get_peft_model(base_model, lora_config)",
              "trainer = Trainer(model=model, args=training_args, train_dataset=train_data)",
              "trainer.train()"],
        days=["Mon: Dataset builder from trade DB","Tue: Instruction pair formatting",
              "Wed: LoRA fine-tuning run","Thu: Evaluation vs base model","Fri: Deploy as 3rd LLM layer"],
    )

    WEEKS[59] = dict(
        title="Regime-Adaptive Strategy Weights via Reinforcement Learning",
        subtitle="Train an RL agent to dynamically adjust strategy allocation weights based on market regime signals.",
        kpis=[("Algorithm","PPO"),("State Space","15 features"),("Action","6 weights"),("Reward","Sharpe improvement")],
        goals=["Define RL environment: state = 15 market features, action = 6 strategy weight allocations",
               "Reward function: Sharpe ratio improvement over previous period",
               "Train PPO agent (Stable Baselines 3) on 5-year historical data",
               "RL agent replaces static regime → allocation mapping from Week 19",
               "Evaluate RL vs static allocation on OOS period",
               "RL agent adjusts weights daily based on updated state observation"],
        tasks=["pip install stable-baselines3 gymnasium","TradingEnv(gymnasium.Env): state, action, reward, step",
               "Historical backtest environment: simulate 5 years of daily regime states",
               "PPO training: 1M steps; evaluate every 50k steps",
               "Export trained policy → rl_allocation_policy.pkl",
               "Wire RLAllocator into AllocationManager; daily weight update job"],
        deliverables=["RL environment runs 5-year episode without error","PPO trains to positive reward",
                      "RL allocation outperforms static on OOS test period","Daily weight updates working"],
        autopilot=["RL agent self-optimizes allocation without human tuning",
                   "RL observes its own mistakes and corrects — true adaptive autopilot",
                   "Weight changes logged daily for transparency: 'RL reduced Iron Condor from 20% to 8% today'"],
        risk=["Risk: RL agent finds pathological allocations → enforce min/max weight bounds per strategy",
              "Risk: RL overfits to training period → use 3-year train / 2-year OOS split minimum"],
        code=["class TradingEnv(gym.Env):",
              "    def step(self, action):  # action = 6 allocation weights",
              "        weights = softmax(action)  # ensure they sum to 1",
              "        pnl = simulate_day(weights, self.state)",
              "        reward = sharpe_increment(pnl)",
              "        self.state = next_state()",
              "        return self.state, reward, done, info"],
        days=["Mon: TradingEnv implementation","Tue: PPO training on historical data",
              "Wed: OOS evaluation vs static allocation","Thu: Policy deployment",
              "Fri: Daily weight update job; weight change logging"],
    )

    WEEKS[60] = dict(
        title="Live Trading Transition: First Real Money Trades",
        subtitle="Go live with real money after clearing the 10-step checklist — starting with minimal 1-contract size.",
        kpis=[("Mode","Live"),("Size","1 contract"),("Budget","$1,000"),("Monitor","24/7")],
        goals=["Clear all 10 go-live checklist items (from Week 35 framework)",
               "Execute first real-money trade: 1 contract, max $500 total risk",
               "monitor every cycle manually for first 2 weeks of live trading",
               "Daily comparison: paper vs live P&L and execution quality",
               "First live week debrief: document all surprises vs paper trading",
               "Gradual scale-up plan: 1 → 2 → 5 contracts over 8 weeks pending results"],
        tasks=["Complete 10-item go-live checklist; document each item's status",
               "Switch broker config to live (Alpaca live account) with real funds",
               "Set hard limits: max_daily_loss=$200, max_position_size=1 contract",
               "First trade: put credit spread on high-IV liquid ETF (SPY, QQQ, IWM)",
               "Daily live vs paper comparison spreadsheet or DB query",
               "Week 1 debrief document: lessons from first live trades"],
        deliverables=["Go-live checklist 100% complete","First real trade executed and confirmed filled",
                      "Daily comparison report running","Week 1 debrief document written"],
        autopilot=["Live trading is the ultimate validation of 60 weeks of work",
                   "1 contract = minimal risk; learning about live vs paper differences is the goal",
                   "Every live trade: capture slippage, fill quality, timing vs paper equivalent"],
        risk=["Risk: First trade fills at bad price → review order type (limit mid price only)",
              "Risk: Panic and override autopilot on first loss → commit to letting it run for 10 trades minimum"],
        code=["# live config",
              "BROKER_MODE = 'live'",
              "MAX_POSITION_CONTRACTS = 1",
              "MAX_DAILY_LOSS_USD = 200",
              "# kill switch is active at all times during live trading"],
        days=["Mon: Complete go-live checklist; switch to live mode",
              "Tue: First live trade; monitor fill quality","Wed: Second and third trades",
              "Thu: Live vs paper comparison analysis","Fri: Week 1 debrief document"],
    )

    # ── Y2 Q2: Scaling & Robustness ──
    WEEKS[61] = dict(
        title="Scale-Up to 5 Contracts & Position Sizing Refinement",
        subtitle="Scale live trading to 5 contracts with Kelly-based sizing validated on 2 weeks of live data.",
        kpis=[("Max Size","5 contracts"),("Kelly","Live-calibrated"),("Risk","<$2,000/day")],
        goals=["Increase max_position_contracts from 1 to 5 after 2 weeks of clean live trading",
               "Recalibrate Kelly parameters using live trade win rate and P&L data",
               "Upgrade daily loss limit: $200 → $500 (proportional to larger size)",
               "Volume discount: reduce per-contract cost with larger fills",
               "Track slippage: live fill quality vs theoretical mid price"],
        tasks=["Update config: MAX_POSITION_CONTRACTS=5, MAX_DAILY_LOSS=500",
               "Kelly recalibration: re-run kelly_calculator with live trade data",
               "Slippage tracker: record (expected_mid - actual_fill) per trade",
               "Volume analysis: check if larger orders get worse fills",
               "Update monitoring thresholds for 5-contract risk"],
        deliverables=["5-contract live trades executing","Kelly recalibrated on live data",
                      "Slippage per trade computed and improving"],
        autopilot=["Scale-up is gated on clean execution — no incidents in first 2 weeks",
                   "Kelly recalibration makes sizing data-driven from real fills"],
        risk=["Risk: 5 contracts get worse fills than 1 → test with 2 then 3 first",
              "Risk: Overconfidence → keep daily loss limit strict"],
        code=["# Live Kelly recalibration",
              "live_trades = db.get_live_trades(last_n=50)",
              "win_rate = len([t for t in live_trades if t.pnl>0]) / len(live_trades)",
              "avg_win = mean([t.pnl for t in live_trades if t.pnl>0])",
              "avg_loss = abs(mean([t.pnl for t in live_trades if t.pnl<0]))",
              "kelly = fractional_kelly(win_rate, avg_win, avg_loss)"],
        days=["Mon: Update config; first 5-contract trade","Tue: Kelly recalibration",
              "Wed: Slippage tracking","Thu: Volume + fill quality analysis","Fri: Updated monitoring"],
    )

    WEEKS[62] = dict(
        title="Multi-Broker Integration: TD Ameritrade / Schwab",
        subtitle="Add TD Ameritrade/Schwab as second broker for redundancy and commission comparison.",
        kpis=[("Brokers","2 active"),("Failover","Automatic"),("Compare","Commission + fill")],
        goals=["Integrate TD Ameritrade/Schwab API via tda-api library",
               "Broker failover: if primary broker fails, auto-route to secondary",
               "Commission comparison: track per-trade commission for each broker",
               "Best-execution logic: route to broker with better current fill quality",
               "Dual broker monitoring: health check both brokers pre-market"],
        tasks=["pip install tda-api (or schwab-py)","Create schwab_broker.py implementing BrokerInterface",
               "BrokerRouter: selects broker based on availability + estimated fill quality",
               "commission_tracker.py: per-trade commission logging",
               "Failover test: simulate primary broker outage → confirm secondary activates"],
        deliverables=["Schwab/TDA broker connected and placing paper orders",
                      "Automatic failover working on outage test","Commission comparison report"],
        autopilot=["Dual broker = zero single-point-of-failure for execution",
                   "Best-execution routing moves toward lower-cost broker over time"],
        risk=["Risk: TDA API deprecation (moving to Schwab) → use schwab-py for future-proof integration"],
        code=["class BrokerRouter:",
              "    def execute(self, order):",
              "        if self.primary.is_healthy(): return self.primary.execute(order)",
              "        return self.secondary.execute(order)  # automatic failover"],
        days=["Mon: Schwab API setup + auth","Tue: schwab_broker.py implementation",
              "Wed: BrokerRouter with failover","Thu: Commission tracker","Fri: Failover E2E test"],
    )

    WEEKS[63] = dict(
        title="Futures & Index Hedging Integration",
        subtitle="Add E-mini futures and VIX derivatives for portfolio hedging during high-risk periods.",
        kpis=[("Instruments","ES, NQ, VIX"),("Hedge","Delta-neutral"),("Cost","Tracked")],
        goals=["Integrate CME E-mini S&P 500 (ES) futures via Interactive Brokers API",
               "Portfolio delta hedge: if portfolio delta drifts beyond ±0.25, hedge with ES mini",
               "VIX call hedge: buy VIX calls as portfolio insurance when VIX < 18",
               "Hedge sizing: calculate exact hedge ratio from portfolio delta",
               "Hedge P&L tracked separately from options P&L",
               "Auto-hedge job: checks delta balance every 30 minutes during market hours"],
        tasks=["pip install ib_insync (Interactive Brokers API)","ib_broker.py: ES futures execution",
               "delta_hedger.py: portfolio_delta → required ES contracts to neutralize",
               "vix_hedge.py: buy OTM VIX calls when VIX < 18",
               "HedgeView.tsx: show active hedges, hedge P&L, delta before/after"],
        deliverables=["ES mini orders placing on IB paper","Delta hedge computation correct",
                      "Auto-hedge job running every 30 minutes","HedgeView shows hedge positions"],
        autopilot=["Hedging makes portfolio delta-neutral — removes market directional risk",
                   "VIX insurance: cheap when calm, pays off in crashes",
                   "Hedge P&L is a cost of doing business — not expected to profit, only protect"],
        risk=["Risk: Futures margin requirements → verify account has sufficient margin before hedging",
              "Risk: Over-hedging (negative delta) → strict delta target range ±0.10"],
        code=["def compute_hedge_qty(portfolio_delta, es_delta_per_contract=50):",
              "    return -round(portfolio_delta / es_delta_per_contract)  # negative to neutralize"],
        days=["Mon: IB API setup; ES paper trading","Tue: Delta hedger calculation",
              "Wed: VIX hedge logic","Thu: Auto-hedge 30min job","Fri: HedgeView + P&L tracking"],
    )

    WEEKS[64] = dict(
        title="Portfolio Rebalancing Engine & Capital Efficiency",
        subtitle="Automated portfolio rebalancing to maintain optimal allocation, maximize capital efficiency.",
        kpis=[("Rebalance","Weekly"),("Idle Capital","<10%"),("Margin Use","<70%"),("Turnover","Minimize")],
        goals=["Weekly rebalancing: assess allocation drift; rebalance toward target weights",
               "Capital efficiency: no more than 10% idle at any time — deploy or earn yield",
               "Margin utilization: keep margin use 50-70% — not too conservative, not too aggressive",
               "Minimize turnover: prefer rolling over closing-and-reopening (lower transaction cost)",
               "Cash yield: uninvested cash → T-bills or money market via broker sweep"],
        tasks=["rebalancer.py: compute current vs target allocation; generate rebalance orders",
               "capital_efficiency(): total_deployed / total_portfolio × 100",
               "margin_monitor(): current margin use vs limit",
               "cash_sweep_manager(): interface with broker cash management",
               "RebalanceView.tsx: current vs target allocation side-by-side with action plan"],
        deliverables=["Rebalancer produces correct action plan for test portfolio drift",
                      "Capital efficiency metric computed","Margin monitor alerts at 70%",
                      "RebalanceView shows weekly rebalance plan"],
        autopilot=["Rebalancing ensures autopilot maintains intended risk profile over time",
                   "Capital efficiency removes idle drag — every dollar working",
                   "Margin monitoring prevents over-extension on volatile days"],
        risk=["Risk: Rebalance trades too frequent (high turnover) → execute only if drift > 5%",
              "Risk: Cash sweep may miss T-bill yield → integrate and verify broker supports it"],
        code=["def rebalance_plan(current_weights, target_weights, tolerance=0.05):",
              "    return {s: target_weights[s]-current_weights[s]",
              "           for s in target_weights",
              "           if abs(target_weights[s]-current_weights.get(s,0)) > tolerance}"],
        days=["Mon: Rebalancer core algorithm","Tue: Capital efficiency + margin monitor",
              "Wed: Cash sweep integration","Thu: RebalanceView.tsx","Fri: Weekly scheduler + E2E test"],
    )

    # ── Y2 Q3: Institutional Features ──
    WEEKS[65] = dict(
        title="Institutional-Grade Reporting & FINRA Compliance",
        subtitle="Build institutional reporting suite: 13F-style transparency, broker reconciliation, and FINRA-ready logs.",
        kpis=[("Report Types","8"),("Reconciliation","Daily"),("Format","Regulatory"),("Retention","7 years")],
        goals=["13F-style position report: all holdings at quarter end with market values",
               "Daily broker reconciliation: compare internal DB positions vs broker actual positions",
               "Trade confirmation reports: PDF confirms for each trade matching broker confirms",
               "FINRA-style order audit trail: full lifecycle of every order",
               "Performance tearsheet: monthly PDF matching professional fund reporting standards",
               "7-year record retention with tamper-proof archiving"],
        tasks=["position_report.py: 13F-format quarterly report","reconciliation.py: compare DB vs broker",
               "trade_confirm.py: PDF trade confirmations","tearsheet.py: monthly performance PDF",
               "archive_manager.py: 7-year cold storage rotation","GET /api/v1/compliance/reports"],
        deliverables=["13F position report generates correctly","Daily reconciliation runs; discrepancies flagged",
                      "Trade confirmations match broker's","Tearsheet matches professional fund format"],
        autopilot=["Reconciliation catches any DB/broker mismatch before it becomes a problem",
                   "Institutional reporting shows autopilot is operating at professional standard"],
        risk=["Risk: Reconciliation mismatch on partial fills → use fill-level reconciliation, not position-level"],
        code=["def reconcile(db_positions, broker_positions):",
              "    for sym in set(db_positions) | set(broker_positions):",
              "        db_qty = db_positions.get(sym,0)",
              "        bk_qty = broker_positions.get(sym,0)",
              "        if db_qty != bk_qty: alert('RECONCILE_MISMATCH', sym, db_qty, bk_qty)"],
        days=["Mon: 13F report + tearsheet","Tue: Daily reconciliation","Wed: Trade confirmations",
              "Thu: 7-year archive manager","Fri: Compliance report API; E2E test"],
    )

    # Weeks 66-78 condensed but detailed
    for wk, (title, subtitle, theme) in enumerate([
        (66, "Tax Lot Accounting & Wash Sale Compliance", "Track lots, gains, holding periods, and wash sale rules automatically.", "tax"),
        (67, "Crypto Correlation Signal Integration", "Monitor BTC/ETH as risk-off signals affecting equity options strategy.", "crypto"),
        (68, "Macro Economic Indicator Dashboard", "Build a macro dashboard: CPI, jobs, Fed rate signals integrated into regime detection.", "macro"),
        (69, "Options IV Skew Trading Strategies", "Build dedicated IV skew arbitrage strategies: buy cheap wing, sell expensive ATM.", "iv_skew"),
        (70, "Live Earnings Play Strategies", "Trade IV crush around earnings: structured plays 5 days before and 1 day after.", "earnings"),
        (71, "Portfolio Insurance & Tail Risk Hedging", "Systematic tail hedging: OTM puts, VIX calls, correlation trades for crash protection.", "tail_hedge"),
        (72, "AI Agent Self-Evaluation & Improvement Loop", "Agent evaluates its own performance weekly, proposes and implements parameter improvements.", "self_eval"),
        (73, "Multi-Timeframe Regime Analysis", "Align short/medium/long-term regime signals for higher-conviction entries.", "multi_regime"),
        (74, "Client Reporting API & Partner Integration", "Build RESTful API for third-party portfolio managers to access performance data.", "api"),
        (75, "Advanced Backtesting: Out-of-Sample Stress Periods", "Deep-dive backtesting in 5 historical stress periods with real tick data.", "stress_bt"),
        (76, "Volatility Forecasting with GARCH Models", "Train GARCH(1,1) to forecast next-day IV; use forecast in position sizing.", "garch"),
        (77, "Options Market Making Simulation", "Simulate basic market making: quote both bid and ask; earn spread as revenue stream.", "mm"),
        (78, "Q3 Performance Review & Y2H2 Planning", "Mid-year review of live trading results and planning for the final 26 weeks.", "review"),
    ], start=66):
        WEEKS[wk] = dict(
            title=title,
            subtitle=subtitle,
            kpis=[("Theme", theme.replace("_"," ").title()), ("Status", "Y2 Advanced"), ("Priority","High"), ("Type","Production")],
            goals=[f"Implement {title.lower()} as a production-grade feature",
                   "Integrate with existing autopilot pipeline",
                   "Add tests for new functionality",
                   "Document in user guide and runbook"],
            tasks=[f"Design {theme} architecture",
                   f"Implement {theme} service module",
                   f"Build {theme} API endpoints",
                   f"Build {theme} frontend component",
                   f"Write {theme} tests + documentation"],
            deliverables=[f"{title} working end-to-end",
                          "Tests passing in CI",
                          "Documented in user guide"],
            autopilot=[f"{title} enhances autopilot decision quality",
                       "Results tracked in RunArtifact and weekly reports"],
            risk=[f"Risk: Integration complexity → build as standalone service first; integrate after unit tests pass"],
            code=[f"# {title} core logic", f"class {theme.title().replace('_','')}Service:", "    pass  # see service module"],
            days=["Mon: Design + architecture","Tue: Core implementation","Wed: API endpoints",
                  "Thu: Frontend component","Fri: Tests + documentation"],
        )

    # ── Y2 Q4: Completion & Ecosystem ──
    WEEKS[79] = dict(
        title="Mobile App: React Native Dashboard",
        subtitle="Build React Native mobile app with real-time P&L, push notifications, and quick trade actions.",
        kpis=[("Platform","iOS+Android"),("Features","Alerts+P&L+Kill"),("Push","FCM+APNs"),("Size","<30MB")],
        goals=["React Native app: real-time P&L, positions list, alerts feed, kill switch button",
               "Push notifications: every trade execution, alert trigger, daily briefing",
               "Biometric auth for kill switch activation",
               "Offline mode: show cached last-known positions when no connection",
               "Dark terminal theme matching desktop dashboard"],
        tasks=["npx react-native init ApexMobile","Connect to FastAPI backend via auth JWT",
               "WebSocket client for live P&L push","FCM + APNs push notification setup",
               "Biometric (TouchID/FaceID) for kill switch","TestFlight + Google Play internal beta"],
        deliverables=["App builds for iOS and Android","Real-time P&L updating via WebSocket",
                      "Push notification fires on test trade","kill switch accessible from mobile"],
        autopilot=["Mobile app = always-on monitoring even away from desk",
                   "Kill switch on mobile is the ultimate safety feature",
                   "Push notification every trade = complete awareness of autopilot activity"],
        risk=["Risk: WebSocket battery drain on mobile → background refresh API polling when inactive",
              "Risk: App store approval delay → use TestFlight for internal testing first"],
        code=["// Kill switch with biometric",
              "const killSwitch = async () => {",
              "  const auth = await LocalAuthentication.authenticateAsync({promptMessage:'Confirm kill'});",
              "  if (auth.success) await api.post('/autopilot/kill');",
              "}"],
        days=["Mon: RN project setup; auth JWT","Tue: P&L + positions screens",
              "Wed: WebSocket live updates","Thu: Push notifications","Fri: Biometric kill switch; TestFlight"],
    )

    WEEKS[80] = dict(
        title="Web3 Integration & On-Chain Portfolio Transparency",
        subtitle="Publish trade hashes on-chain for immutable audit trail and explore DeFi options protocols.",
        kpis=[("Chain","Polygon/Base"),("Hashes","Per-trade"),("Gas","<$0.01"),("DeFi","Research")],
        goals=["Publish SHA-256 hash of each trade decision to Polygon for immutable record",
               "Build verification endpoint: given trade_id, verify on-chain hash matches DB record",
               "Explore Lyra (DeFi options protocol) for on-chain hedging opportunities",
               "On-chain portfolio attestation: quarterly proof-of-portfolio publication",
               "Research: cross-margin between CeFi and DeFi options positions"],
        tasks=["pip install web3","blockchain.py: publish_trade_hash(trade_id, hash) → tx_hash",
               "Polygon Mumbai testnet → mainnet after testing","verify_trade(trade_id) → compare DB vs chain",
               "Lyra protocol research: read whitepaper; test paper trading on testnet",
               "GET /api/v1/compliance/chain-verify/{trade_id}"],
        deliverables=["Trade hash published on Polygon for test trade","Verification endpoint works",
                      "Lyra research document written","Gas cost tracked at $0.01 per hash"],
        autopilot=["On-chain hashes make autopilot 100% tamper-proof — blockchain is the ultimate audit",
                   "DeFi options research opens new alpha streams for Year 3",
                   "Quarterly attestation makes performance claims verifiable by anyone"],
        risk=["Risk: Gas spikes → only publish hourly batch hash (not per-trade) to control cost",
              "Risk: Lyra liquidity thin → DeFi options for research only; no production trading yet"],
        code=["from web3 import Web3",
              "w3 = Web3(Web3.HTTPProvider(POLYGON_RPC))",
              "def publish_hash(trade_hash: str) -> str:",
              "    tx = contract.functions.recordHash(trade_hash).build_transaction({'gas':50000})",
              "    signed = w3.eth.account.sign_transaction(tx, private_key)",
              "    return w3.eth.send_raw_transaction(signed.rawTransaction).hex()"],
        days=["Mon: Web3 + Polygon setup","Tue: Trade hash publisher","Wed: Verification endpoint",
              "Thu: Lyra research + testnet","Fri: Quarterly attestation script"],
    )

    for wk, title in enumerate([
        "Quantitative Research Platform & Jupyter Integration",
        "API Marketplace: Sell Data Feeds & Signals",
        "Enterprise Multi-Tenant Architecture",
        "Advanced Portfolio Optimization: Black-Litterman",
        "Regulatory Filing Automation (Form 4, 13F)",
        "AI-Powered Strategy Narrative Generator",
        "Cross-Asset Correlation Engine (Stocks+Bonds+Crypto)",
        "Distributed Computing: Ray for Parallel Backtests",
        "Automated A/B Testing Framework for Strategies",
        "Production Hardening: K8s, Helm, Auto-scaling",
        "Community Features: Strategy Sharing Marketplace",
        "Beta Program & External User Onboarding",
        "Year 2 Final Review & 4-Year Plan Preparation",
        "Public Launch: Open Source Core + Premium Features",
        "Continuous Improvement: Post-Launch v2.1 Roadmap",
    ], start=81):
        WEEKS[wk] = dict(
            title=title,
            subtitle=f"Advanced Year 2 feature: {title.lower()}",
            kpis=[("Status","Y2 Final Phase"),("Priority","Strategic"),("Impact","High")],
            goals=[f"Implement {title} as production feature",
                   "Integrate with core autopilot platform",
                   "Test thoroughly in staging before production",
                   "Document and release with changelog"],
            tasks=[f"Design architecture for {title}",
                   "Implement core functionality",
                   "Build API and frontend",
                   "Write tests",
                   "Document and deploy"],
            deliverables=[f"{title} live in production",
                          "Tests passing in CI",
                          "User documentation updated"],
            autopilot=[f"{title} adds strategic capability to the autopilot ecosystem"],
            risk=["Risk: Complexity underestimated → timebox to 1 week; defer remainder to v2.1"],
            code=[f"# {title}", "# See architect docs for full implementation"],
            days=["Mon-Fri: Implementation, testing, deployment following standard sprint workflow"],
        )

    WEEKS[104] = dict(
        title="Two-Year Completion: System Review, Open Source & Future Roadmap",
        subtitle="Celebrate 2 years of building, review all 104 weeks of progress, open-source the core, and plan Year 3+.",
        kpis=[("Live Trades","2000+ target"),("Sharpe","Target >1.5"),("AUM","$25K+ target"),("Release","v3.0")],
        goals=["Comprehensive 2-year performance attribution: all strategies, all regimes, all systems",
               "Calculate full 2-year live trading P&L: target Sharpe > 1.5, max drawdown < 15%",
               "Open-source the core framework (minus proprietary alpha signals) on GitHub",
               "Write and publish the definitive technical article: 'Building an Autonomous Options Autopilot'",
               "Year 3-4 roadmap: hedge fund structure, investor capital, full institutional suite",
               "Tag v3.0; celebrate the milestone"],
        tasks=["Run comprehensive_2year_review.py: full attribution analysis",
               "2-year report PDF: performance, decisions, improvements made",
               "Open-source preparation: clean up private signals; write contribution guide",
               "Publish technical article on Substack / Medium / HN",
               "Year 3 Roadmap: investor deck format with track record",
               "git tag v3.0; GitHub release with full changelog"],
        deliverables=["2-year performance report PDF",
                      "Open-source repository live on GitHub with stars",
                      "Technical article published and shared",
                      "Year 3-4 roadmap document",
                      "v3.0 tagged on GitHub"],
        autopilot=["Two years of continuous autonomous operation — the autopilot has proven itself",
                   "Track record establishes credibility for Year 3 institutional conversations",
                   "Open-source core: give back to the community that provided the tools"],
        risk=["Risk: 2-year results below target → honest retrospective; document what to change",
              "Risk: Open-source exposes proprietary alpha → carefully audit what to keep private"],
        code=["# 2-Year performance summary query",
              "SELECT EXTRACT(year FROM created_at) as yr,",
              "       COUNT(*) trades, AVG(CASE WHEN pnl>0 THEN 1.0 ELSE 0 END) win_rate,",
              "       SUM(pnl) total_pnl, MAX(drawdown) max_dd",
              "FROM trades GROUP BY yr ORDER BY yr",
              "-- Target: win_rate>0.60, max_dd<15%, total_pnl>0 both years"],
        days=["Mon: 2-year analysis scripts; performance report PDF",
              "Tue: Open-source preparation; contribution guide",
              "Wed: Technical article draft + publish",
              "Thu: Year 3 roadmap; v3.0 release notes",
              "Fri: Tag v3.0; celebrate; share publicly"],
    )
