"""Year 1 Q4 weeks 40-52 — injected into WEEKS dict by gen_expanded_plan.py"""

def register(WEEKS):
    WEEKS[40] = dict(
        title="Portfolio Heat Map & Sector Dashboard",
        subtitle="Build visual portfolio heat map and sector breakdown for instant risk visualization.",
        kpis=[("Tiles","All positions"),("Color","P&L-based"),("Sector","GICS 11"),("Refresh","30s")],
        goals=["Portfolio heat map: tiles sized by notional, colored by unrealized P&L",
               "Sector donut chart: % of portfolio per GICS sector, live-updated",
               "Position table: sortable by P&L, DTE, strategy, sector",
               "Quick filters: options-only, positive-P&L-only views",
               "CSV export of positions table for tax/reporting",
               "Watchlist panel: 20 symbols with price alerts"],
        tasks=["HeatMapTile.tsx: CSS grid with variable-size, color-coded tiles",
               "SectorDonut.tsx: recharts pie chart with GICS colors",
               "PositionsTable.tsx: sortable columns, filter dropdown",
               "GET /api/v1/positions/export?format=csv",
               "WatchlistPanel.tsx: manage 20-symbol watchlist"],
        deliverables=["Heat map renders all positions with correct sizing + color",
                      "Sector donut updates after each trade",
                      "Position table filterable and sortable",
                      "CSV export downloads correctly"],
        autopilot=["Red heat-map tiles = candidates for autopilot closing step",
                   "Sector donut auto-balances new trade selection toward under-represented sectors",
                   "Watchlist symbols pre-screened in every scan cycle"],
        risk=["Risk: Heat map slow with many tiles → GPU-accelerated CSS transforms only"],
        code=["const HeatMapTile = ({pos}) => (",
              "  <div style={{width: pos.notional/1000+'px',",
              "               background: pnlToColor(pos.unrealizedPnl)}}>",
              "    {pos.symbol} | {pos.unrealizedPnl.toFixed(0)}</div>)"],
        days=["Mon: HeatMapTile component","Tue: SectorDonut chart",
              "Wed: PositionsTable with filters","Thu: CSV export; watchlist panel",
              "Fri: 30s WebSocket refresh; integration test"],
    )

    WEEKS[41] = dict(
        title="Advanced Risk Metrics: VaR, CVaR & Stress Testing",
        subtitle="Implement institution-grade risk metrics and a dedicated Risk Control Room view.",
        kpis=[("VaR","99% 1-day"),("CVaR","Expected Shortfall"),("Stress","7 scenarios"),("Dashboard","Full view")],
        goals=["99% VaR via historical simulation on 252 days of returns",
               "CVaR = average loss in worst 1% of days (more conservative than VaR)",
               "7 stress scenarios: 2008 GFC, 2020 COVID, 2022 Rate Hike, 2011 Debt Ceiling, SVB 2023, etc.",
               "Dollar amounts: 'Worst expected day: -$2,340' — intuitive display",
               "Risk score 0-100: aggregate portfolio risk level",
               "RiskControlRoom.tsx: full-page risk dashboard"],
        tasks=["extend monte_carlo.py: historical_var(), cvar(), stress_tests()",
               "GET /api/v1/risk/dashboard → VaR, CVaR, stress, risk_score",
               "RiskControlRoom.tsx: gauge, 7 stress panels, risk score ring",
               "Risk score = weighted(VaR%, drawdown%, greek_exposure, concentration)",
               "/risk route in React Router; add to nav sidebar"],
        deliverables=["VaR + CVaR correct for test portfolio","7 stress scenarios produce results",
                      "Risk score aligns with intuitive riskiness","RiskControlRoom accessible from nav"],
        autopilot=["Risk score > 75 → autopilot reduces size to 50%",
                   "CVaR used for position sizing (more conservative than VaR)",
                   "Stress test shown in pre-market briefing: 'If 2020-repeat: -$5,400'"],
        risk=["Risk: Stress test assumes stationary returns → add regime overlay",
              "Risk: Risk score weighting arbitrary → document formula; allow config"],
        code=["def historical_var(returns, confidence=0.99):",
              "    s = np.sort(returns)",
              "    idx = int((1-confidence)*len(s))",
              "    return abs(s[idx]), abs(s[:idx].mean())  # VaR, CVaR"],
        days=["Mon: VaR+CVaR","Tue: 7 stress scenarios","Wed: Risk score formula",
              "Thu: RiskControlRoom.tsx","Fri: VaR gate in autopilot sizing"],
    )

    WEEKS[42] = dict(
        title="SEC Filing & Earnings Call LLM Analysis",
        subtitle="Analyze 10-Q filings and earnings transcripts with Gemini for fundamental risk signals.",
        kpis=[("Coverage","S&P 500 10-Qs"),("Analysis","5-factor LLM"),("Cache","90 days"),("Signal","Fundamental risk 0-100")],
        goals=["Fetch 10-Q filings via SEC EDGAR API",
               "Fetch earnings call transcripts via Seeking Alpha / Motley Fool RSS",
               "Gemini 5-factor analysis: liquidity, guidance, legal, management, competitive",
               "fundamental_risk_score per symbol (0-100); stored with 90-day cache",
               "High risk (>70) → reduce position size 50%",
               "Filing summary shown in SymbolDetailPanel"],
        tasks=["sec_edgar.py: fetch latest 10-Q text","transcript_fetcher.py: earnings transcript",
               "gemini_analyst.py: 5-factor prompt → JSON scores + flags",
               "fundamentals table with 90-day TTL",
               "SymbolDetailPanel.tsx: show risk flags + score"],
        deliverables=["10-Q fetched for AAPL, MSFT","Gemini returns risk flags correctly",
                      "Fundamental risk score in entry scorer","Filing summary in symbol panel"],
        autopilot=["Quarterly filing cycle: autopilot knows when each company last filed",
                   "High-risk fundamentals → size reduction applied automatically",
                   "LLM filing analysis: most sophisticated fundamental signal in the system"],
        risk=["Risk: Gemini context limit → chunk filing; summarize each section first",
              "Risk: EDGAR throttling → cache aggressively; 0.5s delays"],
        code=["FILING_PROMPT = '''Analyze 10-Q for risks. Score (0-100, higher=riskier):",
              "1.Liquidity 2.Guidance 3.Legal 4.Management 5.Competitive",
              "Return JSON: {scores:{},flags:[],summary:str}'''"],
        days=["Mon: EDGAR filing fetcher","Tue: Transcript fetcher","Wed: Gemini 5-factor prompt",
              "Thu: Fundamental risk score + cache","Fri: SymbolDetailPanel; entry scorer weight"],
    )

    WEEKS[43] = dict(
        title="Options Roll Engine & Term Structure Analysis",
        subtitle="Automated roll detection and execution — roll losing positions to next month before expiry.",
        kpis=[("Trigger","DTE < 7"),("Auto-roll","Atomic close+open"),("Cost","< $50 per roll"),("Term","IV curve cross-expiry")],
        goals=["Term structure: IV curve across expiry months to find optimal roll target",
               "Roll trigger: DTE < 7 → evaluate roll vs close",
               "Atomic roll: close current + open next-month as paired order",
               "Roll cost analysis: net debit/credit must be favorable",
               "Backtest roll vs close-and-reopen on 2 years of data",
               "RollView: upcoming rolls, candidates, history"],
        tasks=["term_structure.py: IV across expirations","roll_detector.py: DTE<7 scanner",
               "RollEvaluator: compute P&L impact of roll","Atomic roll executor",
               "GET /api/v1/rolls/candidates","RollView.tsx with history table"],
        deliverables=["Roll trigger fires correctly at DTE<7","Atomic roll executes cleanly",
                      "Term structure chart renders","Roll history in DB"],
        autopilot=["Rolling extends position life, reduces realized losses",
                   "Roll calendar: autopilot plans rolls 5 days in advance",
                   "Only roll if net credit or small debit (<$20); else close and redeploy"],
        risk=["Risk: Roll target month has bad IV → skip roll, close instead",
              "Risk: Partial roll (close fills but open fails) → treat as open leg; monitor separately"],
        code=["def evaluate_roll(pos, chain):",
              "    roll_credit = find_30dte(chain).credit",
              "    net = roll_credit - pos.buyback_cost",
              "    return RollDecision(should_roll=net>-20, net_credit=net)"],
        days=["Mon: Term structure + IV curve","Tue: Roll detector + evaluator",
              "Wed: Atomic roll executor","Thu: Roll backtest","Fri: RollView; scheduler"],
    )

    WEEKS[44] = dict(
        title="Prometheus Metrics & Grafana Observability Stack",
        subtitle="Add production monitoring: 50+ Prometheus metrics, 3 Grafana dashboards, PagerDuty alerts.",
        kpis=[("Metrics","50+ exposed"),("Dashboards","3 Grafana"),("SLA","P99<200ms"),("Alerts","PagerDuty")],
        goals=["50+ Prometheus metrics: cycle duration, order fill rate, API latency, errors, memory",
               "3 Grafana dashboards: System Health, Autopilot Performance, Trading P&L",
               "/health endpoint: comprehensive dependency status",
               "PagerDuty on-call for CRITICAL incidents",
               "Structured JSON logs with rotation",
               "SLA targets: API P99<200ms, cycle<90s, uptime>99.9%"],
        tasks=["pip install prometheus-client","prometheus_metrics.py: all counters/histograms/gauges",
               "FastAPI middleware: auto-instrument endpoints","/metrics Prometheus scrape endpoint",
               "docker-compose: prometheus + grafana","3 Grafana dashboard JSON exports",
               "PagerDuty webhook on CRITICAL alert"],
        deliverables=["50+ metrics at /metrics","Real-time Grafana dashboards",
                      "PagerDuty fires on test CRITICAL","Structured JSON logs everywhere"],
        autopilot=["cycle_duration_seconds P99 visible in Grafana → catch slow cycles early",
                   "orders_placed_total tracks autopilot activity over time",
                   "Alert: cycle_success_rate < 0.8 over 1h → PagerDuty page"],
        risk=["Risk: Prometheus/Grafana adds complexity → single docker-compose; document setup",
              "Risk: PagerDuty billing → free tier; limit to <5 alerts/month"],
        code=["CYCLE_DURATION = Histogram('cycle_duration_seconds','Full cycle time')",
              "ORDERS_PLACED  = Counter('orders_placed_total','Orders placed',['strategy'])",
              "@CYCLE_DURATION.time()",
              "async def run_cycle(): ..."],
        days=["Mon: 30 core Prometheus metrics","Tue: Remaining 20 metrics; /metrics endpoint",
              "Wed: Docker prometheus+grafana","Thu: 3 dashboards","Fri: PagerDuty; structured logs"],
    )

    WEEKS[45] = dict(
        title="All 6 Strategy Types Live with Regime Allocation",
        subtitle="Enable all 6 options strategies with intelligent regime-based allocation weighting.",
        kpis=[("Strategies","6 active"),("Allocation","Regime-driven"),("Max/Type","30%"),("Scan","Parallel")],
        goals=["All 6 strategies live: PutCreditSpread, CallCreditSpread, IronCondor, IronButterfly, CalendarSpread, DiagonalSpread",
               "Regime allocation: Bull→60% PutCredit, Bear→60% CallCredit, HighVol→50% IronCondor",
               "6 parallel scans via asyncio.gather",
               "Per-strategy P&L, win rate, Sharpe tracked",
               "Auto-deactivate if OOS Sharpe < 0.5 for 30 days",
               "Max 30% notional per strategy type"],
        tasks=["Build CalendarSpread + DiagonalSpread chain builders + Greeks",
               "asyncio.gather for 6 parallel strategy scans",
               "AllocationManager: $ per strategy from regime config",
               "Strategy health monitor: rolling Sharpe per strategy",
               "Auto-deactivate low-Sharpe strategies in config",
               "StrategyAllocationView.tsx: donut + table"],
        deliverables=["All 6 strategies execute in paper mode","Regime allocation shifts correctly",
                      "Parallel scan beats sequential time","Auto-deactivation works"],
        autopilot=["6 strategies = 6 alpha streams — regime drives which is emphasized",
                   "Auto-deactivation: autopilot fires underperforming strategies on its own"],
        risk=["Risk: Iron Butterfly hard to fill → strict limit orders; tighter spread rules",
              "Risk: Calendar needs 2 expirations → validate both legs exist before scan"],
        code=["async def scan_all(data):",
              "    return await asyncio.gather(",
              "        *[scan_strategy(s,data) for s in ACTIVE_STRATEGIES],",
              "        return_exceptions=True)"],
        days=["Mon: Calendar+Diagonal builders","Tue: Parallel scan","Wed: AllocationManager",
              "Thu: Strategy health monitor","Fri: StrategyAllocationView; E2E test"],
    )

    WEEKS[46] = dict(
        title="AI-Powered Market Briefings in Natural Language",
        subtitle="Gemini-generated pre-market and EOD briefings in Bloomberg-style prose delivered to Slack + email.",
        kpis=[("Briefings","2 daily"),("Sources","7 data feeds"),("Style","NL prose"),("Delivery","Slack+Email+App")],
        goals=["Pre-market briefing at 8:30 AM: overnight news, vol regime, economic events, day's setup",
               "EOD briefing at 4:05 PM: narrative of day's trades, P&L, autopilot decisions",
               "Gemini prompt with 7 structured data sources → 3-paragraph NL prose",
               "Push to Slack, email, and BriefingView in dashboard",
               "Store briefings in DB; searchable by date"],
        tasks=["briefing_generator.py: pre_market_briefing(), eod_briefing()",
               "7 sources: VIX, regime, earnings cal, econ cal, positions, P&L, sentiment",
               "Gemini role='financial analyst'; structured injection → Bloomberg-style output",
               "BriefingView.tsx: styled text view with date navigator",
               "Scheduler: pre-market at 8:30 AM, EOD at 4:05 PM"],
        deliverables=["Pre-market briefing generated for test date","EOD references actual trades",
                      "BriefingView renders","Slack delivery confirmed"],
        autopilot=["Briefings make autopilot decisions legible to non-technical users",
                   "EOD includes 'Today's lesson' section: what worked, what didn't",
                   "Pre-market shows confidence level for coming session"],
        risk=["Risk: Gemini unavailable at 8:30 AM → fallback template-based structured briefing",
              "Risk: LLM false statements → add disclaimer; instruct user to verify key facts"],
        code=["PROMPT=f'Regime={regime}, VIX={vix}, Earnings={earnings}, Sentiment={sentiment}",
              "Write 3 paragraphs: 1)Market context 2)Today setup 3)Risk factors (Bloomberg style)'"],
        days=["Mon: briefing_generator with 7 data sources","Tue: Gemini prompt engineering",
              "Wed: BriefingView.tsx","Thu: Slack+email delivery","Fri: Scheduler + DB storage"],
    )

    WEEKS[47] = dict(
        title="Redis Caching, Rate Limiting & CDN Deployment",
        subtitle="Harden the production API with multi-tier caching, rate limiting, and CDN frontend delivery.",
        kpis=[("Cache Hit",">70%"),("Rate Limit","100 req/min"),("CDN","Cloudflare Pages"),("TTL","Strategy-based")],
        goals=["Multi-tier: in-memory(1s) → Redis(60s) → DB","Tiered TTL: quote 5s, option chain 30s, fundamentals 24h",
               "Rate limiting: 100 req/min per client; 429 with Retry-After",
               "CDN: React build on Cloudflare Pages","Cache invalidation via WebSocket events",
               "Cache hit rate in Prometheus metrics"],
        tasks=["pip install redis","redis_cache.py: get/set/invalidate with TTL",
               "@cache(ttl=30) decorator on market data endpoints",
               "FastAPI middleware: Redis sliding-window rate limiter",
               "Vite build → Cloudflare Pages deploy script",
               "Prometheus: cache_hit_total, cache_miss_total counters"],
        deliverables=["Redis reduces Tradier API calls by >70%","Rate limiter returns 429 at limit",
                      "Frontend on CDN <100ms global TTFB","Cache hit rate in Grafana"],
        autopilot=["Option chains cached 30s → scan phase faster",
                   "Cache invalidation on position update ensures positions view always fresh"],
        risk=["Risk: Redis down → fallback to in-memory dict; log warning",
              "Risk: Stale cache on real-time data → keep quote TTL very short (5s max)"],
        code=["@cache(ttl=30)",
              "async def get_option_chain(sym):  # only fetches on miss",
              "    return await tradier.get_chain(sym)"],
        days=["Mon: Redis client + decorator","Tue: TTL strategy per endpoint",
              "Wed: Rate limiter middleware","Thu: CDN deployment","Fri: Cache stats in Grafana"],
    )

    WEEKS[48] = dict(
        title="Automated Strategy Research & Alpha Discovery Engine",
        subtitle="Build a research mode that autonomously generates, tests, and ranks new strategy variants weekly.",
        kpis=[("Variants","50/week"),("Auto-test","Walk-forward"),("Promote","Sharpe>1.5"),("Report","Weekly digest")],
        goals=["Generate 50 strategy variants by systematic parameter perturbation",
               "Auto-test each with accelerated walk-forward backtest",
               "Rank by OOS Sharpe; promote top-3 to staging for paper testing",
               "Weekly research email: top-5 discoveries with stats",
               "Human review gate before any variant enters paper testing"],
        tasks=["research_mode.py: variant_generator() → 50 param combos",
               "Accelerated WF: 5-year OOS, 6-month training window",
               "StrategyRegistry: research/staging/production status",
               "POST /api/v1/research/run (Sunday night async job)",
               "ResearchView.tsx: ranking table with promote/dismiss buttons"],
        deliverables=["50 variants tested in <2 hours","Top-3 staged correctly",
                      "Research email sent","ResearchView shows all results"],
        autopilot=["Research mode = autopilot evolving itself",
                   "Promoted variants shadow-paper for 4 weeks before production",
                   "Mutation is systematic (grid around best params), not random"],
        risk=["Risk: Lucky backtest period → require 3-year OOS minimum",
              "Risk: Report over-hypes → show confidence intervals; always caveat OOS"],
        code=["def generate_variants(base, n=50):",
              "    return [{k:v*(1+random.uniform(-0.2,0.2)) for k,v in base.items()}",
              "            for _ in range(n)]"],
        days=["Mon: Variant generator","Tue: Accelerated WF engine","Wed: StrategyRegistry + promotion",
              "Thu: ResearchView + email report","Fri: Sunday scheduler; E2E test"],
    )

    WEEKS[49] = dict(
        title="Kelly Criterion Position Sizing & Volatility Targeting",
        subtitle="Replace fixed sizing with fractional Kelly, vol targeting, and dynamic regime-based scaling.",
        kpis=[("Method","25% Kelly"),("Vol Target","12% annual"),("Dynamic","Per-regime"),("Max Risk","2% per trade")],
        goals=["Fractional Kelly (0.25×) based on historical win rate and avg win/loss",
               "Volatility targeting: scale positions to maintain 12% annual portfolio vol",
               "Regime sizing: ×1.0 Neutral, ×0.7 Bear, ×0.5 HighVol",
               "Max 2% of portfolio risk per single trade",
               "Sizing breakdown shown in RunArtifact trace"],
        tasks=["kelly_calculator.py: fractional_kelly(win_rate, avg_win, avg_loss)",
               "vol_scaler.py: compute 20-day realized vol; scale factor",
               "regime_sizer.py: multiply Kelly by regime confidence",
               "Final qty = min(kelly_qty, max_risk_qty, 2% budget)",
               "Sizing breakdown in RunArtifact JSON"],
        deliverables=["Kelly produces correct quantities for test cases",
                      "Vol targeting reduces size when portfolio vol > 12%",
                      "Regime sizing cuts positions in Bear/HighVol",
                      "Sizing breakdown visible in run artifact"],
        autopilot=["Position sizing is one of the highest-impact autopilot improvements",
                   "25% Kelly protects against estimation error in win rate",
                   "Vol targeting makes drawdowns more predictable"],
        risk=["Risk: Kelly huge with small sample → require 30+ trades before Kelly is trusted",
              "Risk: Intraday vol spike → use 20-day realized vol, not intraday"],
        code=["def fractional_kelly(win_rate, avg_win, avg_loss, f=0.25):",
              "    edge = win_rate*avg_win - (1-win_rate)*avg_loss",
              "    return (edge/avg_win) * f  # 25% fractional Kelly"],
        days=["Mon: Kelly calculator","Tue: Vol targeting scaler","Wed: Regime multiplier",
              "Thu: Cycle integration","Fri: Sizing trace in RunArtifact; E2E test"],
    )

    WEEKS[50] = dict(
        title="Security Hardening: JWT, 2FA & Pen Test",
        subtitle="Full security audit: JWT auth for all endpoints, TOTP 2FA, OWASP ZAP pen test, secrets vault.",
        kpis=[("Auth","JWT+TOTP"),("OWASP","0 HIGH findings"),("Secrets","Vault-managed"),("Headers","Grade A")],
        goals=["JWT auth for all API endpoints","TOTP 2FA via pyotp (Google Authenticator compatible)",
               "OWASP ZAP scan; fix all HIGH/CRITICAL findings","HashiCorp Vault for API key management",
               "SQL injection check: all ORM queries; no raw SQL","CSP + HSTS + security headers"],
        tasks=["JWT: POST /auth/login → token; all routes require Bearer",
               "TOTP: pyotp; QR code setup in Settings","ZAP CI scan; fail on HIGH",
               "HashiCorp Vault dev mode; vault.read() for all secrets",
               "Security headers middleware: CSP, HSTS, X-Frame-Options"],
        deliverables=["JWT auth working","2FA setup flow in Settings","Zero HIGH ZAP findings",
                      "Security headers grade A on securityheaders.com"],
        autopilot=["API auth ensures no unauthorized trade triggers",
                   "Vault allows key rotation without code deployment"],
        risk=["Risk: JWT secret leaked → rotate immediately; invalidate all tokens",
              "Risk: TOTP QR exposed → HTTPS only; delete QR after first scan"],
        code=["def create_token(user_id):",
              "    return jwt.encode({'sub':user_id,'exp':utcnow()+timedelta(hours=12)},",
              "                      vault.get('JWT_SECRET'), algorithm='HS256')"],
        days=["Mon: JWT auth all routes","Tue: TOTP 2FA","Wed: OWASP ZAP + fixes",
              "Thu: HashiCorp Vault","Fri: Security headers; final scan"],
    )

    WEEKS[51] = dict(
        title="Documentation Suite: User Guide, API Ref & Runbook",
        subtitle="Build comprehensive docs: Docusaurus site, Storybook components, OpenAPI reference, and 15-scenario runbook.",
        kpis=[("Docs","50+ pages"),("Storybook","20 components"),("Runbook","15 scenarios"),("Coverage","100% features")],
        goals=["10-chapter user guide in Docusaurus",
               "OpenAPI enhanced with rich descriptions and examples",
               "Storybook for all 20 React components",
               "Architecture diagram (Mermaid) in README",
               "Runbook: 15 failure scenarios with exact remediation steps",
               "README quick-start: running in <5 commands"],
        tasks=["Docusaurus setup in docs/; write 10 guide chapters",
               "Enhance FastAPI endpoint docstrings → auto-generates OpenAPI",
               "npx storybook init; stories for all components",
               "Mermaid architecture diagram in README",
               "runbook.md: 15 scenarios"],
        deliverables=["Docusaurus site builds","All 20 components have Storybook stories",
                      "README architecture diagram renders","Runbook covers 15 failures"],
        autopilot=["Documentation makes autopilot decisions auditable by anyone",
                   "Architecture diagram shows data flow: Market→Scan→LLM→Validate→Execute→Monitor"],
        risk=["Risk: Docs fall out of date → docs-check CI step; fail if endpoints undocumented"],
        code=["@app.post('/api/v1/autopilot/cycle',",
              "    summary='Run full autopilot cycle',",
              "    description='Scan→LLM→Validate→Execute. dry_run=True skips orders.',",
              "    response_model=RunArtifact, tags=['Autopilot'])"],
        days=["Mon: Docusaurus + 5 guide chapters","Tue: 5 more chapters + runbook",
              "Wed: Storybook for all components","Thu: README architecture diagram",
              "Fri: API docstrings; docs CI check"],
    )

    WEEKS[52] = dict(
        title="Year 1 Wrap-Up: Performance Review & Year 2 Planning",
        subtitle="Comprehensive Year 1 retrospective, paper trading results analysis, and Year 2 roadmap creation.",
        kpis=[("Paper Trades","500+ target"),("Year Review","Complete"),("Y2 Roadmap","Approved"),("Tag","v2.0-rc1")],
        goals=["Year 1 attribution: 52 weeks development + paper trading results",
               "All-time paper stats: trades, win rate, Sharpe, max drawdown, best strategy",
               "Architecture retrospective: what needs rewrite in Y2",
               "Tech debt audit: categorize and prioritize all debt items",
               "Year 2 Roadmap: AI agent autonomy, real money, institutional features",
               "Tag v2.0-rc1; blog post / Devpost update"],
        tasks=["year_review.py: query all DB tables for Year 1 stats",
               "Year 1 report PDF via ReportEngine",
               "Architecture retrospective document",
               "Year 2 Roadmap.md: key themes and milestones",
               "git tag v2.0-rc1 with annotated release notes"],
        deliverables=["Year 1 performance report PDF","Architecture retrospective",
                      "Year 2 Roadmap approved","v2.0-rc1 on GitHub","Blog post published"],
        autopilot=["Year 1 autopilot: 26 weeks operation, 500+ paper trades, dual-LLM — COMPLETE",
                   "Year 2 theme: fully adaptive AI agent instead of rule-based",
                   "Key Y1 lesson: which strategies and parameters worked best"],
        risk=["Risk: Y1 results disappointing → use Y2 to reboot; don't abandon the system",
              "Risk: Tech debt too high → allocate first 4 weeks of Y2 as refactoring sprint"],
        code=["SELECT strategy_type, COUNT(*), AVG(CASE WHEN pnl>0 THEN 1.0 ELSE 0 END) win_rate,",
              "       SUM(pnl) total_pnl FROM trades",
              "GROUP BY strategy_type ORDER BY total_pnl DESC"],
        days=["Mon: Year 1 analysis scripts","Tue: Year 1 report PDF + retrospective",
              "Wed: Year 2 Roadmap document","Thu: git tag + release notes","Fri: Blog post + share"],
    )
