"""unified_online_schema

Revision ID: ab51c66a55cd
Revises: 
Create Date: 2026-02-20 21:32:58.138339

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab51c66a55cd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=True),
    sa.Column('user', sa.String(length=100), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_action'), 'audit_log', ['action'], unique=False)
    op.create_index(op.f('ix_audit_log_entity_type'), 'audit_log', ['entity_type'], unique=False)
    op.create_index(op.f('ix_audit_log_timestamp'), 'audit_log', ['timestamp'], unique=False)
    op.create_table('autopilot_incidents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('severity', sa.String(length=10), nullable=True),
    sa.Column('category', sa.String(length=30), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('run_id', sa.String(length=36), nullable=True),
    sa.Column('symbol', sa.String(length=10), nullable=True),
    sa.Column('resolved', sa.Boolean(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('resolution_note', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('autopilot_positions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('occ_symbol', sa.String(length=30), nullable=True),
    sa.Column('strategy_template', sa.String(length=30), nullable=False),
    sa.Column('entry_order_id', sa.String(length=36), nullable=True),
    sa.Column('entry_qty', sa.Integer(), nullable=True),
    sa.Column('entry_price', sa.Float(), nullable=True),
    sa.Column('entry_premium', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('current_qty', sa.Integer(), nullable=True),
    sa.Column('current_price', sa.Float(), nullable=True),
    sa.Column('unrealized_pnl', sa.Float(), nullable=True),
    sa.Column('exit_order_id', sa.String(length=36), nullable=True),
    sa.Column('exit_price', sa.Float(), nullable=True),
    sa.Column('exit_reason', sa.String(length=30), nullable=True),
    sa.Column('realized_pnl', sa.Float(), nullable=True),
    sa.Column('stop_loss_price', sa.Float(), nullable=True),
    sa.Column('profit_target_price', sa.Float(), nullable=True),
    sa.Column('time_stop_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('autopilot_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('phase', sa.String(length=30), nullable=True),
    sa.Column('symbols_scanned', sa.Integer(), nullable=True),
    sa.Column('candidates_generated', sa.Integer(), nullable=True),
    sa.Column('candidates_selected', sa.Integer(), nullable=True),
    sa.Column('orders_placed', sa.Integer(), nullable=True),
    sa.Column('positions_closed', sa.Integer(), nullable=True),
    sa.Column('market_open', sa.Boolean(), nullable=True),
    sa.Column('regime', sa.String(length=20), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('think_log', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bars',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('timeframe', sa.String(length=10), nullable=False),
    sa.Column('bar_index', sa.BigInteger(), nullable=False),
    sa.Column('ts_start_ms', sa.BigInteger(), nullable=False),
    sa.Column('ts_end_ms', sa.BigInteger(), nullable=False),
    sa.Column('open', sa.Float(), nullable=True),
    sa.Column('high', sa.Float(), nullable=True),
    sa.Column('low', sa.Float(), nullable=True),
    sa.Column('close', sa.Float(), nullable=True),
    sa.Column('volume', sa.Float(), nullable=True),
    sa.Column('state', sa.String(length=20), nullable=True),
    sa.Column('tick_count', sa.Integer(), nullable=True),
    sa.Column('last_update_ms', sa.BigInteger(), nullable=True),
    sa.Column('bar_hash', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'timeframe', 'bar_index', name='uix_bar_identity')
    )
    op.create_index(op.f('ix_bars_bar_index'), 'bars', ['bar_index'], unique=False)
    op.create_index(op.f('ix_bars_symbol'), 'bars', ['symbol'], unique=False)
    op.create_index(op.f('ix_bars_timeframe'), 'bars', ['timeframe'], unique=False)
    op.create_index(op.f('ix_bars_ts_start_ms'), 'bars', ['ts_start_ms'], unique=False)
    op.create_index('ix_legacy_bar_lookup', 'bars', ['symbol', 'timeframe', 'ts_start_ms'], unique=False)
    op.create_table('market_bars',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('timeframe', sa.String(length=10), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('open', sa.Float(), nullable=False),
    sa.Column('high', sa.Float(), nullable=False),
    sa.Column('low', sa.Float(), nullable=False),
    sa.Column('close', sa.Float(), nullable=False),
    sa.Column('volume', sa.Float(), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('ingested_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'timeframe', 'timestamp', name='uq_bar')
    )
    op.create_index('ix_bar_lookup', 'market_bars', ['symbol', 'timeframe', 'timestamp'], unique=False)
    op.create_index(op.f('ix_market_bars_symbol'), 'market_bars', ['symbol'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('broker_order_id', sa.String(length=64), nullable=True),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('side', sa.String(length=10), nullable=False),
    sa.Column('qty', sa.Float(), nullable=False),
    sa.Column('order_type', sa.String(length=20), nullable=False),
    sa.Column('limit_price', sa.Float(), nullable=True),
    sa.Column('stop_price', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('filled_qty', sa.Float(), nullable=True),
    sa.Column('filled_avg_price', sa.Float(), nullable=True),
    sa.Column('strategy_id', sa.String(length=64), nullable=True),
    sa.Column('autopilot_run_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('filled_at', sa.DateTime(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('broker_order_id')
    )
    op.create_index(op.f('ix_orders_strategy_id'), 'orders', ['strategy_id'], unique=False)
    op.create_index(op.f('ix_orders_symbol'), 'orders', ['symbol'], unique=False)
    op.create_table('positions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('qty', sa.Float(), nullable=False),
    sa.Column('avg_entry_price', sa.Float(), nullable=False),
    sa.Column('current_price', sa.Float(), nullable=True),
    sa.Column('market_value', sa.Float(), nullable=True),
    sa.Column('unrealized_pnl', sa.Float(), nullable=True),
    sa.Column('side', sa.String(length=10), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol')
    )
    op.create_table('raw_ticks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('ts_ms', sa.BigInteger(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('size', sa.Float(), nullable=True),
    sa.Column('tick_hash', sa.String(length=32), nullable=True),
    sa.Column('ingested_at', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tick_hash')
    )
    op.create_index(op.f('ix_raw_ticks_symbol'), 'raw_ticks', ['symbol'], unique=False)
    op.create_index(op.f('ix_raw_ticks_ts_ms'), 'raw_ticks', ['ts_ms'], unique=False)
    op.create_index('ix_tick_lookup', 'raw_ticks', ['symbol', 'ts_ms'], unique=False)
    op.create_table('strategies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('strategy_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('symbols', sa.JSON(), nullable=True),
    sa.Column('parameters', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('strategy_id')
    )
    op.create_table('workflows',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('workflow_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('steps', sa.JSON(), nullable=False),
    sa.Column('triggers', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workflow_id')
    )
    op.create_table('autopilot_candidates',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('strategy_template', sa.String(length=30), nullable=False),
    sa.Column('option_type', sa.String(length=10), nullable=True),
    sa.Column('strike', sa.Float(), nullable=True),
    sa.Column('expiry', sa.String(length=10), nullable=True),
    sa.Column('delta', sa.Float(), nullable=True),
    sa.Column('base_score', sa.Float(), nullable=True),
    sa.Column('adjusted_score', sa.Float(), nullable=True),
    sa.Column('premium', sa.Float(), nullable=True),
    sa.Column('max_loss', sa.Float(), nullable=True),
    sa.Column('max_profit', sa.Float(), nullable=True),
    sa.Column('dte', sa.Integer(), nullable=True),
    sa.Column('selected', sa.Boolean(), nullable=True),
    sa.Column('rejection_reasons', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['autopilot_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('autopilot_llm_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('model', sa.String(length=50), nullable=False),
    sa.Column('latency_ms', sa.Float(), nullable=True),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('context_summary', sa.Text(), nullable=True),
    sa.Column('raw_response', sa.Text(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('validation_outcome', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['autopilot_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('autopilot_orders',
    sa.Column('client_order_id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=True),
    sa.Column('position_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('occ_symbol', sa.String(length=30), nullable=True),
    sa.Column('side', sa.String(length=10), nullable=False),
    sa.Column('order_type', sa.String(length=10), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('limit_price', sa.Float(), nullable=True),
    sa.Column('alpaca_order_id', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('filled_qty', sa.Integer(), nullable=True),
    sa.Column('filled_avg_price', sa.Float(), nullable=True),
    sa.Column('filled_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['position_id'], ['autopilot_positions.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['autopilot_runs.id'], ),
    sa.PrimaryKeyConstraint('client_order_id')
    )
    op.create_table('backtest_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('strategy_id', sa.String(length=64), nullable=True),
    sa.Column('symbols', sa.JSON(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.Column('initial_capital', sa.Float(), nullable=False),
    sa.Column('parameters', sa.JSON(), nullable=True),
    sa.Column('results', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.strategy_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id')
    )
    op.create_table('fills',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('broker_fill_id', sa.String(length=64), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('qty', sa.Float(), nullable=False),
    sa.Column('side', sa.String(length=10), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('commission', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('broker_fill_id')
    )
    op.create_index(op.f('ix_fills_order_id'), 'fills', ['order_id'], unique=False)
    op.create_table('workflow_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('workflow_id', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('step_results', sa.JSON(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.workflow_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('workflow_runs')
    op.drop_index(op.f('ix_fills_order_id'), table_name='fills')
    op.drop_table('fills')
    op.drop_table('backtest_runs')
    op.drop_table('autopilot_orders')
    op.drop_table('autopilot_llm_logs')
    op.drop_table('autopilot_candidates')
    op.drop_table('workflows')
    op.drop_table('strategies')
    op.drop_index('ix_tick_lookup', table_name='raw_ticks')
    op.drop_index(op.f('ix_raw_ticks_ts_ms'), table_name='raw_ticks')
    op.drop_index(op.f('ix_raw_ticks_symbol'), table_name='raw_ticks')
    op.drop_table('raw_ticks')
    op.drop_table('positions')
    op.drop_index(op.f('ix_orders_symbol'), table_name='orders')
    op.drop_index(op.f('ix_orders_strategy_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_market_bars_symbol'), table_name='market_bars')
    op.drop_index('ix_bar_lookup', table_name='market_bars')
    op.drop_table('market_bars')
    op.drop_index('ix_legacy_bar_lookup', table_name='bars')
    op.drop_index(op.f('ix_bars_ts_start_ms'), table_name='bars')
    op.drop_index(op.f('ix_bars_timeframe'), table_name='bars')
    op.drop_index(op.f('ix_bars_symbol'), table_name='bars')
    op.drop_index(op.f('ix_bars_bar_index'), table_name='bars')
    op.drop_table('bars')
    op.drop_table('autopilot_runs')
    op.drop_table('autopilot_positions')
    op.drop_table('autopilot_incidents')
    op.drop_index(op.f('ix_audit_log_timestamp'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_entity_type'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_action'), table_name='audit_log')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
