# Days 21-45 content chunk

CHUNK = '''
_d(21, "Automated Exit Trigger System",
   "Build rule-based and ML-assisted exit triggers: profit target, stop loss, time decay, delta breach, IV crush detection, with configurable per-strategy exit rules.",
   ["grep -rn 'exit\\|close_position\\|should_exit' phase1/services/autopilot/ | wc -l",
    "cat phase1/services/autopilot/monitoring.py | head -50",
    "cat phase1/services/autopilot/exit_triggers.py | head -30 2>/dev/null || echo 'no exit_triggers file'",
    "python3 -c \\"thresholds={'profit_target':0.50,'stop_loss':-1.00,'dte_exit':21,'delta_breach':0.30,'iv_crush':0.20}; print(thresholds)\\"",
    "grep -rn 'profit_target\\|stop_loss\\|max_loss' phase1/services/autopilot/config.py",
    "python3 -c \\"import numpy as np; prices=np.random.normal(185,5,100); trail_stop=np.maximum.accumulate(prices)*0.95; print(f'Trail stop at {trail_stop[-1]:.2f}')\\"",
    "cat phase1/services/autopilot/unified_engine.py | grep -c 'exit\\|close'",
    "python3 -c \\"dte=30; theta=-0.05; daily_decay=theta/dte*100; print(f'Daily theta decay: {daily_decay:.2f}%')\\""],
   ["phase1/services/exits/exit_engine.py (new: evaluate all exit rules per position, return priority-ranked exit signals)",
    "phase1/services/exits/profit_target.py (new: configurable % profit target with partial exit option)",
    "phase1/services/exits/stop_loss.py (new: fixed, trailing, and volatility-adjusted stop losses)",
    "phase1/services/exits/time_exit.py (new: exit at X DTE to avoid gamma risk near expiration)",
    "phase1/services/exits/delta_exit.py (new: exit if short strike delta exceeds threshold)",
    "phase1/services/exits/iv_crush_detector.py (new: detect post-earnings IV crush, accelerate exit)",
    "phase1/services/exits/composite_exit.py (new: combine multiple exit signals with priority weighting)",
    "phase1/services/exits/exit_config.py (new: per-strategy exit rule configuration with validation)",
    "phase1/services/autopilot/monitoring.py (update: replace ad-hoc exit checks with exit engine)",
    "phase1/services/api/exits_routes.py (new: GET /exits/rules, PUT /exits/rules/{strategy}, GET /exits/signals)",
    "frontend/src/features/autopilot/ExitRulesEditor.tsx (new: per-strategy exit rule configuration UI)",
    "phase1/tests/unit/test_exit_engine.py (new: profit target hit, stop triggered, DTE exit, delta breach)"],
   ["Exit Priority Hierarchy: kill_switch > stop_loss > delta_breach > profit_target > time_exit > iv_crush",
    "Partial Exits: close 50% at 50% profit, trail remaining 50% with tighter stop",
    "Trailing Stop: track highest unrealized profit, exit if retracement exceeds 30% of max profit",
    "Gamma Scalping Window: reduce position size at 14 DTE, fully exit at 7 DTE unless deep OTM",
    "IV Crush Detection: if IV drops > 20% within 24h (post-earnings), accelerate profit-taking",
    "Exit Logging: every exit decision logged with all rule evaluations for post-mortem analysis"],
   ["Prompt: 'Build exit engine evaluating 6 exit rules per position: profit target, stop loss, DTE, delta, IV crush, trailing stop.'",
    "Prompt: 'Implement trailing stop that tracks max unrealized profit and exits on 30% retracement.'",
    "Prompt: 'Write IV crush detector: compare current IV to 5-day average, flag if drop exceeds 20%.'",
    "Prompt: 'Create ExitRulesEditor React component: per-strategy sliders for profit target, stop loss, DTE threshold.'",
    "Prompt: 'Write tests: position at 60% profit triggers exit, position hitting -100% stop triggers exit, DTE=5 triggers exit.'"],
   "Premature exits from volatile positions reduce win rate. Mitigation: use volatility-adjusted stops (wider during high VIX). Backtest exit rules before deploying.",
   "Exit engine evaluates all rules per position every 5 minutes. Profit targets, stops, DTE exits all automated. Exit log shows every decision."
)

_d(22, "Kill Switch: Recovery, Auto-Restart, and Incident Response",
   "Enhance kill switch with auto-recovery logic, graduated response levels (caution/warning/critical/halt), incident logging, and automated post-mortem generation.",
   ["grep -rn 'kill.switch\\|emergency\\|halt' phase1/services/autopilot/ | wc -l",
    "cat phase1/services/autopilot/unified_engine.py | grep -A20 'kill_switch'",
    "cat phase1/services/autopilot/config.py | grep -i 'kill\\|emergency\\|max_loss'",
    "python3 -c \\"levels=['NORMAL','CAUTION','WARNING','CRITICAL','HALT']; print(dict(enumerate(levels)))\\"",
    "python3 -c \\"daily_loss=-500; max_daily=-1000; level='CAUTION' if daily_loss>max_daily*0.5 else 'NORMAL'; print(f'Loss: {daily_loss}, Level: {level}')\\"",
    "grep -rn 'incident\\|postmortem\\|recovery' phase1/services/ | wc -l",
    "cat phase1/services/incidents/ -la 2>/dev/null || echo 'incidents dir exists'",
    "python3 -c \\"triggers={'daily_loss_50pct':'CAUTION','daily_loss_75pct':'WARNING','daily_loss_100pct':'CRITICAL','api_failure':'WARNING','llm_failure':'CAUTION'}; print(triggers)\\""],
   ["phase1/services/killswitch/graduated_response.py (new: 5-level response system with auto-escalation logic)",
    "phase1/services/killswitch/recovery.py (new: auto-recovery checks, gradual position resume, health verification)",
    "phase1/services/killswitch/incident_logger.py (new: structured incident records with timeline, actions, resolution)",
    "phase1/services/killswitch/postmortem.py (new: auto-generate postmortem from incident data, logs, and market conditions)",
    "phase1/services/killswitch/notification.py (new: multi-channel alerts: Discord, email, SMS via Twilio)",
    "phase1/services/killswitch/thresholds.py (new: configurable thresholds per level with time-of-day adjustments)",
    "phase1/services/autopilot/unified_engine.py (update: replace binary kill switch with graduated response)",
    "phase1/services/api/killswitch_routes.py (new: GET /killswitch/status, POST /killswitch/override, POST /killswitch/reset)",
    "frontend/src/features/autopilot/KillSwitchPanel.tsx (new: status indicator with level badge, history, manual override)",
    "phase1/tests/unit/test_graduated_response.py (new: escalation, de-escalation, recovery, threshold config)",
    "phase1/tests/unit/test_incident_logger.py (new: incident creation, timeline, resolution recording)"],
   ["Graduated Response: NORMAL(full auto) -> CAUTION(reduce size) -> WARNING(new entries paused) -> CRITICAL(close all) -> HALT(system offline)",
    "Auto-Escalation: 3 consecutive WARNING events within 1 hour auto-escalate to CRITICAL",
    "Recovery Protocol: after CRITICAL, system enters CAUTION for 24h with half position sizes before returning to NORMAL",
    "Incident Timeline: every state change, action taken, and market condition logged with timestamp",
    "Multi-Channel Alerting: NORMAL=log only, CAUTION=Discord, WARNING=Discord+email, CRITICAL=Discord+email+SMS",
    "Manual Override: admin can force any level, requires confirmation and is logged as manual intervention"],
   ["Prompt: 'Implement 5-level graduated response system: NORMAL, CAUTION, WARNING, CRITICAL, HALT with auto-escalation rules.'",
    "Prompt: 'Write auto-recovery: after CRITICAL resolved, enter CAUTION for 24h with half sizes before returning to NORMAL.'",
    "Prompt: 'Create incident logger with structured records: trigger, timeline, actions taken, resolution, duration.'",
    "Prompt: 'Build KillSwitchPanel with traffic light indicator, current level badge, incident history table, manual override button.'",
    "Prompt: 'Write postmortem generator: collect incident data, relevant logs, market conditions, produce markdown report.'"],
   "Auto-recovery re-enabling trading after loss event without human review. Mitigation: CRITICAL->NORMAL requires admin approval. CRITICAL->CAUTION is automatic but CAUTION->NORMAL is manual.",
   "Graduated kill switch with 5 levels. Auto-escalation from WARNING to CRITICAL after 3 events. Recovery requires admin approval. All incidents logged."
)

_d(23, "Frontend Dashboard v2: Widget System with Drag-and-Drop",
   "Redesign dashboard as a configurable widget system with drag-and-drop layout, resizable panels, persistent user layouts, and real-time data binding.",
   ["cd frontend && npm install react-grid-layout @dnd-kit/core @dnd-kit/sortable",
    "cat src/features/layout/views/UnifiedDashboardView.tsx | wc -l",
    "grep -rn 'grid\\|layout\\|widget\\|panel' src/features/ | wc -l",
    "cat src/features/layout/ -la",
    "grep -rn 'localStorage\\|persist\\|save.*layout' src/ | wc -l",
    "python3 -c \\"widgets=['PositionsTile','OrdersTile','ChartWidget','NewsTile','AutopilotPanel','PortfolioSummary','RiskGauge','StrategyCards','MonteCarloChart','ScoreBreakdown']; print(f'{len(widgets)} widgets')\\"",
    "npm ls react-grid-layout 2>/dev/null || echo 'not installed'",
    "cat src/App.tsx | grep -c 'Route\\|route'"],
   ["frontend/src/features/dashboard/WidgetSystem.tsx (new: widget registry, rendering engine, data bindings)",
    "frontend/src/features/dashboard/WidgetGrid.tsx (new: react-grid-layout with drag, drop, resize, snap-to-grid)",
    "frontend/src/features/dashboard/WidgetCard.tsx (new: wrapper with header, resize handle, close button, settings gear)",
    "frontend/src/features/dashboard/WidgetCatalog.tsx (new: sidebar showing available widgets with preview cards)",
    "frontend/src/features/dashboard/LayoutPersistence.ts (new: save/load layouts to localStorage, export/import as JSON)",
    "frontend/src/features/dashboard/presets.ts (new: 3 preset layouts: trader, analyst, monitor)",
    "frontend/src/features/dashboard/WidgetRegistry.ts (new: register widgets with metadata: name, icon, defaultSize, dataSource)",
    "frontend/src/features/layout/views/UnifiedDashboardView.tsx (update: replace hardcoded layout with WidgetGrid)",
    "frontend/src/hooks/useWidgetData.ts (new: hook binding widget to WebSocket/REST data source)",
    "frontend/src/state/layoutStore.ts (new: Zustand store for layout state, widget configs, active preset)",
    "frontend/tests/unit/WidgetGrid.test.tsx (new: add, remove, resize, reorder, persist, load preset)"],
   ["Widget as Component: each widget is a self-contained React component with standard props interface",
    "Layout Engine: react-grid-layout with responsive breakpoints (desktop, tablet, mobile)",
    "Data Binding: each widget declares its data requirements, useWidgetData provides data + loading + error states",
    "Persistence: layout saved to localStorage on every change, synced to backend for cross-device support",
    "Preset Layouts: Trader (chart+positions+orders), Analyst (chart+MC+score+news), Monitor (positions+risk+killswitch)",
    "Widget Catalog: searchable sidebar with drag-to-add, preview on hover, grouped by category"],
   ["Prompt: 'Build a widget-based dashboard using react-grid-layout: drag, drop, resize, persist layout to localStorage.'",
    "Prompt: 'Create WidgetCard wrapper with: title bar, settings gear, close button, resize handle, loading skeleton.'",
    "Prompt: 'Write WidgetCatalog sidebar: searchable list of available widgets with preview cards and drag-to-add.'",
    "Prompt: 'Implement 3 preset layouts: Trader (chart focused), Analyst (data focused), Monitor (system health focused).'",
    "Prompt: 'Create useWidgetData hook that connects widget to WebSocket/REST and provides: data, loading, error, refresh states.'"],
   "Complex widget systems are slow on low-end devices. Mitigation: lazy-load widget contents, virtualize off-screen widgets, limit max 12 widgets per layout.",
   "Dashboard redesigned as widget system. Drag-and-drop working. 3 presets available. Layout persists across sessions. No hardcoded layout remains."
)

_d(24, "Advanced Charting: Indicators, Drawings, and Multi-Timeframe",
   "Upgrade charting with 20+ technical indicators, drawing tools (trendline, fib, support/resistance), multi-timeframe view, and synchronized crosshairs.",
   ["cd frontend && npm install lightweight-charts @anthropic/technical-indicators",
    "cat src/features/chart/ -la",
    "cat src/features/indicators/ -la",
    "grep -rn 'createChart\\|addLineSeries\\|addCandlestick' src/features/chart/ | wc -l",
    "grep -rn 'SMA\\|EMA\\|RSI\\|MACD\\|Bollinger' src/features/indicators/ | wc -l",
    "cat src/features/chart/ChartWidget.tsx | wc -l",
    "python3 -c \\"indicators=['SMA','EMA','RSI','MACD','Bollinger','VWAP','ATR','Stochastic','CCI','OBV','ADX','Ichimoku','Parabolic SAR','Keltner','Donchian','Williams R','MFI','ROC','TRIX','CMF']; print(f'{len(indicators)} indicators')\\"",
    "cat src/features/chart/components/ -la 2>/dev/null || echo 'no chart components dir'"],
   ["frontend/src/features/chart/indicators/IndicatorEngine.ts (new: compute 20+ indicators from OHLCV data)",
    "frontend/src/features/chart/indicators/MovingAverages.ts (new: SMA, EMA, WMA, DEMA, TEMA with configurable periods)",
    "frontend/src/features/chart/indicators/Oscillators.ts (new: RSI, MACD, Stochastic, CCI, Williams%R, MFI)",
    "frontend/src/features/chart/indicators/Volatility.ts (new: Bollinger, ATR, Keltner, Donchian channels)",
    "frontend/src/features/chart/indicators/Volume.ts (new: OBV, CMF, VWAP, Volume Profile)",
    "frontend/src/features/chart/drawings/DrawingEngine.ts (new: trendline, horizontal line, fib retracement, rectangle, text)",
    "frontend/src/features/chart/drawings/DrawingToolbar.tsx (new: toolbar with tool icons, color picker, line style)",
    "frontend/src/features/chart/MultiTimeframe.tsx (new: 2x2 grid showing 1m, 5m, 1h, 1D charts with synced crosshair)",
    "frontend/src/features/chart/ChartWidget.tsx (update: integrate indicator engine, drawing tools, multi-timeframe)",
    "frontend/src/features/chart/IndicatorPanel.tsx (new: add/remove indicators, configure params, toggle visibility)",
    "frontend/tests/unit/IndicatorEngine.test.ts (new: verify SMA, RSI, MACD output against known values)"],
   ["Indicator as Plugin: each indicator implements compute(ohlcv, params) -> Series interface",
    "Overlay vs Pane: overlays (SMA, BB) render on price chart, panes (RSI, MACD) render in separate sub-charts",
    "Drawing Persistence: save drawings to localStorage keyed by symbol+timeframe, restore on chart load",
    "Multi-Timeframe Sync: crosshair movement on one chart highlights corresponding candle on all others",
    "Configurable Params: each indicator has a settings dialog (period, source, color, thickness)",
    "Performance: compute indicators in Web Worker to avoid blocking main thread on large datasets"],
   ["Prompt: 'Build indicator engine computing 20 technical indicators from OHLCV data. Each returns array of values aligned with candles.'",
    "Prompt: 'Implement Fibonacci retracement drawing tool: click two points, auto-draw levels at 23.6%, 38.2%, 50%, 61.8%, 78.6%.'",
    "Prompt: 'Create multi-timeframe chart view: 2x2 grid with synced crosshairs across 1m, 5m, 1h, 1D timeframes.'",
    "Prompt: 'Write IndicatorPanel sidebar: searchable list, click to add, configure params via dialog, toggle visibility.'",
    "Prompt: 'Move indicator computation to Web Worker for non-blocking calculation on 10K+ candle datasets.'"],
   "Too many indicators clutters the chart and slows rendering. Mitigation: max 5 active indicators, performance warning at 10K+ candles, lazy-compute off-screen indicators.",
   "20+ indicators available. Drawing tools functional. Multi-timeframe view with synced crosshairs. Indicators computed in Web Worker."
)

_d(25, "Options Workstation Enhancement",
   "Upgrade options workstation with advanced features: strategy builder, risk/reward visualizer, Greeks surface, chain filtering, and one-click spread construction.",
   ["cd frontend && cat src/features/options/ -la",
    "wc -l src/features/options/*.tsx",
    "cat src/features/options/OptionsChain.tsx | head -40",
    "grep -rn 'greek\\|delta\\|gamma\\|theta\\|vega' src/features/options/ | wc -l",
    "cat phase1/services/options/ -la",
    "wc -l phase1/services/options/*.py",
    "python3 -c \\"from phase1.services.options.tradier_provider import TradierOptionsProvider; print('Provider OK')\\"",
    "python3 -c \\"spreads=['vertical','iron_condor','butterfly','calendar','straddle','strangle','ratio']; print(f'{len(spreads)} spread types')\\""],
   ["frontend/src/features/options/StrategyBuilder.tsx (new: visual drag-and-drop spread construction)",
    "frontend/src/features/options/RiskRewardChart.tsx (new: P&L diagram at expiration with breakeven markers)",
    "frontend/src/features/options/GreeksSurface.tsx (new: 3D surface plot of Greeks across strikes and expirations)",
    "frontend/src/features/options/ChainFilter.tsx (new: filter by moneyness, DTE range, volume, OI, IV percentile)",
    "frontend/src/features/options/SpreadPresets.tsx (new: one-click Iron Condor, Vertical, Butterfly presets)",
    "frontend/src/features/options/PriceEstimator.tsx (new: estimate option price change for given underlying move)",
    "phase1/services/options/spread_analyzer.py (new: compute max profit, max loss, breakeven, POP for any spread)",
    "phase1/services/options/greeks_surface.py (new: compute Greeks across strike x expiration grid)",
    "phase1/services/api/options_routes.py (update: add spread analysis, Greeks surface, strategy builder endpoints)",
    "phase1/tests/unit/test_spread_analyzer.py (new: IC, vertical, butterfly max profit/loss against textbook values)",
    "frontend/tests/unit/RiskRewardChart.test.tsx (new: correct breakeven display, P&L curve shape)"],
   ["Strategy Builder: drag legs onto chart to construct spreads, auto-compute risk/reward/breakeven",
    "Risk/Reward Visualization: P&L at expiration as line chart, fill green above breakeven, red below",
    "Greeks Surface: 3D Plotly surface showing delta/gamma/theta/vega across strike x DTE matrix",
    "Chain Filtering: multi-criteria filter (DTE 20-45, delta 0.15-0.30, volume>100, OI>500)",
    "Spread Presets: one-click IC with auto-selected strikes based on delta targets and width preferences",
    "What-If Analysis: slider to see how P&L changes with underlying price, IV, and time changes"],
   ["Prompt: 'Build visual strategy builder where users drag call/put legs onto a chart to construct multi-leg spreads.'",
    "Prompt: 'Create P&L at expiration chart for any spread: compute payoff across price range, mark breakevens and max profit/loss.'",
    "Prompt: 'Write 3D Greeks surface using Plotly: delta across strikes (x-axis) and expirations (y) with color for magnitude.'",
    "Prompt: 'Implement chain filter component: sliders for DTE range, delta range, checkboxes for volume/OI minimums.'",
    "Prompt: 'Write spread_analyzer.py computing max profit, max loss, breakeven prices, probability of profit for any spread.'"],
   "Complex options calculations can be wrong and cause significant losses. Mitigation: validate all spread calculations against Black-Scholes textbook examples. Add sanity check warnings for unusual spreads.",
   "Options workstation has strategy builder, P&L chart, Greeks surface, chain filtering. All spread calculations validated against textbook."
)

_d(26, "Risk Dashboard with Real-Time Portfolio Greeks",
   "Build comprehensive risk dashboard showing portfolio-level Greeks, sector exposure, correlation matrix, VaR, stress test scenarios, and concentration warnings.",
   ["grep -rn 'risk\\|var\\|exposure\\|concentration' phase1/services/ | wc -l",
    "cat phase1/services/risk_desk/ -la",
    "wc -l phase1/services/risk_desk/*.py",
    "python3 -c \\"import numpy as np; positions=5; deltas=np.random.uniform(-0.3,0.3,positions); portfolio_delta=deltas.sum(); print(f'Portfolio delta: {portfolio_delta:.3f}')\\"",
    "python3 -c \\"import numpy as np; returns=np.random.normal(0,0.02,252); var_95=np.percentile(returns,5); print(f'VaR 95%: {var_95:.4f}')\\"",
    "cat phase1/services/risk_desk/risk_engine.py | head -30",
    "python3 -c \\"sectors={'Tech':0.4,'Finance':0.25,'Health':0.2,'Energy':0.15}; max_sector=max(sectors.values()); print(f'Max sector: {max_sector:.0%}')\\"",
    "grep -rn 'stress.test\\|scenario' phase1/services/ | wc -l"],
   ["phase1/services/risk_desk/portfolio_greeks.py (new: aggregate Greek exposure across all positions)",
    "phase1/services/risk_desk/sector_exposure.py (new: compute sector allocation and concentration metrics)",
    "phase1/services/risk_desk/correlation_matrix.py (new: compute and display position correlation matrix)",
    "phase1/services/risk_desk/var_calculator.py (new: historical VaR, parametric VaR, MC VaR at 95% and 99%)",
    "phase1/services/risk_desk/stress_tester.py (new: run scenarios: market -10%, VIX spike, sector crash, rate hike)",
    "phase1/services/risk_desk/concentration_alerts.py (new: warn if single position >15%, sector >40%, correlation >0.7)",
    "phase1/services/api/risk_routes.py (new: GET /risk/greeks, /risk/var, /risk/stress, /risk/exposure, /risk/alerts)",
    "frontend/src/features/risk/RiskDashboard.tsx (new: multi-panel risk view with all risk metrics)",
    "frontend/src/features/risk/GreeksGauge.tsx (new: gauge widgets for portfolio delta, gamma, theta, vega)",
    "frontend/src/features/risk/StressTestTable.tsx (new: scenario table showing portfolio impact per scenario)",
    "phase1/tests/unit/test_portfolio_greeks.py (new: aggregation of long/short, call/put Greeks across positions)",
    "phase1/tests/unit/test_var_calculator.py (new: VaR computation against known distribution)"],
   ["Portfolio Greeks Aggregation: sum deltas, gammas, thetas, vegas across all positions (sign-aware for long/short)",
    "VaR Methods: historical (last 252 days), parametric (assume normal), Monte Carlo (10K portfolio paths)",
    "Stress Scenarios: market -5/-10/-20%, VIX +50/+100%, sector rotation, rate +100bp, flash crash",
    "Concentration Limits: single position <15% of account, single sector <40%, no two positions >0.7 correlation",
    "Real-Time Updates: Greeks recalculated every time positions or market data change via WebSocket",
    "Risk Budget Tracking: gauge showing used risk vs total risk budget, warning at 80%, block at 100%"],
   ["Prompt: 'Compute portfolio-level Greeks by summing position Greeks (sign-aware for long/short, call/put).'",
    "Prompt: 'Implement historical VaR: use last 252 daily P&L, compute 5th percentile loss.'",
    "Prompt: 'Create stress test scenarios: SPY -10%, VIX +50%, Fed rate +100bp. Compute portfolio impact for each.'",
    "Prompt: 'Build risk dashboard with gauge widgets for delta/gamma/theta/vega and sector exposure pie chart.'",
    "Prompt: 'Write concentration alert system: flag positions exceeding 15% of account or sectors exceeding 40%.'"],
   "Risk models based on normal distribution underestimate tail events. Mitigation: use historical VaR alongside parametric, include stress tests for black swan events.",
   "Risk dashboard shows portfolio Greeks, VaR, sector exposure, correlation matrix. Concentration alerts fire at configured thresholds. Stress test results displayed."
)

_d(27, "CI/CD Pipeline: GitHub Actions with Full Test Matrix",
   "Set up comprehensive GitHub Actions pipeline: lint, typecheck, unit tests, integration tests, build, Docker image push, and deployment staging.",
   ["cat .github/workflows/ -la 2>/dev/null || mkdir -p .github/workflows",
    "cat .github/workflows/test.yml 2>/dev/null || echo 'no test workflow'",
    "python3 -c \\"steps=['lint','typecheck','unit_test','integration_test','build_backend','build_frontend','docker_build','docker_push','deploy_staging']; print(f'{len(steps)} CI steps')\\"",
    "pip install ruff black isort",
    "ruff check phase1/services/ --statistics 2>&1 | tail -10",
    "black --check phase1/services/ 2>&1 | tail -5",
    "isort --check-only phase1/services/ 2>&1 | tail -5",
    "cd frontend && npx eslint src/ --max-warnings 0 2>&1 | tail -10",
    "cat Makefile | head -20 2>/dev/null || echo 'no Makefile'"],
   [".github/workflows/ci.yml (new: full CI pipeline with matrix strategy for Python 3.11/3.12 and Node 20/22)",
    ".github/workflows/deploy.yml (new: deploy to staging on merge to main, production on tag)",
    ".github/workflows/codeql.yml (new: CodeQL security analysis on every PR)",
    "Makefile (new: lint, format, typecheck, test, test-integration, build, docker-build targets)",
    "phase1/.ruff.toml (new: ruff config with Python 3.11 target, line-length 100, selected rules)",
    "phase1/pyproject.toml (update: black config, isort config, ruff config sections)",
    "frontend/.eslintrc.cjs (update: strict TypeScript rules, no-any, no-unused-vars as error)",
    "scripts/ci_gate.sh (new: run all checks in order, fail fast on first error, report summary)",
    ".github/PULL_REQUEST_TEMPLATE.md (new: PR checklist: tests pass, types check, no lint errors, coverage maintained)",
    "phase1/tests/conftest.py (update: CI environment detection, test DB config, artifact preservation)",
    ".github/workflows/release.yml (new: semantic versioning, changelog generation, GitHub release creation)"],
   ["Matrix Strategy: test on Python 3.11+3.12 x Node 20+22 to catch compatibility issues early",
    "Fail Fast: lint -> typecheck -> unit test -> integration test (each step only runs if previous passes)",
    "Artifact Preservation: upload test results, coverage reports, and Docker images as GitHub artifacts",
    "Cache Strategy: pip cache and npm cache across runs for 3x faster CI (5min instead of 15min)",
    "Branch Protection: main branch requires passing CI, code review, and minimum coverage threshold",
    "Security Scanning: CodeQL on every PR, Dependabot for dependency updates, secret scanning enabled"],
   ["Prompt: 'Write GitHub Actions CI workflow: lint, typecheck, unit test, integration test, build, with Python/Node matrix.'",
    "Prompt: 'Create Makefile with: lint (ruff+eslint), format (black+prettier), test (pytest+vitest), build (docker compose build) targets.'",
    "Prompt: 'Configure ruff for Python 3.11: line-length 100, enable pyflakes, pycodestyle, isort, pydocstyle rules.'",
    "Prompt: 'Write PR template with checklist: tests pass, mypy clean, lint clean, coverage >= 85%, no TODOs added.'",
    "Prompt: 'Create deploy workflow: on merge to main deploy to staging, on tag vX.Y.Z deploy to production.'"],
   "CI that takes too long (>15min) slows development velocity. Mitigation: parallel jobs, aggressive caching, split unit/integration into separate jobs. Target: full CI in < 8 minutes.",
   "CI pipeline with 6 stages running on every push. Matrix tests Python 3.11+3.12. All checks pass. PR template enforces quality gates."
)

_d(28, "End-to-End Testing with Playwright",
   "Write comprehensive E2E tests: login flow, dashboard widget interaction, chart loading, autopilot trigger, position management, options chain, and kill switch.",
   ["cd frontend && npx playwright install",
    "npx playwright test --list 2>&1 | head -20",
    "cat playwright.config.ts | head -30",
    "cat tests/e2e/ -la 2>/dev/null || ls e2e/ 2>/dev/null || echo 'no e2e dir'",
    "npx playwright test --project=chromium 2>&1 | tail -20",
    "python3 -c \\"flows=['login','dashboard_load','widget_add_remove','chart_indicator','autopilot_trigger','position_close','options_chain','kill_switch','scheduler_view','settings_save']; print(f'{len(flows)} E2E flows')\\"",
    "grep -rn 'data-testid' src/ | wc -l",
    "cat src/features/layout/views/UnifiedDashboardView.tsx | grep -c 'data-testid'"],
   ["frontend/tests/e2e/dashboard.spec.ts (new: load dashboard, verify widgets, add/remove widget, resize)",
    "frontend/tests/e2e/chart.spec.ts (new: load chart, add indicator, draw trendline, switch timeframe)",
    "frontend/tests/e2e/autopilot.spec.ts (new: view status, trigger dry run, verify results display)",
    "frontend/tests/e2e/positions.spec.ts (new: view positions, check P&L display, close position flow)",
    "frontend/tests/e2e/options.spec.ts (new: load chain, filter strikes, build spread, view risk/reward)",
    "frontend/tests/e2e/killswitch.spec.ts (new: view status, trigger manual override, verify level change)",
    "frontend/tests/e2e/scheduler.spec.ts (new: view jobs, trigger manual job, verify next run update)",
    "frontend/tests/e2e/settings.spec.ts (new: change config, save, reload, verify persistence)",
    "frontend/playwright.config.ts (update: chromium+firefox+webkit, screenshot on failure, video on retry)",
    "frontend/tests/e2e/fixtures.ts (new: shared test helpers, mock API responses, test data)",
    "frontend/src/**/*.tsx (update: add data-testid attributes to all interactive elements)"],
   ["E2E Test Strategy: test user flows not implementation details - if UI changes, tests should still pass",
    "Page Object Model: LoginPage, DashboardPage, ChartPage, AutopilotPage classes encapsulate selectors",
    "API Mocking: use Playwright route interception to mock backend responses for deterministic tests",
    "Visual Regression: screenshot comparison on key pages to catch unintended visual changes",
    "Multi-Browser: test on Chromium, Firefox, WebKit to catch browser-specific rendering issues",
    "CI Integration: E2E tests run in headless mode on GitHub Actions with video recording on failure"],
   ["Prompt: 'Write E2E test for dashboard: load page, verify 5 default widgets, add new widget from catalog, remove a widget, verify persistence.'",
    "Prompt: 'Create Page Object Model for DashboardPage: locators for all widgets, methods for add/remove/resize/configure.'",
    "Prompt: 'Write E2E test for autopilot: navigate to autopilot panel, trigger dry run, wait for results, verify candidates displayed.'",
    "Prompt: 'Set up Playwright config with 3 browsers, screenshot on failure, video on retry, 30s timeout.'",
    "Prompt: 'Add data-testid attributes to all interactive elements across the frontend codebase for E2E test targeting.'"],
   "E2E tests are slow and flaky by nature. Mitigation: run E2E only on PRs to main (not on every push), use API mocking for determinism, retry failed tests once.",
   "10+ E2E tests covering all major user flows. Tests pass on Chromium, Firefox, WebKit. Screenshots on failure. data-testid on all interactive elements."
)

_d(29, "Configuration Management: Environment Profiles and Feature Flags",
   "Build configuration management system with dev/staging/prod profiles, feature flags with runtime toggle, and encrypted secrets management.",
   ["pip install python-dotenv pydantic-settings dynaconf",
    "cat keys.env | wc -l",
    "cat phase1/services/config.py | head -40",
    "grep -rn 'env\\|settings\\|config' phase1/services/config.py | wc -l",
    "python3 -c \\"from pydantic_settings import BaseSettings; print('pydantic-settings ready')\\"",
    "python3 -c \\"profiles=['development','staging','production','testing']; print(f'{len(profiles)} profiles')\\"",
    "env | grep -i 'apex\\|database\\|redis\\|api_key' 2>/dev/null | wc -l",
    "grep -rn 'feature.flag\\|toggle\\|experiment' phase1/services/ | wc -l"],
   ["phase1/services/config/settings.py (new: Pydantic Settings with typed env vars, defaults, validation)",
    "phase1/services/config/profiles.py (new: dev/staging/prod profiles with overrides per environment)",
    "phase1/services/config/feature_flags.py (new: runtime feature flags with JSON config and admin toggle)",
    "phase1/services/config/secrets.py (new: encrypted secrets loading, support for AWS SSM / GCP Secret Manager)",
    "phase1/services/api/config_routes.py (new: GET /config (non-sensitive), POST /config/flags/{name}/toggle)",
    "config/development.env (new: dev defaults, localhost URLs, debug mode, paper broker, verbose logging)",
    "config/staging.env (new: staging URLs, paper broker, reduced logging, real market data)",
    "config/production.env (new: prod URLs, live broker, minimal logging, all safety checks enabled)",
    "config/testing.env (new: test DB, mock brokers, deterministic seeds, all features enabled)",
    "frontend/src/features/admin/FeatureFlagsPanel.tsx (new: toggle table for all feature flags with descriptions)",
    "phase1/tests/unit/test_config.py (new: profile loading, flag toggling, missing env var handling, type validation)"],
   ["Typed Configuration: all settings are Pydantic models with types, defaults, and validation rules",
    "Profile Precedence: defaults -> profile file -> environment variables -> CLI args (later overrides earlier)",
    "Feature Flags: JSON-backed with name, description, enabled, rollout_percentage, user_whitelist",
    "Secret Rotation: encrypted at rest, loaded once on startup, rotatable without restart via admin endpoint",
    "Config Validation: fail fast on startup if required config is missing or invalid",
    "Feature Flag Patterns: use_monte_carlo, enable_sentiment, use_redis_cache, enable_live_trading"],
   ["Prompt: 'Create Pydantic Settings class loading config from .env file with typed fields, defaults, and validation.'",
    "Prompt: 'Implement feature flag system with JSON storage, runtime toggle via admin API, rollout percentage support.'",
    "Prompt: 'Write config profiles for dev/staging/prod with appropriate defaults for each environment.'",
    "Prompt: 'Build FeatureFlagsPanel: table of all flags with toggle switches, descriptions, and last-changed timestamp.'",
    "Prompt: 'Write fail-fast config validation: on startup, check all required vars present, types correct, values in range.'"],
   "Feature flags left in permanently become tech debt. Mitigation: each flag has an expiry date, weekly review of active flags, auto-alert on expired flags.",
   "Config system with 4 profiles. Feature flags toggleable at runtime. Fail-fast validation on startup. FeatureFlagsPanel in admin UI."
)

_d(30, "Documentation: Architecture Decision Records and API Docs",
   "Write comprehensive documentation: ADRs for all major decisions, OpenAPI spec auto-generated from code, deployment guide, and contributor onboarding guide.",
   ["pip install mkdocs mkdocs-material mkdocstrings[python]",
    "python3 -c \\"from fastapi.openapi.utils import get_openapi; print('OpenAPI generator ready')\\"",
    "curl -s http://localhost:8000/openapi.json | python3 -m json.tool | head -20",
    "find docs/ -name '*.md' | wc -l 2>/dev/null || echo 'no docs dir'",
    "mkdir -p docs/adr docs/api docs/guides",
    "python3 -c \\"adrs=['001-python-fastapi','002-react-vite','003-llm-hybrid-selector','004-sqlite-to-postgres','005-redis-caching','006-circuit-breakers','007-graduated-killswitch','008-widget-dashboard','009-apscheduler','010-monte-carlo']; print(f'{len(adrs)} ADRs')\\"",
    "cat README.md | wc -l",
    "grep -rn 'docstring\\|Args:\\|Returns:\\|Raises:' phase1/services/autopilot/unified_engine.py | wc -l"],
   ["docs/adr/001-fastapi-over-flask.md (new: rationale for FastAPI, async support, Pydantic integration)",
    "docs/adr/002-llm-hybrid-selector.md (new: why Groq+Gemini, deterministic fallback, cost analysis)",
    "docs/adr/003-sqlite-to-postgres.md (new: scale limitations, migration strategy, rollback plan)",
    "docs/adr/004-redis-caching-strategy.md (new: TTL choices, eviction policy, fallback behavior)",
    "docs/adr/005-graduated-killswitch.md (new: 5 levels vs binary, auto-recovery, incident response)",
    "docs/api/openapi_spec.json (generate: from FastAPI app, includes all endpoints with schemas)",
    "docs/guides/quickstart.md (new: clone, install, configure, run in 5 minutes)",
    "docs/guides/architecture.md (new: system overview diagram, service dependencies, data flow)",
    "docs/guides/deployment.md (new: Docker Compose deployment, env config, monitoring setup)",
    "docs/guides/contributing.md (new: code style, PR process, testing requirements, branch naming)",
    "mkdocs.yml (new: MkDocs Material config with nav structure, search, code highlighting)",
    "phase1/services/autopilot/unified_engine.py (update: add comprehensive docstrings to all public methods)"],
   ["ADR Format: Title, Status, Context, Decision, Consequences, Alternatives Considered",
    "Auto-Generated API Docs: FastAPI produces OpenAPI spec from type hints, Swagger UI at /docs",
    "MkDocs Material: beautiful documentation site with search, dark mode, code highlighting",
    "Architecture Diagrams: Mermaid flowcharts embedded in markdown for automatic rendering",
    "Living Documentation: docs updated as part of every PR (enforced via PR template checklist)",
    "Docstring Standard: Google-style docstrings with Args, Returns, Raises, Examples sections"],
   ["Prompt: 'Write ADR for choosing FastAPI over Flask: context (async needed), decision, consequences, alternatives.'",
    "Prompt: 'Generate comprehensive docstrings for all public methods in unified_engine.py using Google docstring format.'",
    "Prompt: 'Create MkDocs config with Material theme, nav structure for ADRs/API/Guides, search enabled.'",
    "Prompt: 'Write quickstart guide: prerequisites, clone, install deps, configure env, start services, verify health.'",
    "Prompt: 'Draw Mermaid architecture diagram showing: Frontend -> API -> Services -> DB/Redis/Brokers/LLMs flow.'"],
   "Documentation that diverges from code is worse than no docs. Mitigation: auto-generate API docs from code, docstring linting in CI, docs review in PR checklist.",
   "10 ADRs written. OpenAPI spec auto-generated. MkDocs site builds. Quickstart, architecture, deployment, contributing guides complete."
)
'''
