"""Days 31-90 content. Days 31-60: Advanced autopilot. Days 61-90: Production hardening."""

CHUNK = '''
_d(31, "Autopilot Config Hot-Reload and A/B Testing Framework",
   "Implement live config reload without restart. Build A/B testing framework to compare strategy variants, LLM prompts, and scoring weights in parallel.",
   ["python3 -c \\"import watchdog; print('watchdog ready')\\" 2>/dev/null || pip install watchdog",
    "grep -rn 'reload\\|hot.reload\\|watch' phase1/services/ | wc -l",
    "cat phase1/services/autopilot/config.py | wc -l",
    "python3 -c \\"import json; ab_test={'name':'scoring_v2','variants':['control','treatment'],'allocation':[0.5,0.5],'metric':'sharpe'}; print(json.dumps(ab_test))\\"",
    "grep -rn 'experiment\\|variant\\|ab.test' phase1/services/ | wc -l",
    "python3 -c \\"from scipy import stats; t,p=stats.ttest_ind([1,2,3,4,5],[2,3,4,5,6]); print(f't={t:.3f}, p={p:.3f}')\\"",
    "cat phase1/services/autopilot/unified_engine.py | grep -c 'config'",
    "python3 -c \\"import hashlib; user_bucket=int(hashlib.md5(b'user123').hexdigest(),16)%100; print(f'Bucket: {user_bucket}')\\""],
   ["phase1/services/config/hot_reload.py (new: file watcher that reloads config on change, validates before applying)",
    "phase1/services/experiments/ab_framework.py (new: A/B test definition, user bucketing, metric collection)",
    "phase1/services/experiments/experiment_store.py (new: persist experiment configs and results in DB)",
    "phase1/services/experiments/analyzer.py (new: statistical significance testing, confidence intervals, winner detection)",
    "phase1/services/experiments/decorator.py (new: @experiment('test_name') decorator for variant routing)",
    "phase1/services/autopilot/config.py (update: support hot-reload, version tracking, rollback)",
    "phase1/services/autopilot/unified_engine.py (update: check experiment assignments before strategy selection)",
    "phase1/services/api/experiments_routes.py (new: CRUD experiments, view results, declare winner)",
    "frontend/src/features/admin/ExperimentsPanel.tsx (new: create/view/analyze experiments with charts)",
    "phase1/tests/unit/test_hot_reload.py (new: config change detection, validation, rollback on invalid)",
    "phase1/tests/unit/test_ab_framework.py (new: consistent bucketing, metric collection, significance test)"],
   ["Hot Reload: file watcher -> validate new config -> swap atomically -> log change with diff",
    "A/B Bucketing: deterministic hash-based assignment ensures consistent variant per user/session",
    "Experiment Lifecycle: DRAFT -> RUNNING -> ANALYZING -> COMPLETED with minimum sample size gates",
    "Statistical Rigor: require p < 0.05 and minimum 30 observations per variant before declaring winner",
    "Guard Rails: experiments auto-stop if any variant performs 3x worse than control (early stopping)",
    "Config Versioning: every config change creates a new version, can rollback to any previous version"],
   ["Prompt: 'Implement config hot-reload using watchdog: detect file changes, validate, apply atomically, log diff.'",
    "Prompt: 'Build A/B testing framework with hash-based bucketing, metric collection, and t-test significance analysis.'",
    "Prompt: 'Write @experiment decorator that routes to variant function based on user bucket assignment.'",
    "Prompt: 'Create ExperimentsPanel UI: create experiment, set variants and allocation, view results with confidence intervals.'",
    "Prompt: 'Implement early stopping: auto-halt experiment if variant P&L is 3x worse than control after 30 samples.'"],
   "A/B tests with real money carry financial risk. Mitigation: start all experiments in paper trading, graduate to live only after statistical significance in paper.",
   "Config reloads without restart. A/B framework running with experiment tracking. Statistical significance testing works. Early stopping guard rails active."
)

_d(32, "Advanced LLM Prompt Engineering and Chain-of-Thought",
   "Rewrite all LLM prompts with chain-of-thought reasoning, few-shot examples, structured output format, and self-consistency checking for higher accuracy.",
   ["cat phase1/services/llm/prompts/ -la 2>/dev/null || ls phase1/services/autopilot/prompt_registry.py",
    "cat phase1/services/autopilot/prompt_registry.py | wc -l",
    "grep -rn 'prompt\\|system_message\\|user_message' phase1/services/autopilot/ | wc -l",
    "python3 -c \\"prompt_types=['selection','validation','exit_decision','risk_assessment','market_analysis']; print(f'{len(prompt_types)} prompt types')\\"",
    "python3 -c \\"import tiktoken; enc=tiktoken.encoding_for_model('gpt-4'); tokens=enc.encode('Hello world'); print(f'{len(tokens)} tokens')\\" 2>/dev/null || echo 'tiktoken not installed'",
    "pip install tiktoken",
    "cat phase1/services/autopilot/hybrid_selector.py | grep -A30 'prompt'",
    "python3 -c \\"cot_steps=['1. Market regime','2. Sector analysis','3. IV environment','4. Candidate screening','5. Risk assessment','6. Final selection']; print(f'{len(cot_steps)} CoT steps')\\""],
   ["phase1/services/llm/prompts/selection_v2.py (new: CoT prompt with 6-step reasoning, few-shot examples, JSON output)",
    "phase1/services/llm/prompts/validation_v2.py (new: adversarial validation prompt challenging selection reasoning)",
    "phase1/services/llm/prompts/exit_decision_v2.py (new: position exit reasoning with market context and Greeks)",
    "phase1/services/llm/prompts/market_analysis_v2.py (new: daily market regime classification prompt)",
    "phase1/services/llm/prompts/risk_assessment_v2.py (new: portfolio risk analysis with scenario consideration)",
    "phase1/services/llm/self_consistency.py (new: run same prompt N times, majority vote on action)",
    "phase1/services/llm/prompt_versioning.py (new: version control prompts, A/B test prompt variants)",
    "phase1/services/llm/token_counter.py (new: count tokens before sending, enforce budget per prompt)",
    "phase1/services/autopilot/hybrid_selector.py (update: use v2 prompts with CoT and self-consistency)",
    "phase1/tests/unit/test_prompt_templates.py (new: verify prompts render correctly with all variable combinations)",
    "phase1/tests/unit/test_self_consistency.py (new: 3-of-5 majority vote, tie-breaking logic)"],
   ["Chain-of-Thought: force LLM to reason step-by-step: market regime -> sector -> IV -> candidates -> risk -> selection",
    "Few-Shot Examples: include 3 examples of correct reasoning for each prompt type (positive + negative)",
    "Structured Output: JSON schema enforced via system message + output validation",
    "Self-Consistency: run selection prompt 3 times, take majority vote for higher accuracy (2-of-3 agreement)",
    "Token Budget: max 2000 tokens input, 500 tokens output per prompt to control costs",
    "Prompt Versioning: each prompt has a version, linked to A/B test results for continuous improvement"],
   ["Prompt: 'Rewrite the selection prompt with 6-step chain-of-thought: market regime, sector, IV environment, screening, risk, selection.'",
    "Prompt: 'Create 3 few-shot examples for the selection prompt: one bullish setup, one bearish, one neutral market.'",
    "Prompt: 'Implement self-consistency: run selection 3 times, extract actions, take majority vote with confidence adjustment.'",
    "Prompt: 'Write adversarial validation prompt that challenges the selections reasoning and identifies logical flaws.'",
    "Prompt: 'Build prompt versioning system: store prompts with versions, link to experiment results, enable rollback.'"],
   "Longer prompts cost more tokens and are slower. Mitigation: token budget enforcement, prompt compression for frequently-used templates, cache identical prompt results.",
   "All prompts rewritten with CoT reasoning. Self-consistency runs 3x. Few-shot examples included. Token budget enforced at 2000 input / 500 output."
)

_d(33, "Market Regime Detection (Bull/Bear/Sideways/Volatile)",
   "Build market regime classifier using technical signals, volatility clustering, and trend strength to adapt strategy selection and position sizing per regime.",
   ["python3 -c \\"import numpy as np; r=np.random.normal(0.001,0.015,60); trend=np.polyfit(range(60),np.cumsum(r),1)[0]; print(f'Trend slope: {trend:.4f}')\\"",
    "python3 -c \\"import numpy as np; vix=np.random.uniform(12,35,30); regime='HIGH_VOL' if vix[-1]>25 else 'NORMAL'; print(f'VIX: {vix[-1]:.1f}, Regime: {regime}')\\"",
    "grep -rn 'regime\\|bull\\|bear\\|sideways' phase1/services/ | wc -l",
    "python3 -c \\"from scipy.stats import hurst=0; import numpy as np; series=np.cumsum(np.random.randn(500)); print('Series generated')\\"",
    "cat phase1/services/forecasting/ -la 2>/dev/null || echo 'forecasting exists'",
    "python3 -c \\"signals={'sma_50_200':'BULL','vix_level':'NORMAL','adx_strength':'TRENDING','put_call_ratio':'NEUTRAL'}; print(signals)\\"",
    "python3 -c \\"import numpy as np; returns=np.random.normal(0,0.02,252); vol_20=np.std(returns[-20:])*np.sqrt(252); vol_60=np.std(returns[-60:])*np.sqrt(252); print(f'20d vol: {vol_20:.2%}, 60d vol: {vol_60:.2%}')\\""],
   ["phase1/services/regime/regime_detector.py (new: classify market as BULL/BEAR/SIDEWAYS/HIGH_VOL using composite signals)",
    "phase1/services/regime/trend_analyzer.py (new: SMA crossovers, ADX, linear regression slope for trend direction/strength)",
    "phase1/services/regime/volatility_regime.py (new: VIX level, realized vs implied vol, vol clustering detection)",
    "phase1/services/regime/breadth_indicators.py (new: advance/decline, new highs/lows, % above 200 SMA)",
    "phase1/services/regime/regime_history.py (new: store regime transitions with timestamps for backtesting)",
    "phase1/services/autopilot/unified_engine.py (update: fetch regime before strategy selection, adapt behavior)",
    "phase1/services/autopilot/scoring_weights.py (update: regime-dependent weight vectors per strategy)",
    "phase1/services/strategy/orchestrator.py (update: enable/disable strategies based on regime)"
    "frontend/src/features/autopilot/RegimeBadge.tsx (new: color-coded regime badge with confidence %)",
    "phase1/tests/unit/test_regime_detector.py (new: known market conditions -> expected regime classification)",
    "phase1/tests/unit/test_regime_adaptation.py (new: verify strategy weights change with regime)"],
   ["Composite Regime Score: weighted combination of trend (40%), volatility (30%), breadth (30%)",
    "Regime Persistence: require 3 consecutive days of new regime signal before switching (avoids whipsaws)",
    "Strategy Adaptation: BULL -> more directional plays, BEAR -> more hedging, SIDEWAYS -> more premium selling, HIGH_VOL -> reduce size",
    "Historical Context: store regime history for backtest validation (was regime detector correct historically?)",
    "Regime Transitions: track all transitions with market conditions for pattern analysis",
    "Confidence Level: regime output includes confidence 0-100%, low confidence -> use default weights"],
   ["Prompt: 'Build regime detector using: SMA 50/200 cross, ADX, VIX level, put/call ratio. Output BULL/BEAR/SIDEWAYS/HIGH_VOL with confidence.'",
    "Prompt: 'Write trend analyzer using SMA crossover, regression slope, and ADX strength classification.'",
    "Prompt: 'Implement volatility regime detection: VIX clustering, realized vs implied vol ratio, GARCH estimation.'",
    "Prompt: 'Create regime-dependent scoring weights: adjust IV rank, delta, POP weights based on current regime.'",
    "Prompt: 'Design RegimeBadge component: green BULL, red BEAR, yellow SIDEWAYS, purple HIGH_VOL with confidence %.'"],
   "Regime detector can lag behind rapid regime changes (flash crash). Mitigation: intraday regime check every 30 min, not just daily. VIX spike triggers immediate HIGH_VOL classification.",
   "Regime detector classifies market correctly. Strategy weights adapt per regime. Regime transitions logged. RegimeBadge displayed in dashboard."
)

_d(34, "Async Task Queue with Celery and Redis",
   "Implement Celery for long-running tasks: backtest execution, report generation, batch MC simulation, data ingestion. With retry, monitoring, and priority queues.",
   ["pip install celery[redis] flower",
    "python3 -c \\"import celery; print('Celery', celery.__version__)\\"",
    "python3 -c \\"from celery import Celery; app=Celery('apex',broker='redis://localhost:6379/1'); print('Celery app created')\\"",
    "grep -rn 'background\\|async.task\\|queue\\|celery' phase1/services/ | wc -l",
    "redis-cli SELECT 1 && redis-cli DBSIZE",
    "python3 -c \\"tasks=['run_backtest','generate_report','batch_monte_carlo','ingest_historical','retrain_model','send_notifications']; print(f'{len(tasks)} task types')\\"",
    "cat phase1/services/backtest_engine/run.py | head -20 2>/dev/null || echo 'no backtest run'",
    "pip install flower 2>/dev/null; echo 'flower monitoring ready'"],
   ["phase1/services/tasks/celery_app.py (new: Celery config with Redis broker, result backend, serializer)",
    "phase1/services/tasks/backtest_task.py (new: @task for async backtest execution with progress tracking)",
    "phase1/services/tasks/report_task.py (new: @task for monthly/weekly report PDF generation)",
    "phase1/services/tasks/simulation_task.py (new: @task for batch Monte Carlo across 50 candidates)",
    "phase1/services/tasks/ingestion_task.py (new: @task for historical data download and DB insertion)",
    "phase1/services/tasks/notification_task.py (new: @task for email/Discord/SMS notifications)",
    "phase1/services/tasks/celery_config.py (new: queue routing, priority levels, rate limits, retry policies)",
    "phase1/services/api/tasks_routes.py (new: POST /tasks/submit, GET /tasks/{id}/status, DELETE /tasks/{id}/cancel)",
    "frontend/src/features/admin/TaskMonitor.tsx (new: active tasks table with progress bars, cancel button)",
    "docker-compose.yml (update: add celery worker and beat services)",
    "phase1/tests/unit/test_celery_tasks.py (new: task submission, retry on failure, result retrieval)"],
   ["Queue Architecture: default, high_priority, batch queues with dedicated workers per queue",
    "Task States: PENDING -> STARTED -> PROGRESS(n%) -> SUCCESS/FAILURE with result storage",
    "Retry Policy: 3 retries with exponential backoff for transient failures, dead letter queue for permanent failures",
    "Progress Tracking: tasks emit progress events (20%, 40%, 60%, 80%, 100%) for frontend consumption",
    "Rate Limiting: max 5 concurrent backtests, max 10 concurrent MC sims to prevent resource exhaustion",
    "Flower Monitoring: web UI showing active workers, task history, success rate, avg duration"],
   ["Prompt: 'Set up Celery with Redis broker: define task for async backtest with progress tracking and result storage.'",
    "Prompt: 'Write batch MC simulation task: run 10K paths for 50 candidates in parallel, aggregate results, store in DB.'",
    "Prompt: 'Create task monitoring API: submit tasks, check status/progress, cancel running tasks, list recent tasks.'",
    "Prompt: 'Build TaskMonitor React component: table of active tasks with progress bars, status badges, cancel button.'",
    "Prompt: 'Configure Celery routing: backtests -> batch queue, notifications -> priority queue, reports -> default queue.'"],
   "Long-running tasks consuming all workers block real-time operations. Mitigation: separate queues for batch vs real-time, concurrency limits per queue, priority routing.",
   "Celery running with 3 queues. Backtests run async with progress. Reports generated in background. Flower monitoring active."
)

_d(35, "Discord Bot for Alerts and Remote Control",
   "Build Discord bot for real-time trade alerts, kill switch status, portfolio summary, and remote command execution with role-based permissions.",
   ["pip install discord.py aiohttp",
    "python3 -c \\"import discord; print('discord.py', discord.__version__)\\"",
    "grep -rn 'discord\\|notification\\|alert' phase1/services/ | wc -l",
    "python3 -c \\"commands=['!status','!positions','!pnl','!killswitch','!trigger','!config','!journal','!help']; print(f'{len(commands)} bot commands')\\"",
    "cat phase1/services/delivery/ -la 2>/dev/null || echo 'delivery dir exists'",
    "grep -rn 'webhook\\|notify' phase1/services/ | wc -l",
    "python3 -c \\"embed={'title':'Trade Alert','color':0x00ff00,'fields':[{'name':'Symbol','value':'AAPL'},{'name':'Action','value':'SELL PUT'},{'name':'P&L','value':'+$150'}]}; print(embed)\\"",
    "cat keys.env | grep -i 'discord' || echo 'no discord token in keys.env'"],
   ["phase1/services/discord/bot.py (new: async Discord bot with command handling, embed messages)",
    "phase1/services/discord/commands.py (new: !status, !positions, !pnl, !killswitch, !trigger, !config, !help)",
    "phase1/services/discord/alerts.py (new: auto-post trade entries, exits, kill switch changes, daily summary)",
    "phase1/services/discord/embeds.py (new: rich embed formatters for each alert type with colors and fields)",
    "phase1/services/discord/permissions.py (new: role-based command access: admin can trigger, viewer can only read)",
    "phase1/services/discord/channels.py (new: multi-channel routing: #trades, #alerts, #status, #commands)",
    "phase1/services/autopilot/unified_engine.py (update: emit Discord alerts on trade entry/exit/kill switch)",
    "phase1/services/api/discord_routes.py (new: POST /discord/test-alert, GET /discord/status)",
    "docker-compose.yml (update: add discord bot service)",
    "keys.env (update: DISCORD_BOT_TOKEN, DISCORD_GUILD_ID, DISCORD_ALERT_CHANNEL_ID)",
    "phase1/tests/unit/test_discord_bot.py (new: command parsing, embed formatting, permission check)"],
   ["Async Bot: runs alongside FastAPI app using asyncio, shares event bus for real-time alerts",
    "Embed Messages: rich formatting with colors (green=profit, red=loss), fields for structured data",
    "Channel Routing: trades to #trades, system alerts to #alerts, commands in #commands",
    "Role-Based Access: @admin role can trigger cycles, view config. @viewer role can only read status",
    "Rate Limiting: max 30 messages/minute to avoid Discord rate limits, queue and batch if needed",
    "Command Patterns: !status (system health), !pnl (daily P&L), !positions (current positions), !kill (kill switch status)"],
   ["Prompt: 'Build async Discord bot with command handling for: status, positions, pnl, killswitch, trigger, config.'",
    "Prompt: 'Create rich embed formatters for trade alerts: entry (green), exit (green/red based on P&L), kill switch (red).'",
    "Prompt: 'Implement role-based permissions: admin commands (trigger, config), viewer commands (status, positions, pnl).'",
    "Prompt: 'Write auto-alert system: on trade entry emit to #trades, on kill switch change emit to #alerts.'",
    "Prompt: 'Create !pnl command showing: daily P&L, weekly P&L, open positions, win rate as formatted embed.'"],
   "Discord bot with trade execution capability is a security risk. Mitigation: all execution commands require 2FA confirmation via reaction. Read-only by default.",
   "Discord bot running. Trade alerts auto-posted. !status, !positions, !pnl commands working. Role-based permissions active."
)

_d(36, "Data Ingestion Pipeline: Historical OHLCV and Fundamentals",
   "Build automated data ingestion: historical OHLCV from Alpaca, fundamental data from SEC EDGAR, earnings calendar, dividend data, all stored in PostgreSQL with validation.",
   ["pip install alpaca-py sec-edgar-downloader yfinance",
    "python3 -c \\"from alpaca.data import StockHistoricalDataClient; print('Alpaca data client ready')\\"",
    "python3 -c \\"import yfinance as yf; s=yf.Ticker('AAPL'); print('YF info:', list(s.info.keys())[:5])\\"",
    "python3 -c \\"symbols=['AAPL','MSFT','GOOGL','AMZN','TSLA','NVDA','META','SPY','QQQ','IWM']; print(f'{len(symbols)} symbols to ingest')\\"",
    "python3 -c \\"from datetime import datetime, timedelta; start=(datetime.now()-timedelta(days=365*3)).strftime('%Y-%m-%d'); print(f'Ingestion start: {start}')\\"",
    "grep -rn 'ingest\\|download\\|historical' phase1/services/ | wc -l",
    "cat phase1/services/ingestion/ -la 2>/dev/null || echo 'ingestion dir'",
    "python3 -c \\"import sqlite3; c=sqlite3.connect('phase1/phase1.db'); bars=c.execute('SELECT COUNT(*) FROM bars').fetchone()[0]; print(f'{bars} existing bars')\\""],
   ["phase1/services/ingestion/ohlcv_ingester.py (new: download daily/hourly/minute OHLCV from Alpaca, store in PG)",
    "phase1/services/ingestion/fundamentals_ingester.py (new: SEC EDGAR filings, quarterly financials, balance sheet)",
    "phase1/services/ingestion/earnings_calendar.py (new: upcoming earnings dates from yfinance/SEC for all watchlist symbols)",
    "phase1/services/ingestion/dividend_tracker.py (new: ex-dates, payment dates, yield history for dividend stocks)",
    "phase1/services/ingestion/data_validator.py (new: check for gaps, outliers, stale data, zero volume days)",
    "phase1/services/ingestion/backfill.py (new: detect gaps in historical data, auto-backfill from source)",
    "phase1/services/ingestion/scheduler.py (new: nightly ingestion job, weekly fundamentals refresh, pre-market update)",
    "phase1/services/database/models.py (update: add fundamentals, earnings, dividends tables)",
    "phase1/migrations/versions/002_add_fundamentals_tables.py (new: Alembic migration for new tables)",
    "phase1/services/api/data_routes.py (new: GET /data/bars/{symbol}, GET /data/fundamentals/{symbol}, POST /data/ingest)",
    "phase1/tests/unit/test_data_validator.py (new: gap detection, outlier flagging, stale data check)"],
   ["Ingestion Pipeline: Source -> Download -> Validate -> Transform -> Store -> Index in 5 stages",
    "Multi-Source Redundancy: Alpaca primary, yfinance fallback for OHLCV. SEC primary for fundamentals.",
    "Data Validation: check for missing dates, impossible prices (negative, >10x previous), zero volume anomalies",
    "Incremental Ingestion: only download data after last stored timestamp, never re-download existing data",
    "Storage Efficiency: OHLCV in partitioned bars table, fundamentals in normalized tables with quarterly snapshots",
    "Scheduling: daily bars at 6 PM ET (after market), fundamentals weekly on weekends, earnings calendar daily at 8 AM"],
   ["Prompt: 'Build OHLCV ingester: download from Alpaca for 50 symbols, validate, store in PG bars table with upsert logic.'",
    "Prompt: 'Write data validator: check for date gaps, price outliers (>3 sigma), zero volume days, stale data (>24h old).'",
    "Prompt: 'Create earnings calendar tracker: fetch upcoming earnings from yfinance/SEC, store dates, alert 7 days before.'",
    "Prompt: 'Implement incremental ingestion: query last stored timestamp, only download new data, upsert without duplicates.'",
    "Prompt: 'Write nightly ingestion scheduler: download daily bars at 6 PM ET, validate, store, log summary.'"],
   "Bad data in -> bad decisions out. Mitigation: every ingested row passes 5 validation checks. Quarantine suspicious data for manual review before using in autopilot.",
   "Ingestion pipeline downloads 50 symbols daily. Data validated with 5 checks. Fundamentals refreshed weekly. Earnings calendar maintained."
)

_d(37, "Portfolio Rebalancing Engine",
   "Build automated portfolio rebalancing: target allocation vs actual, drift detection, rebalance suggestions, tax-loss harvesting integration, and execution planning.",
   ["python3 -c \\"target={'SPY':0.40,'QQQ':0.30,'IWM':0.15,'TLT':0.10,'GLD':0.05}; actual={'SPY':0.45,'QQQ':0.25,'IWM':0.18,'TLT':0.08,'GLD':0.04}; drift={k:actual[k]-target[k] for k in target}; print('Drift:', drift)\\"",
    "grep -rn 'rebalanc\\|allocation\\|drift' phase1/services/ | wc -l",
    "cat phase1/services/portfolio/ -la 2>/dev/null || echo 'portfolio dir'",
    "python3 -c \\"import numpy as np; weights=np.array([0.45,0.25,0.18,0.08,0.04]); target=np.array([0.40,0.30,0.15,0.10,0.05]); drift=np.abs(weights-target).sum(); print(f'Total drift: {drift:.2%}')\\"",
    "python3 -c \\"threshold=0.05; drifts=[0.05,-0.05,0.03,-0.02,-0.01]; need_rebalance=any(abs(d)>threshold for d in drifts); print(f'Need rebalance: {need_rebalance}')\\"",
    "cat phase1/services/portfolio/optimizer.py | head -30 2>/dev/null || echo 'no optimizer'",
    "grep -rn 'tax.loss\\|harvest\\|wash.sale' phase1/services/ | wc -l"],
   ["phase1/services/portfolio/rebalancer.py (new: compute trades needed to reach target allocation)",
    "phase1/services/portfolio/drift_monitor.py (new: continuous drift tracking with configurable threshold alerts)",
    "phase1/services/portfolio/target_allocation.py (new: define target allocations per strategy with bands)",
    "phase1/services/portfolio/tax_loss_harvester.py (new: identify losing positions for tax-loss harvesting, wash sale awareness)",
    "phase1/services/portfolio/execution_planner.py (new: optimize trade sequence for minimum market impact)",
    "phase1/services/portfolio/rebalance_scheduler.py (new: auto-rebalance on drift >5%, monthly review, quarterly full rebalance)",
    "phase1/services/api/portfolio_routes.py (new: GET /portfolio/drift, POST /portfolio/rebalance, GET /portfolio/tax-loss)",
    "frontend/src/features/portfolio/RebalanceView.tsx (new: current vs target allocation chart, rebalance preview)",
    "frontend/src/features/portfolio/DriftGauge.tsx (new: gauge showing total portfolio drift from target)",
    "phase1/tests/unit/test_rebalancer.py (new: target vs actual -> correct trades, min trade threshold)",
    "phase1/tests/unit/test_tax_loss.py (new: identify harvesting candidates, verify wash sale 30-day rule)"],
   ["Drift-Based Rebalancing: only rebalance when any position drifts >5% from target (avoids unnecessary trading)",
    "Minimum Trade Size: dont rebalance positions where trade size < $500 (commission eats profit)",
    "Tax-Loss Harvesting: sell losing positions, replace with correlated substitute, obey 30-day wash sale rule",
    "Execution Planning: sequence trades to maintain risk budget at all times (sell over-weights before buying under-weights)",
    "Band Strategy: each allocation has inner band (ignore) and outer band (rebalance) for smoother adjustments",
    "Quarterly Review: full rebalance quarterly regardless of drift, align with strategy performance review"],
   ["Prompt: 'Build rebalancer: compute target vs actual allocation, calculate trades needed, respect minimum trade size and bands.'",
    "Prompt: 'Implement drift monitor: track allocation drift continuously, alert when any position exceeds 5% band.'",
    "Prompt: 'Write tax-loss harvester: identify positions with unrealized losses >$100, check wash sale eligibility, suggest harvesting trades.'",
    "Prompt: 'Create RebalanceView: side-by-side bar chart of current vs target allocation with preview of rebalancing trades.'",
    "Prompt: 'Write execution planner: order trades to maintain risk budget (close over-weights first, then open under-weights).'"],
   "Rebalancing during volatile markets can lock in losses. Mitigation: pause rebalancing during HIGH_VOL regime. Override requires admin confirmation.",
   "Rebalancer computes trades for target allocation. Drift monitor alerts at 5%. Tax-loss harvesting identifies candidates. Wash sale rule enforced."
)

_d(38, "Anomaly Detection for Market and System Health",
   "Build anomaly detector for: unusual price movements, volume spikes, API latency outliers, system resource anomalies. Alert and auto-throttle on detection.",
   ["pip install pyod adtk statsmodels",
    "python3 -c \\"from pyod.models.iforest import IForest; print('PyOD ready')\\"",
    "python3 -c \\"from adtk.detector import ThresholdAD; print('ADTK ready')\\"",
    "python3 -c \\"import numpy as np; data=np.random.normal(0,1,1000); data[500]=10; z_scores=np.abs((data-data.mean())/data.std()); anomalies=(z_scores>3).sum(); print(f'{anomalies} anomalies detected')\\"",
    "grep -rn 'anomal\\|outlier\\|spike' phase1/services/ | wc -l",
    "python3 -c \\"import psutil; cpu=psutil.cpu_percent(); mem=psutil.virtual_memory().percent; print(f'CPU: {cpu}%, MEM: {mem}%')\\"",
    "python3 -c \\"thresholds={'price_zscore':3.0,'volume_multiplier':5.0,'latency_p99_ms':2000,'cpu_pct':90,'memory_pct':85}; print(thresholds)\\""],
   ["phase1/services/anomaly/detector.py (new: unified anomaly detection engine with pluggable algorithms)",
    "phase1/services/anomaly/price_anomaly.py (new: detect unusual price movements using z-score and Isolation Forest)",
    "phase1/services/anomaly/volume_anomaly.py (new: detect volume spikes using rolling window comparison)",
    "phase1/services/anomaly/latency_anomaly.py (new: detect API latency outliers using p99 tracking)",
    "phase1/services/anomaly/system_health.py (new: monitor CPU, memory, disk, DB connections for anomalies)",
    "phase1/services/anomaly/auto_throttle.py (new: reduce trading activity when anomalies detected)",
    "phase1/services/anomaly/alert_manager.py (new: deduplicate alerts, rate limit notifications, escalation logic)",
    "phase1/services/api/anomaly_routes.py (new: GET /anomaly/status, GET /anomaly/history, POST /anomaly/acknowledge)",
    "frontend/src/features/monitoring/AnomalyTimeline.tsx (new: timeline of detected anomalies with severity badges)",
    "phase1/tests/unit/test_price_anomaly.py (new: inject known anomalies, verify detection rate >95%)",
    "phase1/tests/unit/test_auto_throttle.py (new: anomaly detected -> trading rate reduced -> recovery -> normal rate)"],
   ["Multi-Signal Anomaly Detection: price (z-score >3), volume (>5x avg), latency (>p99), system (CPU>90%)",
    "Isolation Forest: unsupervised ML for detecting multi-dimensional outliers in market data",
    "Auto-Throttle: on market anomaly, reduce trading to 50% capacity. On system anomaly, pause non-critical tasks.",
    "Alert Deduplication: same anomaly type within 15 minutes counts as one event (prevents alert fatigue)",
    "Escalation: 1st anomaly -> log, 2nd within 30min -> Discord alert, 3rd -> auto-throttle + email",
    "Historical Context: store all anomalies for pattern analysis (do anomalies cluster around earnings/FOMC?)"],
   ["Prompt: 'Build anomaly detector using z-score and Isolation Forest for price movements. Flag moves >3 sigma.'",
    "Prompt: 'Implement auto-throttle: on anomaly detection, reduce trading rate by 50% for 30 minutes, then gradually restore.'",
    "Prompt: 'Write alert deduplication: same anomaly type within 15 min = single event, escalate on repeated occurrence.'",
    "Prompt: 'Create AnomalyTimeline component: chronological list of anomalies with severity colors and acknowledgment buttons.'",
    "Prompt: 'Build system health monitor: track CPU, memory, disk, DB connections, alert on thresholds.'"],
   "False positive anomalies cause unnecessary throttling. Mitigation: tune thresholds on 30 days of historical data. Start conservative (high thresholds), tighten gradually.",
   "Anomaly detector running for price, volume, latency, system health. Auto-throttle activates on detection. Alert deduplication prevents fatigue."
)

_d(39, "Options Spread Management: Adjustments and Rolling",
   "Build automated spread adjustment logic: roll when tested, widen when IV drops, add hedge legs, and compute adjustment costs vs expected value.",
   ["python3 -c \\"spread={'short_strike':180,'long_strike':175,'premium':2.50,'max_loss':2.50,'delta':-0.25}; print(spread)\\"",
    "python3 -c \\"import numpy as np; short_delta_history=np.random.uniform(-0.35,-0.15,20); breached=(np.abs(short_delta_history)>0.30).sum(); print(f'Delta breached {breached} times out of {len(short_delta_history)}')\\"",
    "grep -rn 'roll\\|adjust\\|spread.*manage' phase1/services/ | wc -l",
    "cat phase1/services/options/ -la",
    "python3 -c \\"roll_cost=-0.50; remaining_credit=1.50; ev_of_roll=0.65*2.00-0.35*3.00; print(f'Roll cost: {roll_cost}, EV: {ev_of_roll:.2f}')\\"",
    "python3 -c \\"adjustments=['roll_out_time','roll_down_strike','roll_up_strike','add_hedge','close_tested_side','widen_spread']; print(f'{len(adjustments)} adjustment types')\\"",
    "cat phase1/services/autopilot/monitoring.py | grep -c 'adjust'",
    "grep -rn 'dte\\|expiration\\|days.to' phase1/services/options/ | wc -l"],
   ["phase1/services/options/spread_manager.py (new: monitor open spreads, detect adjustment triggers, execute adjustments)",
    "phase1/services/options/roll_engine.py (new: roll out in time, roll down/up in strike, roll and widen)",
    "phase1/services/options/adjustment_analyzer.py (new: compute EV of each possible adjustment vs doing nothing)",
    "phase1/services/options/hedge_calculator.py (new: calculate optimal hedge leg to reduce position risk)",
    "phase1/services/options/spread_pnl_tracker.py (new: track unrealized P&L per spread leg, total spread P&L)",
    "phase1/services/autopilot/monitoring.py (update: integrate spread manager for automated adjustments)",
    "phase1/services/api/spread_routes.py (new: GET /spreads/active, POST /spreads/{id}/roll, POST /spreads/{id}/adjust)",
    "frontend/src/features/options/SpreadManager.tsx (new: active spreads list with adjustment suggestions and P&L)",
    "frontend/src/features/options/AdjustmentPreview.tsx (new: preview adjustment with cost, new risk/reward, EV comparison)",
    "phase1/tests/unit/test_roll_engine.py (new: roll out 30 DTE, roll down strike, verify new position parameters)",
    "phase1/tests/unit/test_adjustment_analyzer.py (new: EV calculation for roll vs hold vs close)"],
   ["Adjustment Triggers: short delta >0.30, P&L >-50% of max loss, DTE <14, IV drop >20% from entry",
    "Roll Decision Matrix: if tested + DTE>14 -> roll out in time. If tested + DTE<14 -> close. If IV dropped -> widen.",
    "EV Analysis: for each adjustment option compute: P(profit)*profit - P(loss)*loss - adjustment_cost",
    "Partial Adjustments: close only the tested side of an IC, keep the untested side running",
    "Cost Tracking: log every adjustment cost, compare to holding original position for performance review",
    "Automation Levels: suggest-only (dashboard notification), semi-auto (require confirmation), full-auto (execute immediately)"],
   ["Prompt: 'Build spread manager: monitor open iron condors, detect when short strike is tested (delta >0.30).'",
    "Prompt: 'Implement roll engine: roll out puts/calls by 30 days, compute credit/debit of roll, update position.'",
    "Prompt: 'Write EV analyzer for adjustments: compare roll_out vs close vs add_hedge vs hold using MC simulation.'",
    "Prompt: 'Create SpreadManager component: list of active spreads with P&L, adjustment suggestions, and execute button.'",
    "Prompt: 'Write tests: IC with tested put side -> suggest roll out. IC at 50% profit -> suggest close.'"],
   "Automated adjustments can compound losses if adjustment triggers are too sensitive. Mitigation: minimum 2-hour cooldown between adjustments on same spread. Max 3 adjustments per spread lifetime.",
   "Spread manager monitors all open spreads. Adjustments suggested with EV analysis. Rolls execute correctly. Adjustment costs tracked."
)

_d(40, "Performance Attribution and Strategy Comparison",
   "Build performance attribution system decomposing returns into: strategy alpha, market beta, sector exposure, timing, and transaction costs. Compare strategies head-to-head.",
   ["python3 -c \\"import numpy as np; returns=np.random.normal(0.002,0.015,252); spy=np.random.normal(0.001,0.012,252); beta=np.cov(returns,spy)[0,1]/np.var(spy); alpha=(returns.mean()-beta*spy.mean())*252; print(f'Beta: {beta:.2f}, Alpha: {alpha:.2%}')\\"",
    "grep -rn 'attribution\\|alpha\\|beta\\|comparison' phase1/services/ | wc -l",
    "python3 -c \\"from scipy import stats; r1=np.random.normal(0.002,0.01,100); r2=np.random.normal(0.001,0.012,100); t,p=stats.ttest_ind(r1,r2); print(f't={t:.3f}, p={p:.3f}')\\"",
    "cat phase1/services/journal/ -la",
    "python3 -c \\"components=['strategy_alpha','market_beta','sector_exposure','timing','transaction_costs','slippage']; print(f'{len(components)} attribution components')\\"",
    "grep -rn 'benchmark\\|SPY\\|compare' phase1/services/ | wc -l",
    "python3 -c \\"from datetime import datetime, timedelta; periods={'week':7,'month':30,'quarter':90,'year':365}; print(periods)\\""],
   ["phase1/services/analytics/attribution_engine.py (new: Brinson-style attribution decomposing returns by source)",
    "phase1/services/analytics/strategy_comparison.py (new: head-to-head comparison with statistical significance testing)",
    "phase1/services/analytics/benchmark_tracker.py (new: track SPY, QQQ as benchmarks, compute relative performance)",
    "phase1/services/analytics/cost_analyzer.py (new: decompose transaction costs: commission, slippage, spread, market impact)",
    "phase1/services/analytics/time_period_performance.py (new: compute returns by day, week, month, quarter, year with annualization)",
    "phase1/services/analytics/drawdown_analysis.py (new: max drawdown, drawdown duration, recovery time, underwater chart)",
    "phase1/services/api/analytics_routes.py (new: GET /analytics/attribution, /analytics/compare, /analytics/drawdown)",
    "frontend/src/features/reports/AttributionChart.tsx (new: waterfall chart showing return decomposition)",
    "frontend/src/features/reports/StrategyComparison.tsx (new: side-by-side strategy metrics with significance indicator)",
    "phase1/tests/unit/test_attribution.py (new: known returns -> correct alpha/beta decomposition)",
    "phase1/tests/unit/test_strategy_comparison.py (new: compare two strategies, verify statistical test output)"],
   ["Brinson Attribution: decompose return into allocation effect (sector weight), selection effect (stock alpha), interaction",
    "CAPM Decomposition: return = alpha + beta*market_return + residual. Report alpha significance.",
    "Strategy Comparison: metrics table (Sharpe, Sortino, MaxDD, Win%, PF) with t-test for mean return difference",
    "Cost Analysis: total costs = commissions + slippage + spread + market impact. Track cost as % of gross profit.",
    "Benchmark-Relative: compute Information Ratio = (portfolio return - benchmark return) / tracking error",
    "Rolling Performance: rolling 30-day Sharpe, rolling beta, rolling alpha for temporal performance analysis"],
   ["Prompt: 'Implement Brinson attribution: decompose portfolio return into allocation, selection, and interaction effects by sector.'",
    "Prompt: 'Build strategy comparison: compute Sharpe, Sortino, MaxDD, Win%, PF for each strategy and run t-test on mean returns.'",
    "Prompt: 'Create waterfall chart showing return attribution: market beta, sector exposure, strategy alpha, timing, costs.'",
    "Prompt: 'Write cost analyzer: track commissions, slippage estimates, spread costs per trade and aggregate by strategy.'",
    "Prompt: 'Implement rolling performance: compute 30-day rolling Sharpe, beta, alpha, and plot as time series.'"],
   "Attribution models make assumptions about factor exposures that may not hold. Mitigation: validate with multiple models (Brinson + CAPM + Fama-French). Report confidence intervals.",
   "Attribution engine decomposes returns. Strategy comparison with significance testing. Cost analysis tracks all transaction costs. Benchmarked against SPY."
)

_d(41, "Microservice Architecture: Service Boundaries and gRPC",
   "Begin decomposing monolith into microservices. Define clear service boundaries, implement gRPC for internal communication, keep REST for external API.",
   ["pip install grpcio grpcio-tools protobuf",
    "python3 -c \\"import grpc; print('gRPC', grpc.__version__)\\"",
    "cat phase1/services/ -la | wc -l",
    "find phase1/services -name '__init__.py' | wc -l",
    "python3 -c \\"services=['autopilot','market_data','execution','portfolio','risk','analytics','notification','ingestion']; print(f'{len(services)} candidate microservices')\\"",
    "python3 -m grpc_tools.protoc --help 2>&1 | head -5",
    "grep -rn 'from.*services.*import\\|from.*autopilot.*import' phase1/services/api/ | wc -l",
    "python3 -c \\"import importlib; mods=[m for m in dir() if not m.startswith('_')]; print(len(mods))\\""],
   ["phase1/proto/autopilot.proto (new: gRPC service definitions for autopilot: RunCycle, GetStatus, GetPositions)",
    "phase1/proto/market_data.proto (new: gRPC service for market data: GetBars, GetQuote, StreamPrices)",
    "phase1/proto/execution.proto (new: gRPC service for execution: PlaceOrder, GetOrders, CancelOrder)",
    "phase1/services/grpc_server.py (new: gRPC server hosting all internal services)",
    "phase1/services/grpc_client.py (new: gRPC client stubs for service-to-service communication)",
    "phase1/services/api/main.py (update: REST API calls internal services via gRPC instead of direct imports)",
    "phase1/services/autopilot/service.py (new: gRPC service implementation wrapping existing autopilot logic)",
    "phase1/services/market_data/service.py (new: gRPC service for market data access)",
    "scripts/generate_proto.sh (new: compile .proto files to Python stubs)",
    "docs/adr/011-microservice-boundaries.md (new: ADR documenting service decomposition decisions)",
    "phase1/tests/unit/test_grpc_services.py (new: test gRPC request/response for each service)"],
   ["Strangler Fig Pattern: gradually replace direct imports with gRPC calls, one service at a time",
    "Service Boundaries: each service owns its data, exposes API, no shared DB access across services",
    "gRPC for Internal: faster binary serialization, streaming support, strong typing via protobuf",
    "REST for External: keep REST/JSON for frontend and third-party consumers (human-readable)",
    "Service Registry: each service registers on startup, health checked, discoverable via DNS",
    "Shared Nothing: services communicate only via gRPC/events, no shared state or DB connections"],
   ["Prompt: 'Define protobuf messages and gRPC services for: autopilot (RunCycle, GetStatus), market_data (GetBars, StreamPrices), execution (PlaceOrder).'",
    "Prompt: 'Implement gRPC server wrapping existing autopilot logic: UnifiedEngine.run_cycle() exposed as gRPC method.'",
    "Prompt: 'Write Strangler Fig migration: replace direct autopilot import in API routes with gRPC client call.'",
    "Prompt: 'Create proto compilation script: protoc -> Python stubs -> import in services.'",
    "Prompt: 'Document microservice boundaries in ADR: which functions belong to which service, data ownership rules.'"],
   "Premature microservice split adds complexity without benefit. Mitigation: only extract services with clear boundaries and independent scaling needs. Keep tightly-coupled services together.",
   "3 protobuf definitions created. gRPC server running alongside REST API. Autopilot accessible via gRPC. REST API calls internal services via gRPC."
)
'''
