CHUNK = '''
_d(66, "Container Security Scanning and SBOM",
   "Implement container security: scan Docker images for vulnerabilities, generate SBOM, enforce security policies in CI/CD pipeline.",
   ["pip install safety",
    "python3 -c \\"scans=['trivy_image','snyk_deps','safety_check','hadolint_dockerfile','grype_sbom']; print(f'{len(scans)} security scans')\\"",
    "cat Dockerfile | head -20 2>/dev/null || echo 'no Dockerfile'",
    "pip install pip-audit && pip-audit 2>&1 | tail -10",
    "grep -rn 'vulnerability\\|cve\\|security.scan' .github/ | wc -l"],
   ["scripts/security_scan.sh (new: run Trivy on Docker image, output critical/high vulnerabilities)",
    "scripts/generate_sbom.sh (new: generate SBOM using Syft for dependency transparency)",
    ".github/workflows/security.yml (new: automated security scanning on every PR and weekly schedule)",
    "phase1/requirements-security.txt (new: pinned versions for all dependencies with hashes)",
    "Dockerfile (update: use distroless base image, non-root user, no shell)",
    "docs/security/vulnerability_policy.md (new: SLA for vulnerability remediation: critical=24h, high=7d, medium=30d)",
    "scripts/dependency_update.sh (new: check for outdated deps, create PR with updates and test results)",
    "phase1/tests/security/test_headers.py (new: verify all responses have security headers)",
    "phase1/tests/security/test_auth_bypass.py (new: attempt common auth bypass techniques)"],
   ["Shift-Left Security: scan in CI before merge, block PRs with critical vulnerabilities",
    "Distroless Image: minimal attack surface, no shell, no package manager in production container",
    "SBOM: Software Bill of Materials for supply chain transparency and vulnerability tracking",
    "Dependency Pinning: all deps pinned with hashes to prevent supply chain attacks",
    "Remediation SLA: critical=24h, high=7d, medium=30d, low=next release cycle",
    "Non-Root Container: container runs as non-root user with minimal filesystem permissions"],
   ["Prompt: 'Set up Trivy container scanning in CI: scan Docker image, fail PR if critical or high vulnerabilities found.'",
    "Prompt: 'Generate SBOM using Syft for the Docker image, include in release artifacts for transparency.'",
    "Prompt: 'Harden Dockerfile: distroless base, non-root user, multi-stage build, no shell, minimal layers.'",
    "Prompt: 'Create security policy: vulnerability remediation SLAs, exception process, weekly scan schedule.'",
    "Prompt: 'Write auth bypass tests: test missing token, expired token, invalid signature, privilege escalation.'"],
   "Dependency vulnerabilities are constantly discovered. Mitigation: automated weekly scans, Dependabot for auto-updates, SBOM for tracking.",
   "Container security scanning in CI. Distroless Docker image. SBOM generated. Dependency pinning with hashes. Remediation SLA defined."
)

_d(67, "Database Backup, Recovery, and Disaster Recovery Plan",
   "Implement automated database backups, point-in-time recovery, cross-region replication, and documented disaster recovery procedures with regular testing.",
   ["python3 -c \\"backup_types=['full_daily','incremental_hourly','wal_archive','pg_basebackup','pg_dump_schema']; print(f'{len(backup_types)} backup types')\\"",
    "grep -rn 'backup\\|recovery\\|restore\\|wal' phase1/services/ | wc -l",
    "python3 -c \\"import psycopg2; c=psycopg2.connect(host='localhost',dbname='apex_terminal',user='apex_user',password='dev'); cur=c.cursor(); cur.execute('SELECT pg_database_size(current_database())'); print(f'DB size: {cur.fetchone()[0]/1024/1024:.1f} MB'); c.close()\\""],
   ["scripts/backup/daily_backup.sh (new: pg_basebackup with compression, upload to S3/GCS, verify checksum)",
    "scripts/backup/wal_archive.sh (new: continuous WAL archiving for point-in-time recovery)",
    "scripts/backup/restore.sh (new: restore from backup with point-in-time recovery option)",
    "scripts/backup/verify_backup.sh (new: restore backup to temp DB, run integrity checks, report)",
    "docs/disaster_recovery/dr_plan.md (new: RPO/RTO targets, failover procedures, contact list)",
    "docs/disaster_recovery/runbook.md (new: step-by-step recovery procedures for each failure scenario)",
    "k8s/base/backup-cronjob.yaml (new: daily backup CronJob with S3 upload and Slack notification)",
    "phase1/services/monitoring/backup_monitor.py (new: track backup success/failure, alert on missed backup)",
    "phase1/tests/unit/test_backup_restore.py (new: backup, corrupt a table, restore, verify data integrity)"],
   ["Backup Strategy: full daily at 2 AM + hourly incrementals + continuous WAL archiving",
    "Point-in-Time Recovery: restore to any second using WAL replay (RPO = seconds)",
    "Recovery Time: full restore <30 minutes for 10GB database (RTO target)",
    "Backup Verification: monthly restore to temp DB, run integrity checks, compare row counts",
    "Retention: daily backups kept 30 days, weekly kept 1 year, monthly kept 3 years",
    "Cross-Region: replicate backups to second region for geographic redundancy"],
   ["Prompt: 'Write daily backup script: pg_basebackup with compression, checksum verification, S3 upload, Slack notification.'",
    "Prompt: 'Implement WAL archiving: continuous archive to S3, enable point-in-time recovery to any timestamp.'",
    "Prompt: 'Create DR plan: RPO <1 minute, RTO <30 minutes, failover to read replica, notification procedures.'",
    "Prompt: 'Write backup verification: monthly restore to temp DB, compare row counts, run integrity checks.'",
    "Prompt: 'Create recovery runbook: step-by-step for each scenario: data corruption, server failure, region outage.'"],
   "Untested backups are not backups. Mitigation: monthly automated restore testing, compare row counts and checksums, alert if restore fails.",
   "Daily backups with WAL archiving. Point-in-time recovery tested. DR plan documented with RPO/RTO targets. Monthly restore verification."
)

_d(68, "Custom Metrics and SLO/SLI Framework",
   "Define Service Level Objectives and Indicators for all critical paths. Implement custom Prometheus metrics, SLO dashboards, and error budget tracking.",
   ["python3 -c \\"slos={'api_availability':'99.9%','api_latency_p99':'200ms','autopilot_success':'95%','data_freshness':'5min','order_execution':'99.5%'}; print(slos)\\"",
    "grep -rn 'slo\\|sli\\|error.budget\\|prometheus' phase1/services/ | wc -l",
    "curl -s http://localhost:9090/api/v1/targets 2>/dev/null | python3 -c \\"import json,sys; print(json.load(sys.stdin))\\" 2>/dev/null || echo 'prometheus check needed'"],
   ["phase1/services/monitoring/slo_definitions.py (new: define SLOs for API, autopilot, data pipeline, execution)",
    "phase1/services/monitoring/sli_collector.py (new: collect SLI metrics from Prometheus for each SLO)",
    "phase1/services/monitoring/error_budget.py (new: compute remaining error budget per SLO, alert at 50% consumed)",
    "phase1/services/monitoring/custom_metrics.py (new: business metrics: trades/day, win rate, profit factor)",
    "phase1/services/monitoring/slo_dashboard.py (new: generate Grafana dashboard JSON for all SLOs)",
    "phase1/services/api/slo_routes.py (new: GET /slo/status, GET /slo/budget, GET /slo/history)",
    "frontend/src/features/monitoring/SLODashboard.tsx (new: SLO status cards with budget gauges and trend)",
    "grafana/dashboards/slo.json (new: Grafana dashboard with SLO compliance, error budget burn rate)",
    "phase1/tests/unit/test_error_budget.py (new: budget calculation, alert thresholds, burn rate)"],
   ["SLO Definition: availability (successful requests / total), latency (% under threshold), freshness (data age)",
    "Error Budget: monthly budget = (1 - SLO) * total_requests. Alert at 50% consumed, freeze at 100%",
    "Burn Rate: track how fast error budget is being consumed, alert if projected to exhaust before month end",
    "Custom Business Metrics: trades_per_day, win_rate, profit_factor, avg_hold_time as Prometheus gauges",
    "SLO Review: monthly review of all SLOs, adjust targets based on achievability and business needs",
    "Multi-Window: 5min for alerting, 1hour for dashboards, 30day for SLO compliance reporting"],
   ["Prompt: 'Define SLOs for: API availability (99.9%), API latency p99 (<200ms), autopilot success (>95%), data freshness (<5min).'",
    "Prompt: 'Compute error budget: monthly budget from SLO target, track consumption, alert at 50% and 80% consumed.'",
    "Prompt: 'Create custom Prometheus metrics: trades_per_day counter, win_rate gauge, profit_factor histogram.'",
    "Prompt: 'Build SLO dashboard: status cards (green/yellow/red), error budget gauge, burn rate chart, 30-day trend.'",
    "Prompt: 'Implement burn rate alerting: alert if current burn rate will exhaust monthly error budget in <3 days.'"],
   "SLOs set too aggressively prevent innovation (no error budget for deployments). Mitigation: start with achievable SLOs, tighten quarterly.",
   "SLOs defined for 5 critical paths. Error budget tracking active. Custom business metrics in Prometheus. Grafana SLO dashboard deployed."
)

_d(69, "Multi-Broker Execution with Smart Order Routing",
   "Support simultaneous Alpaca + Tradier execution with smart order routing: best execution, failover, latency-based routing, and fill quality comparison.",
   ["python3 -c \\"brokers={'alpaca':{'latency_ms':50,'fill_rate':0.95,'commission':0.00},'tradier':{'latency_ms':80,'fill_rate':0.98,'commission':0.65}}; print(brokers)\\"",
    "cat phase1/services/brokers/ -la",
    "grep -rn 'router\\|smart.order\\|best.execution' phase1/services/brokers/ | wc -l",
    "wc -l phase1/services/brokers/*.py",
    "python3 -c \\"routing_rules=['best_price','lowest_latency','highest_fill_rate','failover','round_robin']; print(routing_rules)\\""],
   ["phase1/services/brokers/smart_router.py (new: route orders to best broker based on configurable criteria)",
    "phase1/services/brokers/execution_comparator.py (new: compare fill quality across brokers for same order type)",
    "phase1/services/brokers/failover_manager.py (new: auto-failover to secondary broker on primary failure)",
    "phase1/services/brokers/latency_tracker.py (new: track per-broker latency statistics for routing decisions)",
    "phase1/services/brokers/fill_analyzer.py (new: analyze fill quality: price improvement, fill rate, slippage)",
    "phase1/services/brokers/broker_health.py (new: continuous health monitoring per broker with status tracking)",
    "phase1/services/api/broker_routes.py (new: GET /brokers/status, GET /brokers/comparison, POST /brokers/prefer)",
    "frontend/src/features/brokers/BrokerComparison.tsx (new: side-by-side broker metrics with recommendation)",
    "phase1/tests/unit/test_smart_router.py (new: routing decision, failover, latency-based selection)",
    "phase1/tests/unit/test_execution_comparator.py (new: fill quality comparison across brokers)"],
   ["Smart Routing: select broker per order based on: asset type, order size, urgency, historical fill quality",
    "Failover: if primary broker unhealthy (3 failures in 5 min), auto-route to secondary with alert",
    "Latency Tracking: rolling average latency per broker per order type for data-driven routing",
    "Fill Quality: track price improvement, fill rate, partial fills per broker for monthly review",
    "Split Orders: large orders can be split across brokers for better fill rates and reduced market impact",
    "Broker Health: heartbeat check every 30s, health score 0-100 based on availability, latency, fill rate"],
   ["Prompt: 'Build smart order router: select between Alpaca and Tradier based on order type, size, and historical performance.'",
    "Prompt: 'Implement failover: detect broker health degradation (3 failures in 5 min), auto-switch to backup broker.'",
    "Prompt: 'Track per-broker latency: rolling 100-order average latency for options, equities, data requests.'",
    "Prompt: 'Create BrokerComparison view: side-by-side metrics (latency, fill rate, commission) with recommendation badge.'",
    "Prompt: 'Analyze fill quality: compute price improvement vs NBBO midpoint per broker per asset type.'"],
   "Broker failover during open positions can cause inconsistent state. Mitigation: verify all positions on both brokers after failover, reconcile any discrepancies.",
   "Smart order routing between Alpaca and Tradier. Auto-failover on broker failure. Fill quality tracked and compared. Broker health monitoring active."
)

_d(70, "Automated Regression Testing Suite",
   "Build comprehensive regression suite: snapshot tests for API responses, visual regression for UI, data regression for analytics, and automated daily execution.",
   ["cd phase1 && python3 -m pytest tests/ -v --tb=short -x 2>&1 | tail -20",
    "cd frontend && npm test -- --watchAll=false 2>&1 | tail -10",
    "python3 -c \\"regression_types=['api_snapshot','ui_visual','data_computation','performance_benchmark','integration_flow']; print(f'{len(regression_types)} regression types')\\"",
    "grep -rn 'snapshot\\|regression\\|baseline' phase1/tests/ | wc -l",
    "cat .github/workflows/ci.yml | grep -c 'test'"],
   ["tests/regression/api_snapshots.py (new: capture API response shapes, detect breaking changes)",
    "tests/regression/data_regression.py (new: compare analytics output to known-good baselines)",
    "tests/regression/visual_regression.spec.ts (new: screenshot comparison for all major UI pages)",
    "tests/regression/performance_regression.py (new: benchmark critical paths, alert on >20% degradation)",
    "tests/regression/update_baselines.py (new: script to update baselines when intentional changes occur)",
    "scripts/run_regression.sh (new: orchestrate all regression tests, generate comparison report)",
    ".github/workflows/regression.yml (new: nightly regression suite with result notification)",
    "docs/testing/regression_guide.md (new: how to add, update, and interpret regression tests)",
    "tests/regression/conftest.py (new: shared fixtures for baseline loading and comparison)"],
   ["API Snapshots: serialize response structure and types, compare to stored baseline on every run",
    "Visual Regression: pixel-level screenshot comparison with configurable threshold (0.1% tolerance)",
    "Data Regression: run analytics computations on fixed dataset, compare to known-good output",
    "Performance Regression: if critical path p99 degrades >20% from baseline, fail test",
    "Baseline Updates: explicit command to update baselines, requires justification in commit message",
    "Nightly Execution: full regression suite runs nightly, sends report to Discord channel"],
   ["Prompt: 'Build API snapshot tests: capture response structure for all endpoints, compare to stored baselines.'",
    "Prompt: 'Implement visual regression: screenshot all pages with Playwright, compare pixel-by-pixel with 0.1% tolerance.'",
    "Prompt: 'Create data regression: run analytics on fixed dataset, compare output to known-good baseline values.'",
    "Prompt: 'Write baseline update script: accept new baseline, require --reason flag for commit message.'",
    "Prompt: 'Set up nightly regression CI: run all regression types, generate HTML report, post summary to Discord.'"],
   "Visual regression tests are sensitive to rendering differences across environments. Mitigation: run in Docker with fixed fonts and resolution.",
   "Regression suite covers API snapshots, visual UI, data computations, and performance. Nightly execution with Discord notifications."
)
'''
