# Days 8-20 content to be appended to quarter_01.py

CHUNK = '''
_d(8, "PostgreSQL Migration: Schema Design and Alembic Setup",
   "Migrate from SQLite to PostgreSQL. Design normalized schema with proper indexes, foreign keys, and partitioning. Set up Alembic for version-controlled migrations.",
   ["sudo apt-get install -y postgresql postgresql-contrib libpq-dev",
    "pip install psycopg2-binary asyncpg alembic sqlalchemy[asyncio]",
    "sudo -u postgres createuser apex_user --createdb --pwprompt",
    "sudo -u postgres createdb apex_terminal --owner=apex_user",
    "alembic init phase1/migrations",
    "python3 -c \\"import psycopg2; c=psycopg2.connect(host='localhost',dbname='apex_terminal',user='apex_user',password='dev'); print('PG OK'); c.close()\\"",
    "python3 -c \\"import sqlite3; c=sqlite3.connect('phase1/phase1.db'); t=[r[0] for r in c.execute('SELECT name FROM sqlite_master WHERE type=table')]; print(len(t),'tables:', t)\\"",
    "alembic revision --autogenerate -m initial_schema",
    "alembic upgrade head",
    "python3 scripts/migrate_sqlite_to_pg.py --dry-run 2>&1 | tee migration_dry.log"],
   ["phase1/services/database/connection.py (new: async PG connection pool, healthcheck, 20 max connections)",
    "phase1/services/database/models.py (new: SQLAlchemy ORM for trades, positions, bars, autopilot_runs, options_cache, trade_ledger)",
    "phase1/services/database/repositories.py (new: Repository pattern with async CRUD per entity)",
    "phase1/migrations/env.py (new: Alembic config with async PG driver, auto-detect model changes)",
    "phase1/migrations/versions/001_initial_schema.py (new: all tables with indexes, FKs, constraints)",
    "phase1/services/database/indexes.py (new: B-Tree on symbol+timestamp, BRIN on time-series, GIN on JSON)",
    "phase1/services/database/partitioning.py (new: monthly partitions for bars, auto-create new partitions)",
    "scripts/migrate_sqlite_to_pg.py (new: bulk migration with validation, row count verification, rollback)",
    "phase1/services/config.py (update: DATABASE_URL env var, pool settings, PG connection params)",
    "docker-compose.yml (update: add postgres:16 service with volume and healthcheck)",
    "keys.env (update: DATABASE_URL=postgresql+asyncpg://apex_user:dev@localhost/apex_terminal)"],
   ["Repository Pattern: abstract DB behind interfaces for testability and portability",
    "Connection Pooling: asyncpg pool min=5, max=20, recycle=3600s for long-running connections",
    "Time-Series Partitioning: bars partitioned monthly for fast range queries, easy archival, and vacuum speed",
    "Index Strategy: B-Tree for exact lookups, BRIN for timestamp ranges, partial indexes for active records only",
    "Migration Safety: Alembic --sql for reviewable SQL, never auto-apply in production",
    "Dual-Write Period: write to both SQLite and PG for 2 weeks, compare results before decommissioning SQLite"],
   ["Prompt: 'Design a PostgreSQL schema for a trading platform with: trades, positions, bars, autopilot_runs, options_cache, trade_ledger. Include FKs, indexes, constraints.'",
    "Prompt: 'Write Alembic migration creating monthly partitions for bars table from 2023-01 to 2025-12.'",
    "Prompt: 'Create async Repository classes with get_by_id, list_filtered, create, update, delete, bulk_upsert.'",
    "Prompt: 'Write SQLite-to-PG migration script with row count validation, type mapping, and referential integrity checks.'",
    "Prompt: 'Generate EXPLAIN ANALYZE for the 10 most common autopilot queries and suggest index improvements.'"],
   "Data loss during migration is catastrophic. Mitigation: dual-write for 2 weeks, validate row counts daily, keep SQLite as read-only backup until PG is proven stable.",
   "PostgreSQL running with all tables migrated. Alembic tracks versions. All services read from PG. Row counts match SQLite."
)

_d(9, "Redis Integration: Caching, Pub/Sub, Session Store",
   "Deploy Redis for sub-ms caching of market data, options chains, LLM responses. Implement pub/sub for real-time events. Use as rate limiter and session store backend.",
   ["sudo apt-get install -y redis-server",
    "pip install redis[hiredis] aioredis",
    "redis-cli ping",
    "redis-cli INFO server | head -10",
    "python3 -c \\"import redis; r=redis.Redis(); r.set('test','hello'); print(r.get('test'))\\"",
    "redis-cli CONFIG SET maxmemory 256mb",
    "redis-cli CONFIG SET maxmemory-policy allkeys-lru",
    "python3 -c \\"import redis; r=redis.Redis(); r.setex('cache_test',60,'cached'); print('TTL:', r.ttl('cache_test'))\\"",
    "redis-benchmark -q -n 1000 -c 10 -t SET,GET 2>&1 | tail -5"],
   ["phase1/services/cache/redis_client.py (new: async Redis pool, health check, key namespacing, error handling)",
    "phase1/services/cache/cache_manager.py (new: get/set/delete with TTL, pattern invalidation, JSON ser/deser)",
    "phase1/services/cache/decorators.py (new: @cached(ttl=60) decorator for service methods with key generation)",
    "phase1/services/cache/keys.py (new: apex:prices:{sym}, apex:chains:{sym}:{exp}, apex:llm:{hash})",
    "phase1/services/options/tradier_provider.py (update: replace in-memory dict cache with Redis, 60s TTL)",
    "phase1/services/autopilot/data_fetcher.py (update: cache market data, 30s live / 24h historical)",
    "phase1/services/llm/providers/groq_provider.py (update: cache identical prompt responses for 5 minutes)",
    "phase1/services/events/redis_pubsub.py (new: publish/subscribe for cross-process event distribution)",
    "phase1/services/api/rate_limit.py (update: Redis sliding window backend instead of in-memory)",
    "docker-compose.yml (update: add redis:7 service with AOF persistence and healthcheck)",
    "phase1/tests/unit/test_cache_manager.py (new: set/get/TTL/pattern invalidation/serialization)"],
   ["Cache-Aside Pattern: check cache, miss -> fetch source -> store cache -> return",
    "TTL Strategy: prices=30s, chains=60s, LLM=300s, historical=86400s, config=invalidate-on-change",
    "Key Namespacing: apex:{service}:{entity}:{id} prevents key collisions across services",
    "Pub/Sub: autopilot phases published to channel, WebSocket manager subscribes and broadcasts to clients",
    "Cache Warming: on startup, pre-populate top 20 symbols and active positions",
    "Eviction: allkeys-lru with 256MB, monitor hit rate to tune TTLs optimally"],
   ["Prompt: 'Create async Redis cache manager with get/set/delete, TTL, JSON serialization, pattern-based invalidation.'",
    "Prompt: 'Write @cached decorator that auto-generates cache keys from function name and args.'",
    "Prompt: 'Implement Redis pub/sub for autopilot events: publish phase transitions, subscribe in WS manager.'",
    "Prompt: 'Convert Tradier in-memory cache to Redis with OptionChain JSON serialization and 60s TTL.'",
    "Prompt: 'Build Redis monitoring script showing: total keys, memory usage, hit/miss ratio, slowlog entries.'"],
   "Redis as single point of failure cascades to source APIs. Mitigation: graceful degradation - if Redis down, fallback to in-memory cache with shorter TTLs.",
   "Redis running with 256MB limit. Options chains cached 60s. Cache hit rate > 80% for repeated queries."
)

_d(10, "Docker Compose: Full Stack Orchestration",
   "Create production Docker Compose: PostgreSQL, Redis, FastAPI backend, Vite frontend, n8n - all services healthy and communicating over internal network.",
   ["docker --version && docker compose version",
    "docker network create apex-net 2>/dev/null || true",
    "docker compose -f docker-compose.unified.yml config --quiet 2>&1",
    "docker compose -f docker-compose.unified.yml build --no-cache 2>&1 | tail -20",
    "docker compose -f docker-compose.unified.yml up -d 2>&1",
    "docker compose -f docker-compose.unified.yml ps",
    "docker compose -f docker-compose.unified.yml logs backend --tail=20",
    "curl -s http://localhost:8000/health | python3 -m json.tool",
    "curl -s http://localhost:5173 | head -5",
    "docker compose -f docker-compose.unified.yml down"],
   ["docker-compose.yml (rewrite: PG 16, Redis 7, backend, frontend, n8n, all with healthchecks and depends_on)",
    "phase1/Dockerfile (rewrite: multi-stage build, non-root user, minimal final image, HEALTHCHECK)",
    "frontend/Dockerfile (new: multi-stage: npm build -> nginx serve static files)",
    "frontend/nginx.conf (new: reverse proxy /api to backend, gzip, cache-control headers)",
    ".env.docker (new: all env vars for Docker, no secrets in Dockerfiles)",
    "scripts/docker_healthcheck.py (new: comprehensive check for PG, Redis, backend, frontend)",
    "scripts/docker_init_db.sh (new: wait-for-pg, run alembic upgrade head, seed data)",
    "Makefile (update: docker-up, docker-down, docker-logs, docker-rebuild, docker-shell targets)",
    ".dockerignore (update: exclude node_modules, __pycache__, .git, logs, *.db, venv)",
    "docs/DOCKER_SETUP.md (new: deployment guide with troubleshooting for common Docker issues)"],
   ["Multi-Stage Builds: stage 1 installs deps, stage 2 copies runtime only (50% smaller images)",
    "Service Discovery: containers communicate via Docker DNS names (backend, postgres, redis)",
    "Health Checks: each service has HEALTHCHECK, depends_on uses condition: service_healthy for ordering",
    "Volume Strategy: PG data and Redis AOF on named volumes, logs on bind mounts",
    "Network Isolation: frontend -> backend -> postgres/redis (frontend cannot access DB directly)",
    "Init Container: migration service runs before backend, ensures schema is ready before app starts"],
   ["Prompt: 'Write production Docker Compose: PG 16, Redis 7, FastAPI, Vite/nginx, n8n - all with healthchecks and proper ordering.'",
    "Prompt: 'Create multi-stage Dockerfile for FastAPI: install deps in builder, copy runtime in final, run as non-root.'",
    "Prompt: 'Write nginx.conf serving Vite frontend, proxying /api and /ws to backend, with gzip and caching.'",
    "Prompt: 'Create Docker health check verifying: PG accepts connections, Redis PING, backend /health 200.'",
    "Prompt: 'Write Makefile with: up, down, rebuild, logs, shell-backend, shell-db, migrate, seed targets.'"],
   "Docker adds complexity and RAM overhead. Mitigation: document min requirements (4GB RAM, 2 CPU). Keep non-Docker local dev option.",
   "docker compose up starts all services. All healthchecks pass. Backend /health returns OK. Frontend loads at :5173."
)

_d(11, "APScheduler: Automated Market-Hours Trading Loop",
   "Implement APScheduler for time-based autopilot: pre-market scan 9:15 AM, intraday cycles every 15 min, position monitor every 5 min, EOD report 4:05 PM. All market-hours aware.",
   ["pip install apscheduler pytz exchange-calendars",
    "python3 -c \\"from apscheduler.schedulers.asyncio import AsyncIOScheduler; print('APScheduler ready')\\"",
    "python3 -c \\"import exchange_calendars as xcals; nyse=xcals.get_calendar('XNYS'); print('NYSE calendar loaded')\\"",
    "python3 -c \\"from datetime import datetime; import pytz; et=pytz.timezone('US/Eastern'); print('ET:', datetime.now(et))\\"",
    "grep -rn 'schedule\\|cron\\|APScheduler' phase1/services/ | wc -l",
    "cat phase1/services/autopilot/runloop.py | head -30",
    "cat phase1/services/market_calendar.py | head -30",
    "python3 -c \\"import exchange_calendars as xcals; nyse=xcals.get_calendar('XNYS'); import pandas as pd; print('Today open:', nyse.is_session(pd.Timestamp.today()))\\""],
   ["phase1/services/scheduler/scheduler.py (new: AsyncIOScheduler with market-hours-aware job definitions)",
    "phase1/services/scheduler/jobs.py (new: pre_market_scan, intraday_cycle, position_monitor, eod_report, eod_cleanup)",
    "phase1/services/scheduler/market_hours.py (new: is_market_open, next_open, next_close, is_holiday)",
    "phase1/services/scheduler/job_registry.py (new: central registry with enable/disable/status per job)",
    "phase1/services/scheduler/dead_mans_switch.py (new: alert if expected job missed its window)",
    "phase1/services/autopilot/runloop.py (update: integrate with scheduler instead of manual triggers)",
    "phase1/services/api/scheduler_routes.py (new: GET /scheduler/jobs, POST trigger, POST enable/disable)",
    "phase1/services/api/main.py (update: start scheduler on startup, stop on shutdown)",
    "frontend/src/features/automation/SchedulerPanel.tsx (new: jobs table, next run, last result, trigger button)",
    "phase1/tests/unit/test_scheduler.py (new: job registration, market hours, holiday skip, manual trigger)",
    "phase1/tests/unit/test_dead_mans_switch.py (new: alert after missed window, reset on success)"],
   ["Market-Hours Gate: every job checks is_market_open() before executing, skips weekends/holidays",
    "Job Lifecycle: REGISTERED -> SCHEDULED -> RUNNING -> COMPLETED/FAILED with full audit trail in DB",
    "Distributed Lock: Redis SETNX prevents duplicate job execution across multiple backend instances",
    "Dead Mans Switch: if pre_market_scan hasnt run by 9:45 AM ET, send critical Discord alert",
    "Graceful Shutdown: SIGTERM finishes current job, cancels pending, saves state, exits cleanly",
    "Timezone: all schedules America/New_York, all storage UTC, display in users local timezone"],
   ["Prompt: 'Create APScheduler with 5 jobs: pre_market(9:15 ET), intraday(every 15m 9:30-16:00), monitor(every 5m), eod_report(16:05), cleanup(16:30).'",
    "Prompt: 'Write market hours checker with exchange_calendars handling NYSE holidays and early closes.'",
    "Prompt: 'Implement dead mans switch: alert if pre_market_scan hasnt fired by 9:45 AM ET.'",
    "Prompt: 'Create API endpoints to list, trigger, enable/disable scheduled jobs with admin auth.'",
    "Prompt: 'Write SchedulerPanel React component: jobs table with name, schedule, next run, status, trigger button.'"],
   "Scheduler executing trades without human awareness is dangerous. Mitigation: all scheduled cycles default dry_run=True. Must explicitly enable live mode via admin API with confirmation.",
   "APScheduler running 5 jobs. Pre-market fires 9:15 ET. Intraday cycles every 15m during market hours only."
)

_d(12, "Hallucination Detection and LLM Output Validation",
   "Build validation layer catching LLM hallucinations: verify symbols exist, strikes are real, prices within range, reasoning grounded in provided data.",
   ["pip install rapidfuzz jsonschema",
    "python3 -c \\"from rapidfuzz import fuzz; print('Similarity AAPL/AAPPL:', fuzz.ratio('AAPL','AAPPL'))\\"",
    "grep -rn 'hallucin\\|grounding\\|validate_llm' phase1/services/ | wc -l",
    "cat phase1/services/autopilot/validator.py | head -40",
    "python3 -c \\"import json; schema={'type':'object','required':['symbol','action','confidence']}; print(json.dumps(schema))\\"",
    "cat phase1/services/autopilot/hybrid_selector.py | grep -A10 'def select'",
    "python3 -c \\"syms=['AAPL','MSFT','GOOGL','AMZN','SPY','QQQ','IWM','TSLA','NVDA','META']; print(len(syms),'symbols')\\"",
    "grep -rn 'json_schema\\|validate_output' phase1/services/llm/ | wc -l"],
   ["phase1/services/autopilot/hallucination_detector.py (new: validate LLM outputs against market reality)",
    "phase1/services/autopilot/output_schema.py (new: JSON Schema for all LLM response formats)",
    "phase1/services/autopilot/grounding_checker.py (new: verify LLM reasoning only references data from prompt context)",
    "phase1/services/autopilot/symbol_validator.py (new: fuzzy match symbols, check tradeable, verify exchange)",
    "phase1/services/autopilot/price_range_validator.py (new: check prices within daily high/low + 5%)",
    "phase1/services/autopilot/strike_validator.py (new: verify option strikes exist in actual chain data)",
    "phase1/services/autopilot/confidence_calibration.py (new: track confidence vs outcomes, calibrate over time)",
    "phase1/services/autopilot/hybrid_selector.py (update: pipe output through hallucination detector before acting)",
    "phase1/services/autopilot/validator.py (update: add hallucination checks to validation pipeline)",
    "phase1/tests/unit/test_hallucination_detector.py (new: fake symbol, impossible price, invalid strike tests)",
    "phase1/tests/fixtures/hallucinated_responses.json (new: 20 examples of common trading LLM hallucinations)"],
   ["Defense Against Confabulation: treat every LLM output as untrusted input - validate everything",
    "Schema Enforcement: JSON Schema with strict enums, numeric ranges, required fields - reject malformed",
    "Grounding Check: extract entities from reasoning, verify each appears in the provided context",
    "Fuzzy Symbol Match: APLE -> AAPL auto-correct if similarity > 90%, otherwise flag and reject",
    "Price Sanity: if LLM says buy AAPL at $50 when price is $185, flag as hallucination and reject",
    "Confidence Calibration: compare predicted confidence to actual outcomes, compute ECE over time"],
   ["Prompt: 'Build hallucination detector for trading LLMs. Verify: symbol exists, strike in chain, price in range, reasoning grounded.'",
    "Prompt: 'Create 20 test cases of trading LLM hallucinations: fake symbols, impossible prices, expired options, circular reasoning.'",
    "Prompt: 'Write grounding checker extracting entities from LLM text, verifying each against input context.'",
    "Prompt: 'Implement confidence calibration tracking predicted vs actual outcomes with expected calibration error metric.'",
    "Prompt: 'Design strict JSON Schema validating LLM selection: symbol, action, strike, exp, confidence, reasoning.'"],
   "Over-aggressive detection blocks valid trades. Mitigation: log all rejections with reason, review weekly to tune thresholds. Never auto-reject without logging.",
   "Hallucination detector catches fake symbols, impossible prices, invalid strikes. All LLM outputs validated before execution."
)

_d(13, "Entry Scoring Engine (0-100 Quantitative Score)",
   "Build quantitative scoring engine rating every candidate 0-100 based on IV rank, delta, liquidity, POP, earnings proximity, sector momentum, and portfolio correlation.",
   ["pip install scipy scikit-learn",
    "python3 -c \\"from scipy import stats; print('scipy ready')\\"",
    "cat phase1/services/autopilot/candidates.py | head -30",
    "cat phase1/services/autopilot/features.py | head -30",
    "grep -rn 'score\\|rank\\|rating' phase1/services/autopilot/ | wc -l",
    "python3 -c \\"import numpy as np; s=np.random.uniform(0,100,30); print(f'Mean:{s.mean():.1f} Std:{s.std():.1f}')\\"",
    "python3 -c \\"w={'iv':0.20,'pop':0.20,'liq':0.15,'rr':0.15,'delta':0.10,'dte':0.10,'sector':0.05,'corr':0.05}; print('Sum:', sum(w.values()))\\"",
    "grep -rn 'iv_rank\\|pop\\|liquidity_score' phase1/services/autopilot/ | wc -l"],
   ["phase1/services/autopilot/scoring_engine.py (new: compute composite 0-100 from 10+ weighted signals)",
    "phase1/services/autopilot/feature_extractors.py (new: IV rank, POP, liquidity, risk/reward, delta fit extractors)",
    "phase1/services/autopilot/scoring_weights.py (new: configurable weight vectors per strategy template)",
    "phase1/services/autopilot/scoring_normalizer.py (new: min-max and z-score normalization for heterogeneous features)",
    "phase1/services/autopilot/correlation_checker.py (new: compute candidate correlation to existing portfolio)",
    "phase1/services/autopilot/sector_momentum.py (new: sector ETF momentum for sector-aware scoring)",
    "phase1/services/autopilot/earnings_proximity.py (new: penalize candidates with earnings within 7 DTE)",
    "phase1/services/autopilot/candidates.py (update: attach composite score to each CandidateRecord)",
    "phase1/services/autopilot/hybrid_selector.py (update: provide scores to LLM for informed ranking)",
    "frontend/src/features/autopilot/ScoreBreakdown.tsx (new: radar chart showing component scores per candidate)",
    "phase1/tests/unit/test_scoring_engine.py (new: boundary cases, weight normalization, score distribution)"],
   ["Weighted Composite: SUM(weight_i * normalized_signal_i) across iv, pop, liq, rr, delta, dte, sector, corr, earnings, vol",
    "Feature Normalization: z-score within rolling 30-day window for adaptive thresholds",
    "Per-Strategy Weights: Iron Condor emphasizes IV rank, vertical spread emphasizes delta",
    "Score Threshold: min 60/100 to pass to LLM stage, min 75/100 for auto-execution without LLM",
    "Explainability: score breakdown shows each factors contribution (credit score report style)",
    "Backtestable: scoring engine runs on historical data, validates score-to-outcome correlation"],
   ["Prompt: 'Design 0-100 scoring engine with 10 weighted features: IV rank, POP, liquidity, risk/reward, delta, DTE, sector, correlation, earnings, vol smile.'",
    "Prompt: 'Write feature extractors each returning normalized 0-1 value for the scoring composite.'",
    "Prompt: 'Create React radar chart showing 10-axis score breakdown, color-coded by total score.'",
    "Prompt: 'Implement correlation checking: compute portfolio correlation impact of adding new candidate.'",
    "Prompt: 'Backtest scoring: score historical trades, compute Spearman correlation with realized P&L.'"],
   "Overfit weights to recent regime. Mitigation: validate on walk-forward basis, update weights quarterly based on realized outcomes.",
   "Every candidate has 0-100 score. Breakdown visible in UI. Candidates below 60 auto-rejected pre-LLM."
)

_d(14, "Monte Carlo Position Simulator",
   "Build MC simulator running 10,000 GBM price path simulations per candidate to estimate POP, expected return, VaR, CVaR, max drawdown before entry.",
   ["pip install numba joblib tqdm",
    "python3 -c \\"from numba import jit; print('numba JIT ready')\\"",
    "python3 -c \\"import numpy as np; S0=185; sigma=0.3; dt=1/252; Z=np.random.standard_normal((10000,30)); S=S0*np.exp(np.cumsum(-0.5*sigma**2*dt+sigma*np.sqrt(dt)*Z,axis=1)); print(f'Mean final: {S[:,-1].mean():.2f}')\\"",
    "python3 -c \\"import time,numpy as np; t=time.time(); [np.random.standard_normal((10000,30)) for _ in range(100)]; print(f'{time.time()-t:.2f}s for 100 batches')\\"",
    "grep -rn 'monte.*carlo\\|simulation' phase1/services/ | wc -l",
    "python3 -c \\"from scipy.stats import norm; print(f'VaR 5%: {norm.ppf(0.05):.4f}')\\"",
    "python3 -c \\"import numpy as np; r=np.random.normal(0.001,0.02,252); sharpe=np.sqrt(252)*r.mean()/r.std(); print(f'Sharpe: {sharpe:.2f}')\\"",
    "ls phase1/services/forecasting/ 2>/dev/null || echo 'No forecasting dir'"],
   ["phase1/services/simulation/monte_carlo.py (new: GBM price path generator with configurable vol, drift, Numba JIT)",
    "phase1/services/simulation/option_payoff.py (new: payoff calc for puts, calls, spreads, IC, butterflies across paths)",
    "phase1/services/simulation/risk_metrics.py (new: POP, expected return, VaR, CVaR, max drawdown from simulated paths)",
    "phase1/services/simulation/vol_model.py (new: historical vol, EWMA vol, GARCH(1,1) estimation)",
    "phase1/services/simulation/jump_diffusion.py (new: Merton jump-diffusion for earnings/event scenarios)",
    "phase1/services/simulation/batch_simulator.py (new: parallel simulation of multiple candidates via joblib)",
    "phase1/services/autopilot/candidates.py (update: attach MC results to each CandidateRecord)",
    "phase1/services/autopilot/validator.py (update: reject if MC-POP < 55% or CVaR > 2x max loss)",
    "frontend/src/features/autopilot/MonteCarloChart.tsx (new: PnL histogram with percentile markers)",
    "phase1/tests/unit/test_monte_carlo.py (new: convergence, known-price validation, perf benchmark)",
    "phase1/tests/unit/test_option_payoff.py (new: call/put/spread payoff against textbook values)"],
   ["GBM: dS = mu*S*dt + sigma*S*dW with vol calibrated from historical data",
    "Numba JIT: @jit(nopython=True) for 50x speedup (10K paths in <100ms)",
    "Parallel: joblib for 30 candidates simultaneously across CPU cores",
    "Risk Metrics: POP = pct paths positive PnL, VaR = 5th percentile loss, CVaR = mean worst 5%",
    "Vol Calibration: 30-day EWMA for mean-reversion, GARCH for trend-following strategies",
    "Jump Diffusion: Poisson jumps for earnings (magnitude from historical surprise distribution)"],
   ["Prompt: 'Implement MC simulator using GBM with Numba JIT. 10K paths, configurable vol and drift.'",
    "Prompt: 'Write option payoff calculators for: long call, put, vertical spread, iron condor, butterfly across MC paths.'",
    "Prompt: 'Compute risk metrics from MC: POP, expected return, VaR(5%), CVaR(5%), max drawdown.'",
    "Prompt: 'Create React histogram of simulated PnL with vertical lines at mean, VaR, CVaR.'",
    "Prompt: 'Implement GARCH(1,1) vol estimation: fit to historical returns, use for MC calibration.'"],
   "GBM underestimates tails. Mitigation: jump-diffusion for earnings, fat-tailed distributions for crypto. Compare MC-POP vs market-implied POP.",
   "MC simulator runs 10K paths per candidate in <200ms. POP, VaR, CVaR displayed in UI. MC-POP<55% auto-rejected."
)

_d(15, "Walk-Forward Backtesting Framework",
   "Build walk-forward backtester that trains on rolling windows, tests on out-of-sample periods, and produces unbiased performance estimates with proper train/test isolation.",
   ["pip install vectorbt quantstats",
    "python3 -c \\"import vectorbt as vbt; print('vectorbt', vbt.__version__)\\"",
    "python3 -c \\"import quantstats as qs; print('quantstats ready')\\"",
    "cat phase1/services/backtest/ -la 2>/dev/null || ls phase1/services/backtest_engine/",
    "grep -rn 'walk.forward\\|rolling.*window\\|out.of.sample' phase1/services/ | wc -l",
    "python3 -c \\"import pandas as pd; idx=pd.date_range('2022-01-01','2024-12-31',freq='B'); print(f'{len(idx)} trading days')\\"",
    "python3 -c \\"import numpy as np; r=np.random.normal(0.0005,0.01,756); sr=np.sqrt(252)*r.mean()/r.std(); md=np.min(np.cumsum(r)-np.maximum.accumulate(np.cumsum(r))); print(f'Sharpe:{sr:.2f} MaxDD:{md:.4f}')\\"",
    "wc -l phase1/services/backtest_engine/*.py",
    "cat scripts/backtest.py | head -30"],
   ["phase1/services/backtest_engine/walk_forward.py (new: rolling window train/test with configurable window sizes)",
    "phase1/services/backtest_engine/data_splitter.py (new: anchored, rolling, expanding window splitters)",
    "phase1/services/backtest_engine/performance.py (new: Sharpe, Sortino, Calmar, MaxDD, Win Rate, Profit Factor)",
    "phase1/services/backtest_engine/reporter.py (new: HTML report with equity curve, drawdown chart, monthly returns heatmap)",
    "phase1/services/backtest_engine/trade_simulator.py (new: realistic fills with slippage, commissions, partial fills)",
    "phase1/services/backtest_engine/parameter_grid.py (new: grid search and random search for strategy parameters)",
    "phase1/services/backtest_engine/anti_overfit.py (new: combinatorial purged cross-validation, deflated Sharpe ratio)",
    "phase1/services/strategy/iron_condor.py (update: implement backtest-compatible interface)",
    "phase1/services/api/backtest_routes.py (new: POST /backtest/run, GET /backtest/results/{id})",
    "frontend/src/features/backtest/BacktestDashboard.tsx (new: equity curve, drawdown, monthly heatmap, trade list)",
    "phase1/tests/unit/test_walk_forward.py (new: window sizing, no lookahead, metric computation accuracy)"],
   ["Walk-Forward: train on 6 months, test on 1 month, slide forward, aggregate out-of-sample results",
    "No Lookahead Bias: strict timestamp enforcement, data split BEFORE any feature computation",
    "Realistic Simulation: slippage = half the spread, commission = $0.65/contract, partial fills modeled",
    "Anti-Overfit: deflated Sharpe ratio accounts for multiple testing, CPCV for robust cross-validation",
    "Performance Suite: Sharpe, Sortino, Calmar, MaxDD, Win%, Profit Factor, Avg Win/Loss, Recovery Factor",
    "HTML Reports: quantstats-powered report with 30+ metrics, equity curve, monthly returns, drawdown periods"],
   ["Prompt: 'Build walk-forward backtester: train on rolling 6-month window, test on next month, slide forward, aggregate OOS results.'",
    "Prompt: 'Implement data splitter with anchored, rolling, and expanding window modes with purged gap between train/test.'",
    "Prompt: 'Write realistic trade simulator with configurable slippage model, commission structure, and partial fill probability.'",
    "Prompt: 'Create HTML backtest report with equity curve, drawdown chart, monthly returns heatmap, and 30+ performance metrics.'",
    "Prompt: 'Implement deflated Sharpe ratio to account for multiple hypothesis testing across parameter sweeps.'"],
   "Overfitting to historical data gives false confidence. Mitigation: walk-forward with purged gaps, deflated Sharpe ratio, minimum 2-year test period. Never deploy params optimized on full dataset.",
   "Walk-forward backtest runs on Iron Condor strategy. OOS Sharpe > 0.5. HTML report with equity curve, drawdown, and monthly returns generated."
)

_d(16, "News Sentiment Engine (NLP Pipeline)",
   "Build production NLP pipeline for financial news sentiment: collect from multiple sources, extract entities, classify sentiment, score relevance, and feed into autopilot decisions.",
   ["pip install transformers torch newspaper3k feedparser textblob spacy",
    "python3 -m spacy download en_core_web_sm",
    "python3 -c \\"from transformers import pipeline; clf=pipeline('sentiment-analysis',model='distilbert-base-uncased-finetuned-sst-2-english'); print(clf('AAPL beats earnings expectations'))\\"",
    "grep -rn 'sentiment\\|news' phase1/services/autopilot/ | wc -l",
    "cat phase1/services/autopilot/news_sentiment.py | head -30",
    "cat phase1/services/autopilot/news_provider.py | head -30",
    "python3 -c \\"from textblob import TextBlob; b=TextBlob('AAPL reports strong quarterly results'); print(f'Polarity: {b.sentiment.polarity}')\\"",
    "python3 -c \\"import feedparser; feed=feedparser.parse('https://feeds.finance.yahoo.com/rss/2.0/headline?s=AAPL'); print(f'{len(feed.entries)} articles')\\""],
   ["phase1/services/sentiment/news_collector.py (new: multi-source collector: RSS feeds, newsapi.org, finviz, SEC filings)",
    "phase1/services/sentiment/entity_extractor.py (new: spaCy NER for ticker symbols, company names, executives, events)",
    "phase1/services/sentiment/sentiment_classifier.py (new: FinBERT or DistilBERT fine-tuned for financial text)",
    "phase1/services/sentiment/relevance_scorer.py (new: score article relevance to specific symbol using TF-IDF + entity overlap)",
    "phase1/services/sentiment/aggregator.py (new: aggregate per-article scores into per-symbol daily sentiment)",
    "phase1/services/sentiment/cache.py (new: Redis-backed article cache with deduplication by URL hash)",
    "phase1/services/autopilot/news_sentiment.py (update: replace basic impl with NLP pipeline)",
    "phase1/services/autopilot/unified_engine.py (update: inject sentiment score into candidate evaluation)",
    "phase1/services/api/sentiment_routes.py (new: GET /sentiment/{symbol}, GET /sentiment/trending)",
    "frontend/src/features/trading/tiles/NewsTile.tsx (update: show sentiment score, color-coded headlines)",
    "phase1/tests/unit/test_sentiment_classifier.py (new: positive/negative/neutral classification accuracy)"],
   ["Multi-Source Aggregation: combine 3+ news sources, deduplicate by URL hash, weight by source reliability",
    "FinBERT for Financial NLP: pre-trained on financial text, handles domain jargon (dovish, hawkish, etc.)",
    "Entity-Symbol Mapping: 'Apple Inc' -> AAPL, 'Alphabet' -> GOOGL using maintained lookup + NER",
    "Temporal Decay: recent articles weighted more heavily (exp decay with 24h half-life)",
    "Sentiment Thresholds: very_negative < -0.5, negative < -0.2, neutral, positive > 0.2, very_positive > 0.5",
    "Earnings Amplification: sentiment score multiplied 2x during earnings week for that symbol"],
   ["Prompt: 'Build multi-source news collector: RSS feeds (Yahoo, Reuters), newsapi.org, finviz screener headlines.'",
    "Prompt: 'Implement FinBERT-based sentiment classifier that outputs polarity (-1 to 1) and confidence for financial text.'",
    "Prompt: 'Write entity extractor mapping article text to relevant ticker symbols using spaCy NER + company name lookup.'",
    "Prompt: 'Create sentiment aggregator: per-symbol daily score from multiple articles with temporal decay weighting.'",
    "Prompt: 'Update NewsTile component showing color-coded headlines: green for positive, red for negative, with sentiment score badge.'"],
   "NLP model running locally consumes GPU/RAM. Mitigation: use DistilBERT (lighter) or API-based inference. Cache results aggressively. Batch process, dont run per-request.",
   "NLP pipeline processes 100+ articles/day. Per-symbol sentiment score available via API. FinBERT accuracy > 85% on financial headlines."
)

_d(17, "Prometheus and Grafana Observability Stack",
   "Deploy Prometheus for metrics collection, Grafana for dashboards. Instrument backend with request latency, error rate, autopilot cycle timing, cache hit rates, queue depths.",
   ["pip install prometheus-client prometheus-fastapi-instrumentator",
    "docker pull prom/prometheus:latest && docker pull grafana/grafana:latest",
    "python3 -c \\"from prometheus_client import Counter, Histogram; print('prometheus_client ready')\\"",
    "grep -rn 'metrics\\|prometheus\\|counter\\|histogram' phase1/services/ | wc -l",
    "cat phase1/services/monitoring/ -la 2>/dev/null || echo 'monitoring dir exists'",
    "curl -s http://localhost:8000/metrics 2>/dev/null || echo 'No /metrics endpoint yet'",
    "python3 -c \\"from prometheus_fastapi_instrumentator import Instrumentator; print('FastAPI instrumentator ready')\\"",
    "docker compose -f docker-compose.unified.yml ps 2>/dev/null | head -5"],
   ["phase1/services/monitoring/metrics.py (new: define all Prometheus counters, histograms, gauges)",
    "phase1/services/monitoring/instrumentator.py (new: FastAPI middleware auto-instrumenting all endpoints)",
    "phase1/services/autopilot/unified_engine.py (update: emit cycle_duration histogram, phase_count counter)",
    "phase1/services/cache/redis_client.py (update: emit cache_hit/miss counters, cache_latency histogram)",
    "phase1/services/autopilot/hybrid_selector.py (update: emit llm_latency, llm_tokens_used, llm_errors)",
    "phase1/services/options/tradier_provider.py (update: emit api_latency, rate_limit_remaining gauge)",
    "phase1/services/api/main.py (update: mount Instrumentator, expose /metrics endpoint)",
    "monitoring/prometheus.yml (new: scrape config for backend, Redis, PG exporters)",
    "monitoring/grafana/dashboards/apex_overview.json (new: request rate, error rate, p95 latency, uptime)",
    "monitoring/grafana/dashboards/autopilot_metrics.json (new: cycle timing, candidate counts, trade outcomes)",
    "docker-compose.yml (update: add prometheus and grafana services with dashboards volume)",
    "phase1/tests/unit/test_metrics.py (new: verify counters increment, histograms observe, gauges set)"],
   ["RED Method: Rate (requests/sec), Errors (error rate), Duration (latency percentiles) for every endpoint",
    "USE Method: Utilization, Saturation, Errors for infrastructure (CPU, memory, DB connections, Redis)",
    "Custom Business Metrics: candidates_generated, candidates_selected, trades_executed, profit_total gauges",
    "Histogram Buckets: [0.01, 0.05, 0.1, 0.25, 0.5, 1, 2.5, 5, 10] seconds for latency distribution",
    "Alert Rules: p95 latency > 2s, error rate > 5%, autopilot cycle missing for 30min, kill switch activated",
    "Dashboard Hierarchy: Overview -> Autopilot -> LLM -> Broker -> Cache (drill-down pattern)"],
   ["Prompt: 'Define Prometheus metrics for trading platform: request counters, latency histograms, autopilot gauges, cache rates.'",
    "Prompt: 'Create Grafana dashboard JSON: 4 panels showing request rate, error rate, p95 latency, and active connections.'",
    "Prompt: 'Write alert rules: notify if p95 > 2s, error rate > 5%, autopilot stale > 30min, kill switch activated.'",
    "Prompt: 'Instrument the autopilot engine: emit duration per phase, candidate count, selection count, trade count.'",
    "Prompt: 'Create Docker Compose services for Prometheus (scraping backend) and Grafana (with provisioned dashboards).'"],
   "Metrics endpoint exposes internal state. Mitigation: /metrics behind auth or internal network only. Sanitize metric labels (no PII, no symbols in high-cardinality labels).",
   "Prometheus scraping backend /metrics. Grafana dashboard shows request rate, error rate, p95 latency, autopilot cycle timing. Alerts configured."
)

_d(18, "Position Sizing: Kelly Criterion and Risk Parity",
   "Implement advanced position sizing: Kelly criterion for optimal bet size, risk parity for portfolio-level allocation, and configurable max position limits per strategy.",
   ["python3 -c \\"kelly_f = (0.60*2.0 - 0.40) / 2.0; print(f'Kelly fraction: {kelly_f:.2%}')\\"",
    "python3 -c \\"import numpy as np; W=np.array([0.5,0.3,0.2]); cov=np.eye(3)*0.04; risk_contrib=W*np.dot(cov,W)/np.sqrt(np.dot(W,np.dot(cov,W))); print('Risk contrib:', risk_contrib)\\"",
    "grep -rn 'position.size\\|kelly\\|risk.parity\\|allocation' phase1/services/ | wc -l",
    "cat phase1/services/autopilot/config.py | grep -i 'max.*position\\|risk.*budget'",
    "python3 -c \\"max_risk=0.02; account=50000; max_loss_per_trade=max_risk*account; print(f'Max loss per trade: ${max_loss_per_trade}')\\"",
    "python3 -c \\"import numpy as np; wins=np.array([100,150,80,200,50]); losses=np.array([-60,-40,-80,-30,-50]); wr=len(wins)/(len(wins)+len(losses)); avg_w=wins.mean(); avg_l=abs(losses.mean()); kelly=(wr*avg_w-(1-wr)*avg_l)/(avg_w); print(f'Kelly: {kelly:.2%}')\\"",
    "cat phase1/services/autopilot/validator.py | grep -i 'position\\|size\\|budget'",
    "grep -rn 'class.*Config\\|max_positions\\|risk_budget' phase1/services/autopilot/config.py | head -10"],
   ["phase1/services/position_sizing/kelly.py (new: full Kelly, half-Kelly, quarter-Kelly with edge/odds estimation)",
    "phase1/services/position_sizing/risk_parity.py (new: equal risk contribution across positions using vol targeting)",
    "phase1/services/position_sizing/fixed_fractional.py (new: risk X% of account per trade, configurable)",
    "phase1/services/position_sizing/sizer.py (new: unified sizer choosing method based on strategy config)",
    "phase1/services/position_sizing/constraints.py (new: max position value, max contracts, max % of account, sector limits)",
    "phase1/services/autopilot/unified_engine.py (update: integrate position sizer before order placement)",
    "phase1/services/autopilot/config.py (update: add sizing_method, kelly_fraction, max_risk_per_trade params)",
    "phase1/services/autopilot/validator.py (update: position size check against portfolio-level constraints)",
    "frontend/src/features/portfolio/PositionSizingPanel.tsx (new: show sizing method, calculated size, risk contribution)",
    "phase1/tests/unit/test_kelly.py (new: known edge/odds -> expected fraction, half-Kelly cap)",
    "phase1/tests/unit/test_risk_parity.py (new: equal risk contribution verification, rebalancing trigger)"],
   ["Kelly Criterion: f* = (p*b - q) / b where p=win prob, q=1-p, b=win/loss ratio. Use half-Kelly for safety.",
    "Risk Parity: allocate so each position contributes equal portfolio risk (measured by marginal risk contribution)",
    "Fixed Fractional: simple but effective - risk exactly 2% of account per trade, adjust contracts accordingly",
    "Constraint Stack: min(Kelly size, fixed fractional, max contracts, max % account, sector limit, correlation limit)",
    "Dynamic Sizing: reduce size during drawdowns (fractional Kelly), increase during winning streaks (up to full Kelly)",
    "Portfolio Heat: track total portfolio risk as % of account, reduce new positions when heat > 15%"],
   ["Prompt: 'Implement Kelly criterion position sizer. Input: win rate, avg win, avg loss. Output: optimal fraction. Include half-Kelly option.'",
    "Prompt: 'Write risk parity allocator: given positions with individual vols, compute weights for equal risk contribution.'",
    "Prompt: 'Create unified position sizer that chains: Kelly -> fixed fractional -> max constraints -> output final size.'",
    "Prompt: 'Build PositionSizingPanel React component showing: method used, calculated size, risk %, portfolio heat gauge.'",
    "Prompt: 'Write tests for Kelly: 60% win rate, 2:1 ratio -> expected 40% Kelly. Half-Kelly -> 20%. Quarter -> 10%.'"],
   "Full Kelly is too aggressive for options (fat tails). Mitigation: always use half-Kelly or quarter-Kelly. Cap max position at 5% of account regardless of Kelly output.",
   "Position sizer computes optimal size per candidate. Half-Kelly with 2% max risk per trade. Portfolio heat tracked and visible in dashboard."
)

_d(19, "Trade Journal and Performance Analytics",
   "Build comprehensive trade journal that auto-records every trade with full context: entry reasoning, score, sentiment, MC results, and tracks P&L attribution by strategy, symbol, time.",
   ["pip install plotly kaleido openpyxl",
    "python3 -c \\"import plotly.graph_objects as go; fig=go.Figure(); print('plotly ready')\\"",
    "cat phase1/services/autopilot/ledger.py | head -30",
    "cat phase1/services/autopilot/reporting.py | head -30",
    "grep -rn 'journal\\|ledger\\|trade_log' phase1/services/ | wc -l",
    "python3 -c \\"import sqlite3; c=sqlite3.connect('phase1/phase1.db'); print(c.execute('SELECT COUNT(*) FROM trade_ledger').fetchone())\\"",
    "python3 -c \\"from datetime import datetime, timedelta; days=[(datetime.now()-timedelta(days=i)).strftime('%Y-%m-%d') for i in range(30)]; print(f'{len(days)} days of data')\\"",
    "grep -rn 'P.L\\|pnl\\|profit\\|loss' phase1/services/autopilot/ | wc -l"],
   ["phase1/services/journal/trade_journal.py (new: auto-record entry/exit with full decision context as JSON)",
    "phase1/services/journal/attribution.py (new: P&L attribution by strategy, symbol, time period, entry score)",
    "phase1/services/journal/analytics.py (new: win rate, avg hold time, best/worst trades, streak analysis)",
    "phase1/services/journal/equity_curve.py (new: daily equity curve with benchmarks SPY and drawdown overlay)",
    "phase1/services/journal/monthly_report.py (new: monthly P&L summary, strategy comparison, risk metrics)",
    "phase1/services/journal/export.py (new: export to CSV, Excel, PDF with charts)",
    "phase1/services/api/journal_routes.py (new: GET /journal/trades, GET /journal/analytics, GET /journal/report)",
    "phase1/services/autopilot/unified_engine.py (update: auto-journal every trade with context snapshot)",
    "frontend/src/features/reports/JournalView.tsx (new: searchable trade table with expandable context)",
    "frontend/src/features/reports/EquityCurve.tsx (new: interactive Plotly chart with drawdown overlay)",
    "phase1/tests/unit/test_attribution.py (new: P&L correctly attributed to strategy, symbol, time)"],
   ["Context Snapshot: every trade records market_data, sentiment, MC_results, score_breakdown, LLM_reasoning at entry",
    "P&L Attribution: decompose total P&L into: strategy alpha, market beta, timing luck, cost drag",
    "Equity Curve: daily mark-to-market with SPY benchmark, drawdown periods highlighted",
    "Monthly Reports: automated PDF with monthly P&L, strategy performance, risk metrics, lessons learned",
    "Export Formats: CSV for analysis, Excel for reporting, PDF for stakeholders, JSON for programmatic access",
    "Journal Queries: filter by strategy, symbol, date range, outcome, score range for pattern discovery"],
   ["Prompt: 'Build trade journaling system that auto-records: entry time, exit time, strategy, symbol, score, sentiment, reasoning, P&L.'",
    "Prompt: 'Implement P&L attribution: decompose total return into strategy alpha, market beta, timing, and costs.'",
    "Prompt: 'Create Plotly equity curve component with drawdown overlay, SPY benchmark, and monthly return annotations.'",
    "Prompt: 'Write monthly report generator: PDF with equity curve, strategy table, risk metrics, top/bottom trades.'",
    "Prompt: 'Build searchable trade journal UI with expandable rows showing full entry context, MC chart, and exit reasoning.'"],
   "Hindsight bias in journal review. Mitigation: context snapshot is immutable at entry time. Exit reasoning recorded at exit. No retroactive edits allowed.",
   "Every trade auto-journaled with full context. P&L attribution by strategy visible. Equity curve with benchmark in dashboard."
)

_d(20, "Multi-Strategy Orchestrator",
   "Build strategy orchestrator managing multiple concurrent strategies with independent risk budgets, configurable weights, correlation-aware allocation, and unified position management.",
   ["cat phase1/services/strategy/ -la 2>/dev/null || ls phase1/services/strategy/",
    "cat strategies/*.py | head -20",
    "grep -rn 'class.*Strategy\\|AbstractStrategy\\|BaseStrategy' phase1/services/ | wc -l",
    "cat phase1/services/autopilot/v1_templates.py | head -30",
    "python3 -c \\"strats=['iron_condor','put_credit_spread','call_debit_spread','covered_call','protective_put']; print(f'{len(strats)} strategies')\\"",
    "grep -rn 'template\\|strategy_name\\|strategy_type' phase1/services/autopilot/ | wc -l",
    "python3 -c \\"import numpy as np; corr=np.corrcoef(np.random.randn(5,100)); print(f'Avg corr: {corr[np.triu_indices(5,1)].mean():.3f}')\\"",
    "cat phase1/services/autopilot/config.py | grep -i 'strategy\\|template'"],
   ["phase1/services/strategy/orchestrator.py (new: manage multiple strategies with independent lifecycles)",
    "phase1/services/strategy/strategy_registry.py (new: register/discover strategies with metadata and config schema)",
    "phase1/services/strategy/base_strategy.py (new: abstract base with generate_candidates, manage_positions, should_exit)",
    "phase1/services/strategy/iron_condor.py (new: full IC strategy with entry/exit/adjustment logic)",
    "phase1/services/strategy/put_credit_spread.py (new: PCS with IV rank and delta targeting)",
    "phase1/services/strategy/covered_call.py (new: CC on portfolio holdings with strike selection logic)",
    "phase1/services/strategy/risk_allocator.py (new: divide risk budget across strategies based on config weights)",
    "phase1/services/strategy/correlation_monitor.py (new: track inter-strategy correlation, alert on concentration)",
    "phase1/services/autopilot/unified_engine.py (update: iterate over registered strategies instead of single template)",
    "phase1/services/api/strategy_routes.py (new: CRUD for strategies, enable/disable, update config)",
    "frontend/src/features/strategy/StrategyManager.tsx (new: card-based strategy management with toggle/config)",
    "phase1/tests/unit/test_orchestrator.py (new: multi-strategy allocation, risk budget enforcement, correlation check)"],
   ["Strategy as Plugin: each strategy is a self-contained module with standard interface (generate, manage, exit)",
    "Risk Budget Allocation: total portfolio risk split among strategies (e.g., IC=40%, PCS=30%, CC=30%)",
    "Correlation-Aware: if two strategies have > 0.7 correlation, reduce combined allocation by 30%",
    "Independent Lifecycle: each strategy has its own state machine, config, and monitoring schedule",
    "Portfolio-Level Constraints: total positions <= max, total risk <= budget, sector concentration <= threshold",
    "A/B Testing: run strategies in parallel with equal allocation, compare performance over time"],
   ["Prompt: 'Design strategy orchestrator managing 5 concurrent strategies with independent risk budgets and correlation monitoring.'",
    "Prompt: 'Write BaseStrategy abstract class with: generate_candidates, manage_positions, should_exit, get_metrics methods.'",
    "Prompt: 'Implement Iron Condor strategy: entry on high IV rank, exit at 50% profit or 21 DTE, adjust if tested.'",
    "Prompt: 'Build StrategyManager React component: cards per strategy with enable/disable toggle, config editor, and live P&L.'",
    "Prompt: 'Write risk allocator dividing portfolio budget across strategies with correlation-based adjustment.'"],
   "Multiple strategies competing for same capital can over-allocate. Mitigation: orchestrator checks total allocation before any trade. Portfolio-level hard limits enforced by validator.",
   "3+ strategies registered and running concurrently. Each has independent risk budget. Portfolio total risk monitored. Strategy performance compared side-by-side."
)
'''
