export * from './types';

export {
  historicalVaR,
  parametricVaR,
  cornishFisherVaR,
  monteCarloVaR,
  portfolioMonteCarloVaR,
  stressedVaR,
  backtestVaR,
  attributePnL,
  computeSensitivities,
  sensitivityLadder,
  factorRiskDecomposition,
  marginalRiskContribution,
  componentRiskContribution,
  incrementalVaR,
  riskBudget,
  herfindahlIndex,
  effectiveN,
  topNExposure,
  sectorConcentration,
  rollingCorrelation,
  regimeDependentCorrelation,
  peaksOverThreshold,
  blockMaxima,
  calculateVaR,
  tailRiskMetrics,
  fullVaRReport,
} from './marketRisk';

export {
  getHistoricalScenarios,
  getScenarioById,
  buildHypotheticalScenario,
  buildCorrelationStressScenario,
  buildLiquidityStressScenario,
  buildSectorStressScenario,
  buildCountryStressScenario,
  calculateScenarioPnL,
  stressTestWithLimits,
  reverseStressTest,
  generateSensitivityLadder,
  multiFactorStress,
  combinedScenario,
  sequentialScenarioPnL,
  compareScenarios,
  concentrationStress,
  runAllHistoricalScenarios,
  worstCaseScenario,
} from './stressTesting';
export type { ScenarioComparison } from './stressTesting';

export {
  mapToSPEquivalent,
  ratingToNumeric,
  numericToRating,
  isInvestmentGrade,
  getTransitionMatrix,
  transitionProbability,
  multiYearTransition,
  historicalPD,
  mertonPD,
  altmanZScore,
  altmanZScorePD,
  estimateLGD,
  calculateEAD,
  expectedLoss,
  unexpectedLoss,
  creditVaR,
  creditVaRMonteCarlo,
  creditSpreadFromPD,
  impliedPDFromSpread,
  creditSpreadDuration,
  cdsPremium,
  cdsMarkToMarket,
  calculateCVA,
  calculateDVA,
  calculateFVA,
  calculateBilateralCVA,
  identifyWrongWayRisk,
  creditMigrationPnL,
  creditConcentration,
  sectorCreditExposure,
} from './creditRisk';

export {
  BASEL_CATEGORIES,
  createKRI,
  updateKRI,
  getDefaultKRIs,
  createLossEvent,
  categorizeEvents,
  lossDistributionApproach,
  fitFrequencyDistribution,
  fitSeverityDistribution,
  calculateRCSA,
  rcsaSeverity,
  basicIndicatorApproach,
  standardizedApproach,
  advancedMeasurementApproach,
  escalateEvent,
  addRemediation,
  updateRemediationStatus,
  checkOverdueRemediations,
  evaluateRiskAppetite,
  assessControlEffectiveness,
  computeOpRiskSummary,
} from './operationalRisk';
export type {
  LDAResult,
  RiskAppetiteMetric,
  ControlAssessment,
  OpRiskSummary,
} from './operationalRisk';

export {
  frtbDeltaCharge,
  frtbVegaCharge,
  frtbCurvatureCharge,
  frtbDefaultRiskCharge,
  frtbResidualRiskAddOn,
  calculateFRTB,
  calculateBaselIII,
  checkBaselIIICompliance,
  calculateRWA,
  simmDeltaMargin,
  simmVegaMargin,
  simmCurvatureMargin,
  calculateISDAMargin,
  volckerComplianceCheck,
  generatePositionReport,
  checkLargeExposures,
  calculateRegulatoryCapital,
  generateRegulatoryMetrics,
} from './regulatory';
export type {
  VolckerMetrics,
  PositionReport,
  LargeExposureResult,
  RegulatoryCapitalSummary,
} from './regulatory';

export {
  createLimit,
  computeLimitStatus,
  updateLimitUtilization,
  checkLimits,
  detectBreaches,
  trackLimitUtilization,
  buildLimitHierarchy,
  requestTemporaryIncrease,
  expireTemporaryIncreases,
  aggregateLimits,
  preTradeCheck,
  canExecuteTrade,
  createLimitApproval,
  approveLimitRequest,
  rejectLimitRequest,
  getLimitDashboard,
} from './limits';
export type {
  LimitCheckResult,
  LimitUtilizationHistory,
  LimitHierarchyNode,
  AggregatedLimit,
  PreTradeCheckResult,
  LimitApproval,
  ApprovalStatus,
  LimitDashboardSummary,
} from './limits';
